### ISSUE TITLE
ibm_sherbrooke optimization_level=3 

### ISSUE THREAD

**Issue by bsiegelwax** [Qiskit/qiskit#10138]
### Environment

IBM Quantum Lab

### What is happening?

![transpiled_ghz](https://github.com/Qiskit/qiskit-terra/assets/70060202/4314cb20-e10f-4ba2-8582-9c9259a5c471)
This is what optimization_level=3 does to a 54-qubit GHZ on ibm_sherbrooke.

### How can we reproduce the issue?

I tried multiple circuits and they all had similar results, so it should happen with any large GHZ state.

### What should happen?

Many qubits are shown to not have multi-qubit operations, but all 54 participated in at least one multi-qubit operation.

### Any suggestions?

This is from experimentation after the IBM Quantum Spring Challenge. The circuit produced sheer noise, so I wanted to see if optimization_level=3's mapping feature would improve qubit selection and improve the results.

**Comment by bsiegelwax** [comment]
One of them was:
```
qc.h(q[0])
for i in range(0, 6):
    for j in range(0, 2**i):
        if ((2**i)+j) == 54: break
        qc.ecr(q[j], q[(2**i)+j])
```
followed by:
```
qc_list = transpile([qc]*20, backend, optimization_level=3, layout_method='sabre', routing_method='sabre', approximation_degree=0)
best_depth = [circ.depth() for circ in qc_list]
best_idx = np.where(best_depth == np.min(best_depth))[0][0]
qc_transpiled = qc_list[best_idx]
'''

**Comment by jakelishman** [comment]
Ok, thanks - this looks likely to be some problem being introduced by `approximation_degree`; I can reproduce your results with it set, but not without it.  Setting that to "0" is telling the unitary resynthesis algorithms to use maximal approximations (maybe backwards to what you'd expect), so there are likely various 2q collected blocks that are getting approximated at some intermediate stage to identities, and consequently removed.

**Comment by bsiegelwax** [comment]
As an extension of this issue, I carefully crafted a 54-qubit GHZ with 1 Hadamard and 53 ECRs. The transpiled circuit has 53 ECRs, but it adds a bunch of Hadamards everywhere, tripling the depth of the circuit from 12 to 34 using optimization_level=1, the shallowest of the 4 presets. The results are sheer noise. The results are the same from the QASM editor. The depth was slightly worse with CX, which I also tried. If I did all the hard work manually of selecting qubits and connecting them, why is the transpiler adding so much noise?

chmscrlnopt07g4g0pk0
chmri0hike34bjj1nql0
![before](https://github.com/Qiskit/qiskit-terra/assets/70060202/a4df80b1-f6a6-4428-a692-ce2bf1365b27)
![after](https://github.com/Qiskit/qiskit-terra/assets/70060202/c0a08c2e-00ea-42fe-b961-9e562e0ad4a9)

**Comment by jakelishman** [comment]
The ecr gate isn't symmetrical, and Sherbrooke implements ecr only in the native direction of each link.  The extra y rotations and hadamards are most likely the transpiler "flipping" your gates so they can run on the hardware.

**Comment by bsiegelwax** [comment]
The result with CX was worse. I think the least depth was 44 with CX vs 34 with ECR and optimization_level=1.

**Comment by jakelishman** [comment]
Yes, Sherbrooke doesn't support cx natively at all.  If you're trying to do hardware-specific optimisations by hand, you might want to examine the `.target` attribute of the particular backend; you can find all the information about the supported gates and their directions in there.

**Comment by jakelishman** [comment]
I'm going to close this issue now because it's quite old, and I don't think there's anything more to be done.  The initial problem was that setting `approximation_degree` in the transpiler was asking it to aggressively approximate the output, which is why the gate space was reduced.  Removing that option should have restored unitary equality.  The following issues seemed to be around broken assumptions that ECR is implemented symmetrically; it isn't, so the transpiler was correctly rewriting circuits to make the input circuit safely natively runnable.

Please feel free to open a new issue if there's more to discuss.
