### ISSUE TITLE
BasicSwap FakeRun Typo

### ISSUE THREAD

**Issue by evmckinney9** [Qiskit/qiskit#10147]
### Environment

- **Qiskit Terra version**: 
qiskit-terra             0.23.3

### What is happening?

basic_swap.py has boolean parameter `fake_run`, when true should return the dag before adding in SWAP gates. However,
```python
if self.fake_run:
            return self.fake_run(dag)
```
this should be `self._fake_run(dag)` to reference the class' function instead of the attribute.
Error indicated by `TypeError: 'bool' object is not callable`

### How can we reproduce the issue?

```python
from qiskit.transpiler.passes.routing import BasicSwap

swapper = BasicSwap(coupling, fake_run=True)
dag = swapper.run(dag)
```

### What should happen?

Call the class function

### Any suggestions?

```python
if self.fake_run:
            return self._fake_run(dag)
```

**Comment by jakelishman** [comment]
Thanks for the report!  Would you like to make a PR fixing it?

**Comment by evmckinney9** [comment]
Will do. I'll check the other passes as well for this typo.
