### ISSUE TITLE
Transition `package_name` in deprecation decorator to `qiskit` as default

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10202]
The decorators [`deprecate_arg`](https://qiskit.org/documentation/stubs/qiskit.utils.deprecate_arg.html) and [`deprecate_function`](https://qiskit.org/documentation/stubs/qiskit.utils.deprecate_function.html) have a parameter `package_name` that defaults to `qiskit-terra`.

Considering that the `qiskit` metapackage is on track to have a single dependency on `qiskit-terra` and their versions are going to be the same in the future (see [RFC0011](https://github.com/Qiskit/RFCs/blob/master/0011-repo-rename.md#future-extensions)), the notion of Terra is getting hidden under the Qiskit brand. As such, it makes sense that the documentation refers less to Terra and invites users to update `qiskit`.

From:
<img width="771" src="https://github.com/Qiskit/qiskit-terra/assets/766693/b03b3817-bd37-4b2b-9457-0b31d31fd883">

To:
<img width="772" src="https://github.com/Qiskit/qiskit-terra/assets/766693/ed9f2fd1-b740-494c-a4d9-e552c26287c3">

**Comment by Raghav-Bell** [comment]
can i also contribute to this issue ?

**Comment by Eric-Arellano** [comment]
Sure! Although, @1ucian0 we can't do this until qiskit releases using the same version number as qiskit-terra, right?

**Comment by jakelishman** [comment]
This is going to be tricky, even when the most recent version numbers are aligned.  All existing releases were deprecated using the version of `qiskit-terra`, and old releases won't (can't) change number.  The old deprecations probably still need to refer to the release of Terra they were deprecated in - I think it'll be very confusing if we change all of those to point to "metapackage" versions instead, since it's quite possible that a lot of people never installed the metapackage.

**Comment by 1ucian0** [comment]
@Eric-Arellano said:
> we can't do this until qiskit releases using the same version number as qiskit-terra, right?

right. This issue is about planning that transition because I see, like @jakelishman, this might be complicated.

Here some options:

 * have a dynamic default that is qiskit-terra if `since=0.*` and qiskit if `since=1.*`
 * systemically change number from the `qiskit-terra` domain to `qiskit` domain using https://qiskit.org/documentation/release_notes.html#version-history  (eg `qiskit-terra 0.24.0` to `qiskit 0.43.0`)
 * other?

**Comment by 1ucian0** [comment]
I think this is closed by https://github.com/Qiskit/qiskit/pull/10877
