### ISSUE TITLE
Add Covariance Matrix Adaptation Evolution Strategy (CMA-ES) optimizer for VQAs

### ISSUE THREAD

**Issue by Unathi-Skosana** [Qiskit/qiskit#10262]
### What should we add?

Qiskit terra interface for [CMA-ES](https://cma-es.github.io/) which is a stochastic derivative-free numerical optimization algorithm, observed  in  [arXiv:2111.13454](https://arxiv.org/abs/2111.13454) to be on par with and sometimes outperforming SPSA with appropriate hyperparameter tuning [^1].

[^1]: I would be more than happy to work on this.

**Comment by Cryoris** [comment]
@MarcDrudis almost finished the implementation of CMA-ES during the work on #8170, which would be nice to get in.

**Comment by ElePT** [comment]
Transferred to new repo: https://github.com/qiskit-community/qiskit-algorithms/issues/62
