### ISSUE TITLE
write a how-to: Obtaining information about a backend 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10317]
Based on https://github.com/Qiskit/qiskit-tutorials/blob/5ecfec18301299b58ac16be0151541484eae03f6/tutorials/circuits_advanced/08_gathering_system_information.ipynb, Qiskit needs a how-to on Obtaining information about a backend. The main difference with the previous versions is to port it to backend v2.

**Comment by ayukumar11** [comment]
@1ucian0 I'm interested in contributing to this documentation. Is this a good first issue for me to work on ?

**Comment by 1ucian0** [comment]
I wouldn't call it a good first issue, but If you are familiar with backendV2 and [our documentation guidelines](https://qisk.it/docs-guide), I think it is doable. There are many good first issues in https://qisk.it/good-first-issues

**Comment by MaldoAlberto** [comment]
@1ucian0 I can take this in case that nobody is working

**Comment by ayukumar11** [comment]
@1ucian0 I'm familiar with the backend and learning about sphinx as well. Thank you for the link ! 
I'd like to take this up ? Can you please assign it to me ?

**Comment by 1ucian0** [comment]
Sure.. assigning you @ayukumar11

**Comment by MaldoAlberto** [comment]
Hey @ayukumar11, how's it going working on this? We're trying to coordinate the timeline for this issue as part of the qiskit-metapackage migration in https://github.com/Qiskit/qiskit-tutorials/issues/1473
Also let me know if I can help! And feel free to hand the ticket off to me if you'd prefer, but 100% okay to keep working on this!

**Comment by ayukumar11** [comment]
Hi @MaldoAlberto I have started working on it. What time frame are you looking at for the metapackage migration for me to level set ?

**Comment by abbycross** [comment]
This information now exists in the Guides: https://docs.quantum.ibm.com/guides/get-qpu-information so closing this issue.
