### ISSUE TITLE
write a "get started with Qiskit" tutorial 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10315]
Part of https://github.com/Qiskit/qiskit-tutorials/issues/1473

The [qiskit intro](https://github.com/Qiskit/qiskit-metapackage/blob/master/docs/intro_tutorial1.rst), [circuit basics](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits/01_circuit_basics.ipynb) and [getting started with qiskit](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits/1_getting_started_with_qiskit.ipynb) tutorials need to be merged in a single "get started with Qiskit" tutorial in this repo.

Related issues:
 * https://github.com/Qiskit/qiskit-terra/issues/10613
 * https://github.com/Qiskit/qiskit-metapackage/issues/1497
 * https://github.com/Qiskit/qiskit-metapackage/issues/1352
 * https://github.com/Qiskit/qiskit-tutorials/issues/1434

**Comment by frankharkins** [comment]
@1ucian0 please assign me :)

**Comment by resduo** [comment]
@frankharkins To prevent conda or python version conflict, should we add a more specific tutorial on virtual environment setup? p/s: Since qiskit is not dependent on many exotic packages or dependencies, docker container is not worth to be investigated, so far.

**Comment by resduo** [comment]
@frankharkins I see that many new-experience users encounter the dependencies conflict. For this, I guess the simplest, yet effective approach is to use [pyenv](https://github.com/pyenv/pyenv). What do you think if we add the installation instruction of pyenv, and how to manage the versions of dependencies through it, for both qiskit usage and contribution?

**Comment by javabster** [comment]
This was completed a while ago in IQP docs with the creation of the "Start" section: https://docs.quantum.ibm.com/start
