### ISSUE TITLE
QAOA callback attribute docstring incorrectly includes best measurement

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit#10434]
The QOAO callback attribute docstring says this

```
        callback (Callable[[int, np.ndarray, float, dict[str, Any]], None] | None): A callback
            that can access the intermediate data at each optimization step. These data are: the
            evaluation count, the optimizer parameters for the ansatz, the evaluated value, the
            the metadata dictionary, and the best measurement.
```

Whereas the callback parameter in the constructor does not have `and the best measurement` nor does the SamplingVQE callback, in either situation, that this class extends where the callback is done by the parent. I believe `and the best measurement` should just be simply removed unless there was somehow an intent to have had this - but the callback signature does not accommodate such presently.

**Comment by ElePT** [comment]
Transferred to new repo: https://github.com/qiskit-community/qiskit-algorithms/issues/48
