### ISSUE TITLE
Wrong global phase in 1q Pauli equivalence release note

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit#10527]
### Environment

- **Qiskit Terra version**: 0.25
- **Python version**: n/a
- **Operating system**: n/a

### What is happening?

The release note added in #10300 contains incorrect circuit identities, and I think the actual equivalences might be wrong too (but I would have to brush up on my understanding of `global_phase` to be sure).  Specifically, the release note _should_ say $X=-iYZ$, $Y=-iZX$, and $Z=-iXY$, but these are specified incorrectly (without the minus sign).

### How can we reproduce the issue?

n/a

### What should happen?

n/a

**Comment by jakelishman** [comment]
Oh damn, you're right - I had the relationship backwards in my head, and it wasn't caught by testing because the test (and what I did locally too) only uses `Operator(gate) == Operator(circuit)`, which deliberately throws away the global phase.

**Comment by jakelishman** [comment]
Ah no, panic over: the equivalences are actually correct, and so is the test that verifies them, it's just the release note that's wrong about what's implemented.  I'd just confused myself both then and here:
```python
from qiskit import QuantumCircuit
qc = QuantumCircuit(1)
qc.x(0)
qc.y(0)
```

does _not_ correspond to `X @ Y`, it corresponds to `Y @ X` - the state is on the right lol.  I'll just go hand back my PhD.

I just screwed up the release note: I put in the relations as $X = iZY$ etc, but wrote $X = iYZ$.
