### ISSUE TITLE
Framework for realistic experimental backends

### ISSUE THREAD

**Issue by Matt-RFI** [Qiskit/qiskit#10529]
### What should we add?

There are different versions of Backend objects that exist in Qiskit Terra, such as `FakeBackend` which inherits from `BackendV2`. Additionally, there are other simulator-based backends like the QASM simulator and the statevector simulator. Ultimately, the results from these simulators are not as practical and true-to-hardware as the results from existing IBM Quantum backends. A potential solution to this problem is to create a realistic experimental backend generator that takes information from IBM Quantum backends, samples from this data, and replicates the backend’s performance. The information of the backend will be stored in a `BackendSpec` object that the user can utilize to generate new backends. The following is a more detailed look at this potential solution:

<img width="813" alt="Screenshot 2023-07-28 at 12 13 12 PM" src="https://github.com/Qiskit/qiskit-terra/assets/60669376/448b3c1e-aff5-4727-9139-f8e25c49180f">

There are two ways a user can construct a BackendSpec object: 

1. The user inputs an existing backend
2. The user constructs a backend with custom specifications

In both cases the BackendSpec class creates/samples from the information inputted by the user, and the class also contains modifier functions which can change certain parts of a backend spec, including the number of qubits, coupling map, and error rates. The class then samples from these values and feeds them into the RealisticBackend class, which returns a BackendV2 object. Some example code from the API is shown below:

```
parent_backend = provider.get_backend('example backend')
backend_spec = BackendSpec(parent_backend)

backend_spec.set_qubit_property(0, 'T1', 0.73)
backend_spec.set_qubit_property(1, 'error_rate', 0.43)

new_backend = backend_spec.normal_distribution()
qc = QuantumCircuit(18)
qc.h(0)
qc.measure_all()
job = execute(qc, backend=new_backend, shots=4000)
```

**Comment by jakelishman** [comment]
The backends in `qiskit.providers.fake_provider` literally use calibration data from their equivalent `qiskit-ibm-provider` backends, although we admittedly don't really update that once we've made it once.

What you describe is, I think, both the domain of Qiskit Aer, but also already implemented there.  You can use [`NoiseModel.from_backend`](https://qiskit.org/ecosystem/aer/stubs/qiskit_aer.noise.NoiseModel.from_backend.html) to get the object with up-to-date calibrations from whatever backend you like, then execute on `AerSimulator` (which is all the fake backends do anyway), using that noise model.

Fwiw, `execute` is not a preferred way to run a circuit on a backend - it's a fast-path only.  You get access to the full range of options by doing
```python
from qiskit import transpile
qc = ...
backend = ...
transpiled = transpile(qc, backend, <transpile options>)
job = backend.run(transpiled, <backend-specific run options>)
```

**Comment by jakelishman** [comment]
In that case, I think that much of what you're describing is called [`Target`](https://qiskit.org/documentation/stubs/qiskit.transpiler.Target.html) in Qiskit, as it's the fundamental component that describes the properties of a backend.  There's documentation on that page about how to construct one, and you can pass one to `transpile` using the `target` keyword argument, instead of passing a full backend.

**Comment by jakelishman** [comment]
Fwiw, all the extra helper methods that you might want to have to investigate the properties of various error distributions and whatnot would, I think, be a bit more suited to a separate package to provide them; they sound quite specific to one particular type of research.  You could make that, if you like and it'd help your work, and you can contribute it to [the Qiskit ecosystem](https://qiskit.org/ecosystem).

**Comment by jakelishman** [comment]
I'll close this as stale now, or "already implemented via `Target`".  Feel free to re-open if there's more to discuss.
