### ISSUE TITLE
Unroller fails on `h` gate

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#10586]
### Environment

- **Qiskit Terra version**:  latest
- **Python version**:  3.10
- **Operating system**: 

### What is happening?

```python

from qiskit import QuantumCircuit
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes.basis import Unroller


qc = QuantumCircuit(5)
qc.h(0)
qc.rz(0.1, 0)
qc.rzz(np.pi/2, 0, 2)

unroll_pass = Unroller(basis=['cx', 'sx', 'x', 'rz'])

pm = PassManager([unroll_pass])
pm.run(qc)
```

gives

QiskitError: "Error decomposing node of instruction 'h': 'NoneType' object has no attribute 'global_phase'. Unable to define instruction 'u' in the basis."

### How can we reproduce the issue?

Run above

### What should happen?

I should be able to unroll to the target basis

### Any suggestions?

-

**Comment by jakelishman** [comment]
The unroller is a very basic hierarchical basis translation, and cannot guarantee that a source basis will be able to be converted. In general, the only basis that's more-or-less certain (up to opaque instructions) to work is the OpenQASM 2 general basis `u, cx`. This is kind of fundamental to what the `Unroller` actually represents.

In general, you'll want to use a full `translation` transpiler stage to most reliably convert bases. For built-in standard Qiskit gates, `BasisTranslator` with the `StandardEquivalenceLibrary` will typically be enough.

**Comment by nonhermitian** [comment]
It begs the question then as to why the `Unroller` is even still in Qiskit if it can no longer even handle an `h` gate?  Moreover, it is at the top of the basis change passes section.  Given the order is not alphabetical, this implies it is the pass of choice when doing basis changes:

![image](https://github.com/Qiskit/qiskit-terra/assets/1249193/e4801d54-8cb3-48b5-bfe4-d69cf589ede8)


I did originally try the `BasisTranslator`, but I have no idea how to add a equivalence library, and there is no minimal example in the pass documentation that shows me how to get it working: https://qiskit.org/documentation/stubs/qiskit.transpiler.passes.BasisTranslator.html#qiskit.transpiler.passes.BasisTranslator  Is it not possible to default to the standard library, as you suggest above, if none is given?  This would make life easier for the vast majority of users.

**Comment by jakelishman** [comment]
This stems from a misunderstanding of how basis translation works. `Unroller` can handle `h` for some target bases. This is true for any basis translation; we can't universally translate from _any_ source basis to _any_ target basis with any of the methods we have defined.

We do default if you use the full compiler path.  When you want to access compiler internals outside the full path, you need to handle configuration yourself; us adding default state arguments to the constructors of internal objects would make it easier to introduce bugs or surprising behaviour when defaults at different entry points get out of sync. This has happened frequently in the circuit drawers, and continues to cause problems there. In principle, the lower level you want to enter our stack, the more manual configuration you'll need to do.

Our documentation can always be improved, and this is one place.

**Comment by nonhermitian** [comment]
> In principle, the lower level you want to enter our stack, the more manual configuration you'll need to do.

And where we have big gaps in the documentation.  So very much agree with you.

**Comment by nonhermitian** [comment]
I think this is closed now given that Unroller is gone and replaced in #10607
