### ISSUE TITLE
Any clue how to introduce "actual" weak measurement?

### ISSUE THREAD

**Issue by SeifMostafa** [Qiskit/qiskit#10593]
### What should we add?

I am not approaching using slight rotation and ancillary qubit to simulate approx. weak measurement. Targeting actual weak measurement. It could be achieved with new operator and some advanced digging, ready to do so but might need some guidance from you.

**Comment by aeddins-ibm** [comment]
Hi SeifMostafa, I think you can already do this through through qiskit.pulse, by pulling the default measurement pulses from the backend object and then reducing those pulse amplitudes (maybe also durations) to make the measurements weaker. I agree it will likely require some "advanced digging" as you predict.
https://qiskit.org/documentation/apidoc/pulse.html
https://qiskit.org/documentation/stubs/qiskit.pulse.channels.MeasureChannel.html

Depending on your goals, you may want to calibrate the strength of a measurement at the qubit by looking at the dephasing induced by the measurement. This can be done by applying your measurement pulse inside a Ramsey sequence. There are a few ways to implement this; e.g. Fig 1b in https://arxiv.org/abs/1711.05336.

**Comment by 1ucian0** [comment]
@SeifMostafa, did @aeddins-ibm answer your question?

**Comment by SeifMostafa** [comment]
@1ucian0, still trying to implement it myself as @aeddins-ibm direction guide proposed, will update here soon.

**Comment by 1ucian0** [comment]
It seems to me this is not a feature request but maybe a tutorial request. Not fully sure. i will close this it `stale` for now. If there is something concrete that you think Qiskit should include, feel free to reopen this one or open a new one.
