### ISSUE TITLE
exceptions coming from Jupyter calls are not detectable by 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10603]
If documentation is built at PR-time to make sure that changes do not break it. When an exception is triggered, the PR is blocked. However, when the exception comes from Jupyter notebook itself, CI is not detecting it. Take https://github.com/Qiskit/qiskit/issues/10677 as an example where the `_repr_jpg_` call raised.

While I understand these situations are rare, it would be great if CI could account for them as they also affect the documentation output (following the previous example: https://qiskit.org/documentation/stable/0.44/tutorials/circuits_advanced/04_transpiler_passes_and_passmanager.html  )

**Comment by jakelishman** [comment]
To be clear, the problem here is when an exception is triggered by an _implicit_ IPython call during a cell output's rich-display resolution, which appear not to be propagated up to our actual execution context, but are silently displayed inline.

**Comment by jakelishman** [comment]
This is obsolete now because we don't have any Jupyter notebooks in the repo any more since the tutorials docs moved out.
