### ISSUE TITLE
Documentation should elucidate what the main Qiskit functionality is

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#10600]
### What should we add?

Currently the documentation does not describe anywhere what Qiskit is actually used for in practice.  Rather, one sees the following screen that just has redirects to things other than Qiskit itself; the docs homepage wants users to leave the Qiskit docs.

![image](https://github.com/Qiskit/qiskit-terra/assets/1249193/016e903a-5895-4b19-9a0f-0addd5c34742)

Instead, the documentation should focus on what the Qiskit package is utilized for, namely circuit construction, circuit library, circuit transformations (transpilation), and execution (via IBM and ecosystem partners).  It is likely that having subsections to the docs for each of these topics, amongst other docs improvements, would go along way for making the docs more useful for end users.

**Comment by yusharth** [comment]
What changes do you suggest, and how can I assist in moving forward with that? Should we focus on a comprehensive explanation of Qiskit and its features for a few paragraphs, or should we emphasize its applications and advantages over other available frameworks? I'm interested in contributing, but I would appreciate more details about the requirements.

**Comment by nonhermitian** [comment]
Many thanks for offering to help.  The main functionality of Qiskit is building circuits or making use of the circuit library, circuit transformations, and circuit execution / processing (perhaps with the use of ecosystem providers).  None of these core features are mentioned / described anywhere.  This is a large chunk of work, so I would talk to @1ucian0, and/or @javabster about how to proceed here.

**Comment by yusharth** [comment]
I would be happy to be part of the discussions as well and learn more about Qiskit and QC in general. I might be able to do some significant contributions as well. So please let me know if you plan any meeting or discussion over a chat about this issue. I would request you to keep me involved as it would be a great learning experience as well.

**Comment by 1ucian0** [comment]
Hi @yusharth, welcome and thanks for volunteer in the project. Have a look to https://qisk.it/good-first-issues for issues that we considered are a good entry point to Qiskit-related projects.

This issue in particular is maybe not the best first issue, as it depends on several conversations that are happing as we speak.

**Comment by Eric-Arellano** [comment]
Going to close given that docs are moving to https://docs.quantum-computing.ibm.com on Nov 29 ([announcement](https://medium.com/qiskit/important-changes-to-qiskit-documentation-and-learning-resources-7f4e346b19ab)), hosted at https://github.com/Qiskit/documentation.

Please open an issue there if you believe this is still a problem with the new docs.
