### ISSUE TITLE
Review and refactor docs intro pages

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit#10613]
I'm creating this issue here for now as the files in question still live in this repo, but we can move this issue to terra later (or maybe consider this work as part of the migration)

In recent discussions with users it has been highlighted that there is some confusion around the "getting started", "qiskit introduction" and "qc in a nutshell" pages. It is unclear to users where they should go for certain needs. I propose the following changes, further ideas/discussion are very welcome!

**1. remove the "qc in a nutshell" page**
This might be a controversial suggestion, but I think in qiskit.org we should be moving away from trying to teach people quantum computing (at least not at this basic level) and instead be nudging people to go to the qiskit textbook for this kind of info.

**2. Rename "getting started" to "Installation"**
It was brought up in user feedback sessions that new users assumed that links to the getting started page would take them to a "hello world" type of example, or the "qc in a nutshell" type of content. I think using a term like "Installation" would be better for this page. We should also update the "next steps" section at the bottom depending on what we decide to do with the other pages

**3. rename "qiskit introduction" to "Get started" or "get started with qiskit" or similar.** 
The "qiskit introduction" page feels like the closest to a "hello world" type of example that should live under the getting started label. Also explicitly titling it "get started with qiskit" could help people understand that this is specifically for qiskit and not for learning quantm computing in general

**4. refactor the "qiskit introduction" page to better address new user needs.**
This probably requires some more thought/discussion, but we could also refer to the qiskit.org homepage and use some of the quick start examples from there and expand them a bit, including the primitives as well. We should also add links at the top to direct people to the installation page if they haven't already got qiskit installed and another link to the qiskit textbook if they need info on learning quantum computing

note: if we rename the getting started page we should update the qiskit.org landing page accordingly

**Comment by javabster** [comment]
@jakelishman I think [this outstanding PR](https://github.com/Qiskit/qiskit-terra/pull/10328) should be merged before closing this issue

**Comment by abbycross** [comment]
Given the extensive changes to the docs, ok to close this issue @javabster ?
