### ISSUE TITLE
Discourage search engines from indexing old documentation builds

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit#10616]
Often, outdated versions of the qiskit documentation rank higher in search engine results than current documentation.  This is especially noticable with Qiskit/qiskit-metapackage#1389, as many of these pages are broken links, currently.

### What is the expected behavior?

We should try to prevent outdated documentation from appearing in search results.  This can be improved by adding `<meta name="robots" content="noindex">` to the `<head>` of each page in each old documentation build.

**Comment by jakelishman** [comment]
Also, after #10610, this will also apply to the `/dev` documentation as well.

**Comment by garrison** [comment]
I believe there is nothing left for the Qiskit developers to do here, especially now that the documentation is no longer on qiskit.org.
