### ISSUE TITLE
Deprecate Qiskit Visualizations tutorial

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit#10653]
As part of the Qiskit Documentation content restructuring efforts, [Qiskit Visualizations tutorial](https://qiskit.org/documentation/tutorials/circuits/2_plotting_data_in_qiskit.html) is moving to the content to API reference and will be deprecated. Related issue: https://github.com/Qiskit/qiskit-tutorials/issues/1436

We should

- [ ] replace the current tutorial notebook with a deprecation warning notebook
- [ ] in the notebook, gives user a deprecation warning, direct users to [`qiskit.visualization` API reference page](https://qiskit.org/documentation/apidoc/visualization.html) and link to this issue for any comment.
- [ ] tell users that they can still access the old notebook in older version of the documentation page: https://qiskit.org/documentation/stable/0.36/tutorials/circuits/2_plotting_data_in_qiskit.html
- [ ] Redirect https://qiskit.org/documentation/tutorials/circuits/2_plotting_data_in_qiskit.html link permanently to the deprecated version, probably https://qiskit.org/documentation/stable/0.37/tutorials/circuits/2_plotting_data_in_qiskit.html after the deprecated notebook is merged.

Update: see https://github.com/Qiskit/qiskit-tutorials/pull/1353#issuecomment-1681346271 for what Eric proposes doing instead.

**Comment by javabster** [comment]
I think we should revisit this decision, now that we have more Qiskit content on https://docs.quantum-computing.ibm.com/ I think those pages could benefit from a standalone visualisation page there, which we could probably reuse the qiskit visualization tutorial for. 

cc @abbycross

**Comment by abbycross** [comment]
Does the revamped content that appears in the [Visualization](https://docs.quantum.ibm.com/guides/visualize-circuits) section of the guides complete this issue?
