### ISSUE TITLE
Operator tutorials and opflow deprecation

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit#10666]
There are 2 tutorials in `operators` folder which relate to opflow content. One is about the opflow framework/function in general, the other is for gradients that are also part of opflow.

Opflow is soon to be deprecated - see Qiskit/qiskit-terra#9176 so these tutorials should be addressed. We can at a minimum edit them to link to the opflow migration guide upfront along with suitable comments about the deprecation and alternate function. And potentially point to alternate tutorials:

* For operators I do not think I have seen a quantum_info tutorial around the operators there.

* For the gradients Qiskit/qiskit-tutorials#1390 this would be the 'replacement' tutorial using the gradient primitives from algorithms.

**Comment by woodsp-ibm** [comment]
I see #10682 adds a comment about the operator/opflow tutorials - maybe that suffices to address this issue.

**Comment by Eric-Arellano** [comment]
We will also want a note at the top of the operator tutorials themselves about the deprecation. I am working right now on migrating qiskit-tutorials into Qiskit. Once that copy is merged, I plan to add the note and then we can close this issue.

**Comment by Eric-Arellano** [comment]
This was fixed back when we had qiskit.org
