### ISSUE TITLE
Use `BackendV2` for basic aer

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#10690]
### What should we add?

Right now the backends in `qiskit.providers.basicaer` are all built on the legacy `BackendV1` model. We should update it to be based on the more modern `BackendV2` instead. The target will be very simple for these backends, it's basically just:

```python
MAX_QUBITS_MEMORY = int(log2(local_hardware_info()["memory"] * (1024**3) / 16))
target = Target(num_qubits=min(24, MAX_QUBITS_MEMORY)
lam = Parameter("lambda")
target.add_instruction(U1Gate(lam))
phi = Parameter("phi")
target.add_instruction(U2Gate(phi, lam))
theta = Parameter("theta")
target.add_instruction(U3Gate(theta, phi, lam))
target.add_instruction(RZGate(phi))
target.add_instruction(SXGate())
target.add_instruction(XGate())
target.add_instruction(CXGate())
target.add_instruction(IGate())
target.add_instruction(UnitaryGate, name="unitary")
```

The trickier piece here is more about maintaining backwards compatibility for all the pieces that are part of the `BackendV1` interface and not in the `BackendV2` interface to give users a chance to migrate.

**Comment by burgholzer** [comment]
Might I point out https://github.com/Qiskit/qiskit/issues/10592 in that regard as it also popped up during an attempt to move our classical simulation backends from BackendV1 to BackendV2?

**Comment by MozammilQ** [comment]
@mtreinish , am I allowed to try this one?
