### ISSUE TITLE
`qiskit.passmanager` does not show up in docs!

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit#10691]
For example, search does not work for its members:

<img width="653" alt="Screenshot 2023-08-22 at 2 41 48 PM" src="https://github.com/Qiskit/qiskit/assets/14852634/d6e12ff2-fede-4e96-9569-38fee8a562f9">

Based on this code:

https://github.com/Qiskit/qiskit/blob/4a8c0ca38060ff6434c5fdbb42cdf0c741d4cd8a/docs/apidoc/index.rst?plain=1#L19-L22

We would expect `qiskit.passmanager` to show up here, but it's missing:

<img width="520" alt="Screenshot 2023-08-22 at 2 42 14 PM" src="https://github.com/Qiskit/qiskit/assets/14852634/ca9b78a0-ef2a-4ac0-bf82-2fd4bc6bd46d">

I'm not sure why this is. `passmanager.rst` looks like any other module RST file, and `passmanager/__init__.py` seems fine too.

**Comment by jakelishman** [comment]
Because this file is new for Terra 0.45 - it's not in a deployed documentation build yet.

**Comment by Eric-Arellano** [comment]
Oh...duh. Indeed https://qiskit.org/documentation/dev/apidoc/passmanager.html.

Thanks Jake

**Comment by jakelishman** [comment]
Huh, I forgot we were doing dev docs now - neat to see them working!
