### ISSUE TITLE
Programming on Quantum Computers — Coding with Qiskit S2E6

### ISSUE THREAD

**Issue by shreyasat27** [Qiskit/qiskit#10720]
I'm following the titled video! 

from qiskit.ml.datasets import ad_hoc_data 

I'm trying to run this but getting an error:  No module named 'qiskit.ml'

Then I followed some other person who said that we should try the updated version and thus I used, 

from qiskit_machine_learning.datasets import ad_hoc_data

but now still I'm getting an error 
ModuleNotFoundError: No module named 'qiskit_machine_learning'

I'm using Google Collab to run the code! Does anybody, have any idea?

```[tasklist]
### Tasks
```

**Comment by Raghav-Bell** [comment]
`qiskit-aqua` was depreceated in 2021 hence `qiskit.ml` isn't working, check [migration guide](https://github.com/qiskit-community/qiskit-aqua/blob/main/README.md#migration-guide). 
Required file is [here ](https://github.com/qiskit-community/qiskit-machine-learning/blob/main/qiskit_machine_learning/datasets/ad_hoc.py) in [qiskit-community/qiskit-machine-learning](https://github.com/qiskit-community/qiskit-machine-learning)

Edit:
In  short run the following code block on colab:
```
!pip install qiskit-machine-learning # installing qiskit_machine_learning module (edited after below comments)

from qiskit_machine_learning.datasets import ad_hoc_data # importing ad_hoc_data
```

**Comment by shreyasat27** [comment]
I tried it as well I'm getting this error 

ModuleNotFoundError: No module named 'qiskit_machine_learning'

> `qiskit-aqua` was depreceated in 2021 hence `qiskit.ml` isn't working, check [migration guide](https://github.com/qiskit-community/qiskit-aqua/blob/main/README.md#migration-guide). Required file is [here ](https://github.com/qiskit-community/qiskit-machine-learning/blob/main/qiskit_machine_learning/datasets/ad_hoc.py) in [qiskit-community/qiskit-machine-learning](https://github.com/qiskit-community/qiskit-machine-learning)
> 
> Edit: In short run the following code block on colab:
> 
> ```
> !pip install qiskit[machine-learning] # installing qiskit_machine_learning module
> 
> from qiskit_machine_learning.datasets import ad_hoc_data # importing ad_hoc_data
> ```

**Comment by woodsp-ibm** [comment]
The application packages were all removed as optional dependents from the qiskit metapackage so installing it via qiskit thus `pip install qiskit[machine-learning]` no longer works - instead install it directly using
```
pip install qiskit-machine-learning
```
https://github.com/qiskit-community/qiskit-machine-learning#installation

**Comment by shreyasat27** [comment]
after the installation process, I was getting some error related to QSVM and other issues which is now changed to qsvc and qsvr and other issues, this below link helped in case anyone needs it, 

https://qiskit.org/ecosystem/machine-learning/migration/01_migration_guide_0.5.html
