### ISSUE TITLE
Test raising "the property ``qiskit.circuit.bit.Bit.index`` is deprecated"

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10749]
The following tests are raising
```
DeprecationWarning: The property ``qiskit.circuit.bit.Bit.index`` is deprecated as of qiskit-terra 0.17. It will be removed no earlier than 3 months after the release date. Instead, use `QuantumCircuit.find_bit` to find all the containing registers within a circuit and the index of the bit within the circuit.
```

- [x] `test.python.visualization.timeline.test_generators.TestGates.test_gen_sched_gate_with_finite_duration` https://github.com/Qiskit/qiskit/pull/10750
- [x] `test.python.quantum_info.operators.symplectic.test_pauli.TestPauli.test_barrier_delay_sim` https://github.com/Qiskit/qiskit/pull/10757
- [x] `test.python.visualization.timeline.test_generators.TestTimeslot.test_gen_bit_name` https://github.com/Qiskit/qiskit/pull/10750
- [x] `test.python.visualization.timeline.test_layouts.TestBitArrange.test_qreg_creg_descending` https://github.com/Qiskit/qiskit/pull/10843
- [x] `test.python.visualization.test_circuit_latex.TestLatexSourceGenerator` https://github.com/Qiskit/qiskit/issues/9880

The deprecation was introduced on April 01, 2021. 

Related:
 * https://github.com/Qiskit/qiskit/issues/10744 
 * https://github.com/Qiskit/qiskit/pull/10733#discussion_r1311610141
 * https://github.com/Qiskit/qiskit/issues/9880

**Comment by jakelishman** [comment]
See also: #9880

**Comment by 1ucian0** [comment]
Tests are clean (at least wrt this specific warning)!
