### ISSUE TITLE
Remove code deprecated in 0.20 (released on March 31, 2022)

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10747]
There is code released 16 month ago that needs to be removed.
 - qiskit/visualization/circuit/latex.py:52 (`__init__`)
 - qiskit/visualization/circuit/latex.py:53 (`__init__`)
 - qiskit/visualization/circuit/latex.py:54 (`__init__`)
 - qiskit/visualization/circuit/latex.py:55 (`__init__`)
 - qiskit/transpiler/coupling.py:128 (`subgraph`)
 - qiskit/dagcircuit/dagcircuit.py:612 (`_copy_circuit_metadata`)
 - qiskit/synthesis/evolution/suzuki_trotter.py:54 (`__init__`)
  
This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

**Comment by Raghav-Bell** [comment]
@1ucian0 Please assign this issue to me.
