### ISSUE TITLE
Remove code deprecated in 0.19 (released on December 06, 2021)

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10746]
There is code released 20 month ago that needs to be removed.
 - `qiskit/transpiler/instruction_durations.py:173` (`get`)
 - `qiskit/providers/models/backendconfiguration.py:834` (`control`)
 - `qiskit/qobj/__init__.py:84` (`__init__`)
  
This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

**Comment by mtreinish** [comment]
The deprecations in `algorithms` we can just ignore since we'll be removing the entire module before too long.

**Comment by 1ucian0** [comment]
removing them from the list. Thanks!

**Comment by doublehoon** [comment]
@1ucian0 Hi, can I work on this issue?

**Comment by 1ucian0** [comment]
Assigned! Thanks!
