### ISSUE TITLE
Remove code deprecated in 0.18 (released on July 12, 2021)

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10745]
There is code released 25 month ago that needs to be removed.
 - qiskit/algorithms/phase_estimators/phase_estimation_result.py:70 (`most_likely_phase`)
 - qiskit/opflow/gradients/derivative_base.py:138 (`parameter_expression_grad`)
  
This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

**Comment by jakelishman** [comment]
tbf we can probably just close this issue because we'll be removing algorithms and opflow entirely from `main` in a couple of months
