### ISSUE TITLE
Remove code deprecated in 0.16 (released on October 15, 2020)

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10743]
There is code released 33 month ago that needs to be removed.
 - qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py:228 (`num_ancilla_qubits`)
 
This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

**Comment by danielleodigie** [comment]
hi, could I be assigned to this?

**Comment by 1ucian0** [comment]
Sure! Assigned. Thanks!
