### ISSUE TITLE
Remove code deprecated in 0.21 (released on June 30, 2022)

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10748]
There is code released 13 month ago that needs to be removed.
 - qiskit/execute_function.py:39 (`execute`)
 - qiskit/execute_function.py:40 (`execute`)
 - qiskit/transpiler/passes/scheduling/alap.py:30 (`__init__`)
 - qiskit/transpiler/passes/scheduling/asap.py:36 (`__init__`)
 - qiskit/transpiler/passes/scheduling/dynamical_decoupling.py:93 (`__init__`)
 - qiskit/transpiler/passes/scheduling/alignments/align_measures.py:93 (`__init__`)
 - qiskit/transpiler/passes/utils/cx_direction.py:22 (`__init__`)
 - qiskit/transpiler/passes/utils/check_cx_direction.py:22 (`__init__`)
 - ~qiskit/algorithms/optimizers/spsa.py:652 (`optimize`)~ Not needed, as `qiskit.algorithms` has its own process.
 - qiskit/pulse/transforms/alignments.py:48 (`to_dict`)
 - qiskit/pulse/transforms/alignments.py:333 (`to_dict`)
 - qiskit/pulse/transforms/alignments.py:419 (`to_dict`)
 - qiskit/qpy/interface.py:75 (`dump`)
  
This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

**Comment by Raghav-Bell** [comment]
Please assign this issue to me.

**Comment by 1ucian0** [comment]
done @Raghav-Bell  . Thanks!
