### ISSUE TITLE
Remove code deprecated in 0.15 (released on August 06, 2020)

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10742]
There is code released 36 month old that needs to be removed. 
 - qiskit/visualization/state_visualization.py:39 (`plot_state_hinton`)
 - qiskit/visualization/state_visualization.py:257 (`plot_bloch_multivector`)
 - qiskit/visualization/state_visualization.py:365 (`plot_state_city`)
 - qiskit/visualization/state_visualization.py:625 (`plot_state_paulivec`)
 - qiskit/visualization/state_visualization.py:799 (`plot_state_qsphere`)
 - qiskit/scheduler/utils.py:18 (`utils.format_meas_map`)
 - qiskit/scheduler/utils.py:23 (`macros.measure`)
 - qiskit/scheduler/utils.py:27 (`macros.measure_all`)

This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

**Comment by ThirDecade2020** [comment]
Hello @1ucian0 thanks for posting some updated 'good first issues'. This seems like an issue that I might be able to tackle. Can you assign me here?

**Comment by 1ucian0** [comment]
done. Thanks! I would recommend you to do it in two PRs: one for visualization, one for the scheduler.

**Comment by ThirDecade2020** [comment]
Noted, thanks!

**Comment by ThirDecade2020** [comment]
@1ucian0 @unit0113 I'm a little confused. I was assigned this 2 days ago, but it looks like a pull request was already made? Should I wait for that one to be resolved or continue to work on this as normal? Thanks. - Jason

**Comment by ThirDecade2020** [comment]
@1ucian0 Should I still work on this issue?

**Comment by 1ucian0** [comment]
I think we can push @unit0113's PR over the final line soon. Do you mind selecting another `good first issue`?
