### ISSUE TITLE
The release 0.25.1 doesn't fetch any more. Did it change?

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit#10766]
### Environment

- **Qiskit Terra version**: 0.25.1
- **Python version**: 3.9
- **Operating system**: FreeBSD 13.2

The FreeBSD port science/py-qiskit-terra was updated to 0.25.1 on Aug 18th, but now the fetch fails:
```
fetch: https://codeload.github.com/Qiskit/qiskit-terra/tar.gz/0.25.1?dummy=/Qiskit-qiskit-terra-0.25.1_GH0.tar.gz: size unknown
fetch: https://codeload.github.com/Qiskit/qiskit-terra/tar.gz/0.25.1?dummy=/Qiskit-qiskit-terra-0.25.1_GH0.tar.gz: size of remote file is not known
Qiskit-qiskit-terra-0.25.1_GH0.tar.gz                   11 MB 9267 kBps    01s
=> Fetched file size mismatch (expected 12138707, actual 12138283)
```

Was the release re-made, or was your GitHub account hacked and the new tarball is malicious?

### What is happening?

The release was re-rolled.

### How can we reproduce the issue?

n/a

### What should happen?

Releases should not be re-rolled.

### Any suggestions?

Releases should not be re-rolled.

**Comment by Raghav-Bell** [comment]
This issue #10755  may be helpful, please give a read.

**Comment by jakelishman** [comment]
Those tarballs are just automatically generated by GitHub on a tag event.  We haven't rerun any release, but you're not downloading an artifact that we generate and so we don't have complete control on it.  Judging by the file size change, I'm guessing that GitHub has modified that tarball due to the repository renaming also discussed in #10755.

**Comment by 1ucian0** [comment]
Maybe it is a modification in the tarball root directory? now is called `qiskit-0.25.1`, maybe it was called `qiskit-terra-0.25.1`? Let us know if this answers the questions so we can close this issue

**Comment by 1ucian0** [comment]
Hi @yurivict, hopefully this issue covered all your questions. Feel free to comment forwards if this issues is not resolved yet.
