### ISSUE TITLE
Make error_message part of Job abstract interface

### ISSUE THREAD

**Issue by hay-k** [Qiskit/qiskit#10799]
### What should we add?

Currently, the `JobV1` abstract interface does not define a method called `error_message`, however some Qiskit functionality (e.g. [here](https://github.com/Qiskit-Extensions/qiskit-experiments/blob/4f08d6facc8f4eb5361bc05296d5e6e0b03e0a35/qiskit_experiments/framework/experiment_data.py) in `qiskit_experiments`) assumes that job objects have such a method. I think, it would be nice if the Job interface explicitly defined this as abstract method.

**Comment by jakelishman** [comment]
Sorry this never got a reply at the time.

We can't add new methods to an existing interface; it risks breaking existing implementations by shadowing a method they have, potentially with different semantics.  Experiments was wrong to rely on that method _always_ being present; if it's still doing it in a situation where the `Job` might not be a custom subclass that extends the interface with that method, it'd be a bug there.

I'll close this as "can't fix" for now - we can't add things to a subclass-safe interface - but if there's ever a new `Job` interface, it'd be a candidate for discussion then.
