### ISSUE TITLE
Serialization fails for controlled unitary gate

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit#10802]
**Describe the bug**
I get the error: `AttributeError: 'NoneType' object has no attribute 'clbits` and it seems that the `Qpy to QASM conversion failed: unable to parse quantum circuit` for a circuit containing a controlled unitary gate.

**Steps to reproduce**
```
from qiskit.extensions import UnitaryGate
from qiskit.quantum_info import random_unitary, SparsePauliOp
from qiskit import QuantumCircuit, QuantumRegister
from qiskit_ibm_runtime import QiskitRuntimeService, Options, Estimator, Session

UU = random_unitary(4, seed=12345)
qr = QuantumRegister(3)
qc = QuantumCircuit(qr)
qc.h(0)
qc.append(UnitaryGate(UU).control(1), qr)

service = QiskitRuntimeService()
backend = service.get_backend('ibmq_qasm_simulator')

options = Options(optimization_level=2, resilience_level=0)
estimator = Estimator(backend=backend, options=options)

XXexp = estimator.run(qc, observables=SparsePauliOp('IIX')).result().values[0]
```

**Expected behavior**
It should work

**Suggested solutions**

**Additional Information**

Transpiling before works
`transpile(qc, basis_gates = backend.configuration().basis_gates)`

- **qiskit-ibm-runtime version**: 0.12.0
- **Python version**: 3.8.16
- **Operating system**: MacOs

**Comment by kt474** [comment]
@jakelishman is this a bug with qpy? If so, can it be transferred to qiskit (terra)

**Comment by jakelishman** [comment]
Yep, looks like it to me. I've no write access on this to transfer, but @mtreinish could.

**Comment by ElePT** [comment]
@AzizNgoueya As a quick patch until the bug is found/fixed, you can try transpiling the circuit locally before sending it to the estimator:

```
from qiskit import transpile
qc = transpile(qc, basis_gates=['sx', 'x', 'rz', 'cx'])
```

**Comment by ElePT** [comment]
I can take a look at this bug :)
