### ISSUE TITLE
Deprecate qiskit/transpiler/graysynth.py

### ISSUE THREAD

**Issue by ShellyGarion** [Qiskit/qiskit#10819]
### What should we add?

Continue the work in https://github.com/Qiskit/qiskit/pull/9795 and deprecate[ `qiskit/transpiler/graysynth.py`](https://github.com/Qiskit/qiskit/blob/main/qiskit/transpiler/synthesis/graysynth.py).
The code now exists in the [synthesis library](https://qiskit.org/documentation/apidoc/synthesis.html):

- `cnot_synth` is replaced by `synth_cnot_count_full_pmh`
- `graysynth` is replaced by `synth_cnot_phase_aam`

One should follow [Qiskit deprecation policy guidelines](https://qiskit.org/documentation/deprecation_policy.html).

**Comment by AmirAflak** [comment]
would like to take this :)

**Comment by ShellyGarion** [comment]
Thanks @AmirAflak - I assigned you to this issue.

**Comment by ShellyGarion** [comment]
@AmirAflak - is there any progress with this issue? Thanks!

**Comment by border-b** [comment]
Hi @ShellyGarion, if this is still open I would like to work on this!

**Comment by ShellyGarion** [comment]
@border-b - thanks, I assigned you to this issue

**Comment by ShellyGarion** [comment]
@AmirAflak and @border-b - I'm unassigning you from this issue, as it seems that #11079 already covers this.

**Comment by rishabhRsinghvi** [comment]
@ShellyGarion so is it solved, then please close it.

**Comment by ShellyGarion** [comment]
> @ShellyGarion so is it solved, then please close it.

This issue could be closed only after PR #11079 will be merged, and that PR still needs more work.
