### ISSUE TITLE
Remove code deprecated in 0.22 (released on October 13, 2022) [quantum_info]

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10811]
There is code released 9 month ago that needs to be removed.
 - `qiskit/quantum_info/operators/symplectic/pauli_utils.py:21`
 - `qiskit/quantum_info/operators/symplectic/random.py:116`
  
This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

Related:
* https://github.com/Qiskit/qiskit/issues/10812
* https://github.com/Qiskit/qiskit/issues/10813
* https://github.com/Qiskit/qiskit/issues/10810

**Comment by doublehoon** [comment]
Hi, can I work on this issue?

**Comment by 1ucian0** [comment]
assigned! Thanks!
