### ISSUE TITLE
Remove code deprecated in 0.22 (released on October 13, 2022) [transpiler and providers]

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10813]
There is code released 9 month ago that needs to be removed.
 - `qiskit/transpiler/passes/calibration/rzx_builder.py:68`
 - `qiskit/providers/basicaer/qasm_simulator.py:375`
  
This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

Related:
* https://github.com/Qiskit/qiskit/issues/10812
* https://github.com/Qiskit/qiskit/issues/10811
* https://github.com/Qiskit/qiskit/issues/10810

**Comment by santhosh-gnse** [comment]
Hello @1ucian0 !

Can you please assign this issue to me !

**Comment by 1ucian0** [comment]
Done! Thanks

**Comment by rupeshknn** [comment]
As the PR is merged, shouldn't this issue be closed?

**Comment by 1ucian0** [comment]
yes! all the issues on this epic are closed and, therefore, it can be closed. Thanks!
