### ISSUE TITLE
support `Pauli.delete([])`

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit#10839]
### Environment

- **Qiskit Terra version**: 0.25.1

### What is happening?

`Pauli` and `PauliList` have a method `delete` to delete elements (qubits from a Pauli; Paulis or qubits from a PauliList).

This method accepts a list specifying the indices to delete. However, it raises an error when the list is empty. It would be helpful for programmatic use of `delete` if an empty-list (empty iterable) would instead delete nothing, i.e. return a copy of the original Pauli/PauliList object. This would also be in line with the behavior of `np.delete()`, which is expected here since Paulis are built on, and nominally act like, numpy arrays.

### How can we reproduce the issue?

```
import qiskit.quantum_info as qi
```
Case 1:
```
p = qi.Pauli('XYZ')
p.delete([])
```
Case 2:
```
pl = qi.PauliList(['XYZ','ZIX'])
pl.delete([])
```
Case 3:
```
pl = qi.PauliList(['XYZ','ZIX'])
pl.delete([], qubit=True)
```

### What should happen?

Do not raise an error. Return a copy of the original object.

**Comment by jakelishman** [comment]
This seems sensible to me - I think there's quite a lot of places within `quantum_info` that don't quite have correct handling for the empty list, and I'm generally in favour of giving them the expected behaviour.

**Comment by AlexanderGroeger** [comment]
This seems like a rather easy thing to fix. If there's no rush, I can look into it next week.

**Comment by jakelishman** [comment]
Sounds good to me, thanks!
