### ISSUE TITLE
extend BasicSimulator with standard gates

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10852]
As part of the discussion in https://github.com/Qiskit/qiskit/pull/10673, we resolved that every standard gate with a fixed amount of qubits can be in BasicSimulator.

**Comment by ghost** [comment]
I am interested in taking up this issue. I am new to open source contribution but excited to learn! Will start looking through previous details in [#10673](https://github.com/Qiskit/qiskit/pull/10673).

**Comment by jakelishman** [comment]
I've updated this post to refer to `BasicSimulator`, following the removal of `BasicAer` in 1.0.
