### ISSUE TITLE
Expand test coverage on release jobs

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#10870]
### What should we add?

Right now when we publish a release for qiskit to test our pre-compiled binaries we only run: https://github.com/Qiskit/qiskit/blob/main/examples/python/stochastic_swap.py which runs `StochasticSwap`. This is a historical artifact because in the past the only compiled extension module in qiskit was the internals of the `StochasticSwap` pass. However, in the current form of qiskit we have a lot of compiled extension modules that are used more broadly throughout qiskit. To ensure we're building valid binaries we should expand the test coverage during the CI job to make sure the wheels are functional before we publish them. The simplest option is to just run the entire test suite, but the only thing we need to be wary of is runtime if we go this route. This is basically what I attempted in #8603 (which went stale and I never finished). Since we have a hard 1 hour job limit the more realistic scenario is we add a limited subset of smoke tests from the test suite which will thoroughly exercise all the rust code in qiskit and we run that for the test phase in cibuildwheel.

**Comment by jakelishman** [comment]
We started doing this for Tier 1 as part of release PGO in #11502, and set it to be the complete validation in #13205.  I'll close this as complete, unless I've missed something.
