### ISSUE TITLE
Quantum imaginary time evolution (QITE) feature

### ISSUE THREAD

**Issue by wyqian1027** [Qiskit/qiskit#10884]
### What should we add?

I am wondering if QITE is implemented in some way already in Qiskit so that we can use it. As far as I can tell, the ImaginaryTimeEvolver class is currently NotImplemented. It would be nice to include it in Qiskit as QITE is now a major research of interest.

**Comment by jakelishman** [comment]
`ImaginaryTimeEvolver` is an abstract base class that defines an interface.  `VarQITE` and `SciPyImaginaryEvolver` are both concrete realisations of that interface.

For what it's worth, further questions about `qiskit.algorithms` should likely be directed to https://github.com/qiskit-community/qiskit-algorithms/, which is where the algorithms components of Qiskit are relocating to.

**Comment by wyqian1027** [comment]
Thanks very much for the reply. I will close the thread now.
