### ISSUE TITLE
Singeltonize `Measure`, `Reset`, and `Barrier`

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#10953]
### What should we add?

In https://github.com/Qiskit/qiskit/pull/10314#issuecomment-1744466964 it was pointed out after #10314 merged that we can make some of the circuit instructions singletons pretty easily just as we did for parameterless gates. The `Measure`, `Reset` instruction are super straightforward to convert to singletons because they are single qubit/clbit constructs and do not take any parameters. `Barrier` also conceptually can be a "singleton" with a globally shared instance for barriers  but as its variable width we'd need to store a distinct instance for each value of number of qubits that `Barrier` is instantiated with, which will require some custom handling as none of the singleton fixtures support this yet.

**Comment by santhosh-gnse** [comment]
Hii @mtreinish!

If this issue still unassigned, can I take up this issue

**Comment by mtreinish** [comment]
@Matrixmang0 sure if you have the bandwidth for this feel free to give it a try. I'd recommend trying to use `Measure` or `Reset` to start (as the `Barrier` will be a little trickier)

**Comment by santhosh-gnse** [comment]
I'll certainly do my best. As I'm still getting acquainted with the repository, I'm uncertain about my bandwidth to tackle this issue. However, with your guidance, support from this incredible community, I'm hopeful that I can navigate through and resolve the issue :)

**Comment by jakelishman** [comment]
Update on this: #11170 made `Measure` and `Reset` singletons, so that part of the issue is solved.  `Barrier` is rather more non-trivial (and arguably will provide little benefit) because it would need greater modifications to the singleton machinery, which is tricky.  We already have a prototype of this internally, made for other reasons, but it may not be worth the cost of adding it - the potential savings from barriers are not expected to be large.

**Comment by mtreinish** [comment]
Given the last comment here I'm going to close this as complete because I think `Barrier` isn't worth singletonizing as there typically are only a few barriers in a circuit and dealing with the variable width is more effort than the benefits it would provide.
