### ISSUE TITLE
sometimes visual testing fail with `no such file or directory`

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10968]
Take the example of https://github.com/Qiskit/qiskit/pull/10907/checks?check_run_id=17192520206:

![screencapture-github-Qiskit-qiskit-pull-10907-checks-2023-10-04-14_24_38](https://github.com/Qiskit/qiskit/assets/766693/ab715695-b254-4317-a674-3ae3f0d969c1)

"Sometimes" (maybe there is a pattern, I just dont know which one) this happens. No idea why.

**Comment by jakelishman** [comment]
The pattern is that if the visual tests don't run (such as if the initial test suite fails), they never create the directories, and all the handling of them afterwards is what causes the cascade of errors.

**Comment by AngeloDanducci** [comment]
I'll take a look at this, agreed with Jake's analysis.

Should be set up to only archive visual test files after the visual tests run but clearly that's not currently the case.
