### ISSUE TITLE
@NahidaNahida , your fix is probably the right one. Since you solved it, would you like to make a pull request (PR) to fix this bug? If you don't want to do it, no problem, we can do it pretty quickly.

### ISSUE THREAD

**Issue by NahidaNahida** [Qiskit/qiskit#10985]
@NahidaNahida , your fix is probably the right one. Since you solved it, would you like to make a pull request (PR) to fix this bug? If you don't want to do it, no problem, we can do it pretty quickly.

_Originally posted by @jlapeyre in https://github.com/Qiskit/qiskit/issues/10980#issuecomment-1749769249_

Thanks for your agreement and advice. I have already proposed a pull request for this bug at (https://github.com/Qiskit/qiskit/pull/10983).

**Comment by mtreinish** [comment]
It looks like this issue was opened by accident, the contents look like a reply on #10980. I'm going to close this accordingly, but please feel free to reopen this if I'm missing something or there is more to discuss here.
