### ISSUE TITLE
Update Qiskit Homepage Banners for Sunset

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/qiskit#11007]
The current banners for the Qiskit Homepage must be updated to the new wording as we get closer to sunset. The updated banners can be found [here](https://www.figma.com/file/0Je6YtTaizU1Y7lCubTenn/Qiskit.org-page-updates?type=design&node-id=442%3A5700&mode=design&t=XESKKfgkCymUNoBe-1) 
<img width="754" alt="updated qiskit banner" src="https://github.com/Qiskit/qiskit_sphinx_theme/assets/89415444/2cf76300-108f-4768-abcb-afa0cf04f47d">

**Comment by yusharth** [comment]
Can I help you @javabster?

**Comment by javabster** [comment]
hi @yusharth sorry there is already a PR open for this, I just forgot to link it to the issue :)
