### ISSUE TITLE
how to run for loop in qiskit with Openqasm 3

### ISSUE THREAD

**Issue by eeeeeeeason** [Qiskit/qiskit#11034]
### Environment

- **Qiskit Terra version**: 
  - qiskit-terra                      0.25.1
- **Python version**: 
  - Python 3.10.8
- **Operating system**: 
  - ibm-quantum-computing-lab

### What is happening?

I am going to introduce the new progress of qasm3 to my colleagues, and I would like to thank the community for their contribution. but i find for loop can not use as paper said [ https://arxiv.org/pdf/2104.14722.pdf ]

I've read about the support of qasm3, but I don't quite understand what it says about for loops. " Discrete sets and negative stepping is not supported.  "  [ https://docs.quantum-computing.ibm.com/build/qasm-feature-table ] 

error after run code in quantum computing lab : line 6:8 no viable alternative at input 'j'

```
import qiskit.qasm3
 
program = """
    OPENQASM 3.0;
    include "stdgates.inc";
    qubit[3] q;
    
    for j in [0:2] {
        h q[j];
    }

"""
circuit = qiskit.qasm3.loads(program)
circuit.draw("mpl")
```

### How can we reproduce the issue?

run this code in quantum computing lab
```
import qiskit.qasm3
 
program = """
    OPENQASM 3.0;
    include "stdgates.inc";
    qubit[3] q;
    
    for j in [0:2] {
        h q[j];
    }

"""
circuit = qiskit.qasm3.loads(program)
circuit.draw("mpl")
```

### What should happen?

more detail about how to use for loop ?. thanks a lot

**Comment by jakelishman** [comment]
Those loops are not valid `for` loops because they don't include a type for the loop variable.  Please [read the OpenQASM 3 documentation](https://openqasm.com/language/classical.html#for-loops), which is not a part of Qiskit.

After that, you would need a simulator or hardware that supports `for` loops.  I'm not certain that there are any that are public at the moment, although `if` conditionals and `while` loops are better supported.

**Comment by eeeeeeeason** [comment]
> Those loops are not valid `for` loops because they don't include a type for the loop variable. Please [read the OpenQASM 3 documentation](https://openqasm.com/language/classical.html#for-loops), which is not a part of Qiskit.
> 
> After that, you would need a simulator or hardware that supports `for` loops. I'm not certain that there are any that are public at the moment, although `if` conditionals and `while` loops are better supported.

I am looking forward to the availability of the for loop feature in the qasm3 module of Qiskit as soon as possible, because I want to write Quantum Fourier Transform directly within it.
