### ISSUE TITLE
Add drawer support for `Operations` that are not subclasses of `Instruction`

### ISSUE THREAD

**Issue by alexanderivrii** [Qiskit/qiskit#11087]
### What should we add?

We need to support drawing circuits with any operation that is not an `Instruction`, and in particular with `Clifford`s and `AnnotatedOperation`s. We also need to add tests.

**Comment by enavarro51** [comment]
@alexanderivrii This circuit
```
from qiskit import QuantumCircuit
from qiskit.quantum_info import Clifford, random_clifford
from qiskit.circuit.annotated_operation import AnnotatedOperation, InverseModifier, ControlModifier
from qiskit.circuit.library import SGate

qc = QuantumCircuit(3)
cliff = random_clifford(2)
qc.append(cliff, [0, 1])
qc.ccx(0, 1, 2)
op1 = AnnotatedOperation(SGate(), [InverseModifier(), ControlModifier(2)])
qc.append(op1, [0, 1, 2])
qc.draw('mpl')
```
produces
![image](https://github.com/Qiskit/qiskit/assets/16268251/4f9bf56c-05a0-4ce7-b0da-32440b11fe1a)
What additional info do you want to be displayed? Also I just noticed there's a bug in the 'text' drawer that crashes on this circuit. :-(
