### ISSUE TITLE
Refactor VF2 scoring rust interface

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#11134]
The implementation makes me wonder if in the future we should have some sort of `VF2Scorer` class that builds these and holds them as instance data among any other data that is reused between scorings. The reason being to encapsulate the internals of scoring without forcing client code to be aware of them (i.e. rather than threading a bunch of parameters around, we might call a `VF2Scorer::score` method and pass just the layout).

_Originally posted by @kevinhartman in https://github.com/Qiskit/qiskit/pull/11115#pullrequestreview-1702040931_

**Comment by MozammilQ** [comment]
@mtreinish , am I allowed to try this issue?

**Comment by mtreinish** [comment]
Oh sorry I missed your comment here back in December. I'm actually going to close this issue as it's superseded by #12276 and #12277 since we'll move all the patch logic to rust. But that's also currently blocked.
