### ISSUE TITLE
IBM AfroHacks at AfroTech Participation

### ISSUE THREAD

**Issue by jritten** [Qiskit/qiskit#11137]
### What should we add?

IBM AfroHacks at AfroTech Hackathon starts on Monday, and the Quiskit project repo(s) are not properly labeled to indicate to participants wanting to contribute to Qiskit during the 2-day hackathon which projects/issues to work on. 

Add “afrohacks” to Settings  => Topics on any Qiskit repos, and add "afrohacks" to issue Labels, to indicate the repos/repo issues Qiskit would like to have participants work on during the 48-hour AfroHacks at AfroTech Hackathon starting on Monday. Please feel free to connect with me with any questions. Thank you!

**Comment by jritten** [comment]
https://ibm.biz/afrohacks-hackathon

**Comment by 1ucian0** [comment]
Hi Jenna, Qiskit always welcomes new contributors. Qiskit and qiskit-related projects already have a specific label for new comers, called `good first issues`. Here, the full list: https://qisk.it/good-first-issues (I'm going to update it to be ready for the event). 

Please, make sure that the participant are familiar with the [contributor guidelines](https://qisk.it/contribute) and consider that the project does not guarantee a response or a merge before the event finishes.

Happy hacking, 1ucian0
