### ISSUE TITLE
Remove deprecated code since 0.23 in qiskit/visualization/state_visualization.py

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#11143]
There is code in `qiskit/visualization/state_visualization.py` deprecated in 0.23 that needs to be removed:

 - `qiskit/visualization/state_visualization.py:1283` (`num_to_latex_ket`)
 -  `qiskit/visualization/state_visualization.py:1302` (`numbers_to_latex_terms`)

This includes:
 * Remove deprecated code and tests (if they only check the deprecation raise)
 * tag the PR as [Changelog: Removal](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
 * create a release note in the category upgrade:. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

**Comment by border-b** [comment]
Hi @1ucian0, can you please assign this to me?

**Comment by 1ucian0** [comment]
done, thanks!
