### ISSUE TITLE
Deprecate legacy pulse builder command.

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit#11152]
### What should we add?

Pulse builder still supports following commands that inject circuit gate operation into the pulse context: 
- `qiskit.pulse.builder.call_gate`
- `qiskit.pulse.builder.cx`
- `qiskit.pulse.builder.u1`
- `qiskit.pulse.builder.u2`
- `qiskit.pulse.builder.u3`
- `qiskit.pulse.builder.x`

These are legacy workflow which we implemented before the pulse gate feature. These command introduce weird cyclic dependency between circuit and pulse program, and must be deprecated before the next release. 

In addition, following commands are nice to be deprecated as well.

- `qiskit.pulse.builder.active_transpiler_settings`
- `qiskit.pulse.builder.active_circuit_scheduler_settings`
- `qiskit.pulse.builder.transpiler_settings`

### Background
Note that the standard program representation in Qiskit is now `QuantumCircuit`, and pulse programs exist as a microcode (calibration) of the circuit. The pulse builder is a tool to define such microprograms, and circuit -> pulse conversion must be explicitly done with the circuit scheduler. Injecting circuit instruction in pulse program is indeed an opposite workflow.

**Comment by MozammilQ** [comment]
@nkanazawa1989 , should I go ahead with this? If I am allowed to?

**Comment by nkanazawa1989** [comment]
Thanks! I just assigned this to you.

**Comment by itoko** [comment]
Note: An alternative of `pulse.x(q)` will be `pulse.call(backend.target["x"][(q, )].calibration)`.

**Comment by MozammilQ** [comment]
A PR for this seems to be very straight forward, just deprecated these functions, modify tests and add a release note, that's it!
But, for three days I am banging my head over how this is a type: feature request ?
I tried seeing into other issues/comments by Naoki but didn't get any hint.
Anyways, I am opening this PR #11191 with whatever I know, if I left something please guide me :) 
@itoko , @nkanazawa1989

**Comment by MozammilQ** [comment]
@nkanazawa1989 , I think this should be closed isn't it?

**Comment by nkanazawa1989** [comment]
Right, thanks for the reminder!
