### ISSUE TITLE
broken formatting in deprecation policy page

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#11168]
In https://qiskit.org/documentation/deprecation_policy.html, the code block seems broken:

![Screenshot 2023-11-01 at 16 04 45](https://github.com/Qiskit/qiskit/assets/766693/f1e70b36-38e6-4442-985a-336ce962fe42)

**Comment by shindodkar** [comment]
would you like to give  some suggestion/hint on this issue

**Comment by jakelishman** [comment]
The aim of the issue is to fix the file `docs/deprecation_policy.rst` so the pictured code block appears properly.  It looks likely to me that there might be a `::` at the end of the previous paragraph instead of a `:`, but I haven't looked in detail.

**Comment by AngeloDanducci** [comment]
Closing as fixed per #11186
