### ISSUE TITLE
UnitaryOverlap cannot handle barriers

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit/qiskit#11177]
### Environment

- **Qiskit Terra version**: 0.45.0rc1
- **Python version**: 3.10
- **Operating system**: macOS

### What is happening?

UnitaryOverlap circuit breaks when input circuits contain barriers

### How can we reproduce the issue?

```
from qiskit.circuit import QuantumCircuit
from qiskit.circuit.library import UnitaryOverlap

qc1 = QuantumCircuit(2)
qc1.ry(np.pi/2, qc1.qubits)
qc1.cx(0, 1)
qc1.barrier()
qc1.rz(np.pi/2, qc1.qubits)

# Create the overlap circuit
overlap = UnitaryOverlap(qc1, qc1)
```

results in:
```CircuitError: 'One or more instructions cannot be converted to a gate. "barrier" is not a gate instruction```

### What should happen?

UnitaryOverlap should be able to handle circuits with barriers as if they weren't there.

**Comment by jakelishman** [comment]
Yeah ok, this one is probably on me for letting it through review: https://github.com/Qiskit/qiskit/pull/10734#pullrequestreview-1687299774.
