### ISSUE TITLE
avoid typechecking coefficients individually in SparsePauliOp.init()

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit#11187]
### What should we add?

I'm not certain but for large SparsePauliOp objects, it seems like the type-checking is a bottleneck for initializing the object (which also happens inside various SPO methods such as `compose()`):
https://github.com/Qiskit/qiskit/blob/02cb814e7669b8035924399b935b003032e1f7b3/qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py#L134-L142

In the most common case, we can avoid calling `isinstance` thousands of times by changing the logic to:
```
        if isinstance(coeffs, np.ndarray):
            if coeffs.dtype == object:
                dtype = object
            else:
                dtype = complex
        elif coeffs is not None:
            if not isinstance(coeffs, (np.ndarray, Sequence)):
                coeffs = [coeffs]
            if any(isinstance(coeff, ParameterExpression) for coeff in coeffs):
                dtype = object
            else:
                dtype = complex
```

Very crude timing test (seconds indicated at lower left); may want to confirm benchmark before committing. I repeated with `seed=2` (not shown).
<img width="549" alt="image" src="https://github.com/Qiskit/qiskit/assets/60495383/8a42da69-53b8-4371-8b39-9e9e71b100fc">

**Comment by jakelishman** [comment]
Coincidentally, I'd also spotted this recently and there's fix in #11133.
