### ISSUE TITLE
Rename `qiskit-terra` into `qiskit` and remove the metapackage

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#11240]
For the last months, the Qiskit project is transition to "terra-only", sometime called `qiskit == qiskit-terra`.

In previous years, `qiskit` was a collection of packages and, as such, the _metapackage_ structure was appropriate. However, now it only represents a package, qiskit-terra. A metapackage with a single dependency is unnatural and even error prune sometimes.

So, let's remove the metapackage and make `pip install qiskit` install the current `qiskit-terra`. This is probably the final blow for the _terra_ concept.

**Comment by mtreinish** [comment]
This has been completed since: https://github.com/Qiskit/qiskit/pull/11271 merged
