### ISSUE TITLE
Support for the Reset instruction for remote simulators

### ISSUE THREAD

**Issue by antalszava** [Qiskit/qiskit#11270]
### What should we add?

The remote simulators ibmq_qasm_simulator and simulator_statevector on IBM quantum experience raise the following error:

```
qiskit.exceptions.QiskitError: "Cannot unroll the circuit to the given basis, dict_keys(['diagonal', 'multiplexer', 'rxx', 'mcx', 'mcu1', 'mcry', 'u3', 'rz', 'z', 'mcrz', 'u2', 'mcrx', 'mcr', 'u1', 'mcswap', 'p', 'mcu3', 'ccx', 'kraus', 'y', 'mcz', 'delay', 'cx', 'measure', 'cu2', 'sdg', 'initialize', 'x', 'cu3', 'unitary', 't', 'cp', 'mcsx', 'mcp', 'cz', 'rx', 'cy', 'csx', 'u', 'rzx', 'mcu2', 'sx', 'rzz', 'ry', 'r', 'ryy', 'cu1', 'cswap', 'mcy', 'swap', 'roerror', 'id', 'h', 's', 'tdg']). Instruction reset not found in equivalence library and no rule found to expand."
```

It would be great to be able to perform a reset operation on simulators too.

**Comment by 1ucian0** [comment]
With the [retirement of remote simulators](https://docs.quantum.ibm.com/announcements/product-updates/2024-03-22-announcement-cloud-simulators-and-lab), this issue does not apply anymore. Therefore, closing as not-planned.
