### ISSUE TITLE
Add missing APIs to be generated in our docs

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit#11290]
See https://github.com/Qiskit/documentation/issues/238 for more context and instructions.

- [ ] qiskit.quantum_info.BaseOperator
- [ ] qiskit.opflow.X
- [ ] qiskit.opflow.Y
- [ ] qiskit.opflow.Z
- [ ] qiskit.opflow.I
- [ ] qiskit.opflow.CX
- [ ] qiskit.opflow.S
- [ ] qiskit.opflow.H
- [ ] qiskit.opflow.T
- [ ] qiskit.opflow.CZ
- [ ] qiskit.opflow.Swap
- [ ] qiskit.opflow.Zero
- [ ] qiskit.opflow.One
- [ ] qiskit.opflow.Plus
- [ ] qiskit.opflow.Minus
- [ ] qiskit.algorithms.VarQTE
- [ ] qiskit.quantum_info.states.quantum_state.QuantumState

**Comment by jakelishman** [comment]
Almost all of these are being removed from Qiskit 1.0 - the only two that are remaining are the two base classes from `qiskit.quantum_info`, which maybe should be documented, but they're funny. They're not really meant to be _user_ subclassable, they're kind of just implementation details of `qiskit.quantum_info`.

**Comment by Eric-Arellano** [comment]
Ah okay, let's close this then. Thanks for the context! 

We reference them in the migration guides, which is where we noticed them. But this is fine with me to not document them.
