### ISSUE TITLE
have a "lockfile" when a major reaches end-of-life

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#11349]
### What should we add?

When a Qiskit major version reaches end-of-life (mid 2024 in the case of 0.*) it would be great to have a way to keep it installable with working dependencies.

**Comment by jakelishman** [comment]
For reference: this issue isn't so much targetted at 0.46.0 as the EOL of the 0.x series in general, which is why it's not being acted on for 0.46.0.

**Comment by mtreinish** [comment]
I'm just going to keep kicking this one between the 0.46.x milestones until we approach the final patch release (so we don't lose track of it).

**Comment by jakelishman** [comment]
Oh yeah, I was about to make a `0.last` or something similarly stupidly named, but just kicking it between milestones is probably the most likely for us to keep it in mind.

**Comment by eliarbel** [comment]
This is done now with #13112
