### ISSUE TITLE
Completeness relation of kraus operators not satisfied in Fake backends 

### ISSUE THREAD

**Issue by simonecantori** [Qiskit/qiskit#11391]
With the following code 

```
from qiskit.providers.fake_provider import FakeGuadalupe
from qiskit.providers.aer.noise import NoiseModel
import numpy as np

backend = FakeGuadalupe()
nm = NoiseModel.from_backend(backend)

print(nm._local_quantum_errors['cx'][(0,1)].circuits[0])
print(len(nm._local_quantum_errors['cx'][(0,1)].circuits[0][1][0].params))

k11=np.transpose(nm._local_quantum_errors['cx'][(0,1)].circuits[0][1][0].params[0].conj())*nm._local_quantum_errors['cx'][(0,1)].circuits[0][1][0].params[0]
k22=np.transpose(nm._local_quantum_errors['cx'][(0,1)].circuits[0][1][0].params[1].conj())*nm._local_quantum_errors['cx'][(0,1)].circuits[0][1][0].params[1]
k33=np.transpose(nm._local_quantum_errors['cx'][(0,1)].circuits[0][1][0].params[2].conj())*nm._local_quantum_errors['cx'][(0,1)].circuits[0][1][0].params[2]
print(k11+k22+k33)
```

I get the following output:
```
     ┌────────────┐┌───────┐
q_0: ┤0           ├┤ kraus ├
     │  Pauli(II) │├───────┤
q_1: ┤1           ├┤ kraus ├
     └────────────┘└───────┘
3
[[1.        +0.j 0.        +0.j]
 [0.        +0.j 0.99257842+0.j]]
```

But I think that this means that the completeness relation of the kraus operator is not satisfied. Am I missing anything?

**Comment by jakelishman** [comment]
Matrix multiplication is done with `@` on Numpy arrays - `*` is elementwise multiplication.  So the last error (your `k33`) is made a matrix that looks like
```python
k3 = np.array([[0.+0.j, 0.08614861+0.j],  [0.+0.j, 0.+0.j]])
```

If you do `k3.conj().T * k3` (what you've done) you'll get the zero matrix, but if you use `@` to get the matrix multiplication, you'll correctly recover the missing component from the $\lvert 1\rangle\langle 1\rvert$ term.

**Comment by simonecantori** [comment]
> Matrix multiplication is done with `@` on Numpy arrays - `*` is elementwise multiplication. So the last error (your `k33`) is made a matrix that looks like
> 
> ```python
> k3 = np.array([[0.+0.j, 0.08614861+0.j],  [0.+0.j, 0.+0.j]])
> ```
> 
> If you do `k3.conj().T * k3` (what you've done) you'll get the zero matrix, but if you use `@` to get the matrix multiplication, you'll correctly recover the missing component from the |1⟩⟨1| term.

Thank you, I didn't realize I used * instead of np.matmul, sorry.
