### ISSUE TITLE
QuantumCircuit qasm2 dumps generates wrong OpenQASM code

### ISSUE THREAD

**Issue by sergeysalata** [Qiskit/qiskit#11500]
### Select all that apply

- [ ] typo
- [X] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

When exporting QuantumCircuit to OpenQASM U gate exported as 'u' instead of 'U' this leads to error when importing generated OpenQASM code using qasm2.loads()

Step to reproduce:
Run program:

```
from qiskit import qasm2
from qiskit import QuantumRegister, QuantumCircuit
q = QuantumRegister(1, "q")
qc = QuantumCircuit(q)
qc.u(0.3, 0.2, 0.1, q[0])
qq =  qasm2.dumps(qc);
print(qq);
circuit = qasm2.loads( qq );
```

Output:
**OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
u(0.3,0.2,0.1) q[0];**
Traceback (most recent call last):
  File "C:\work\1\python\tele2.py", line 12, in <module>
    circuit = qasm2.loads( qq );
  File "C:\work\quantum\qiskit\lib\site-packages\qiskit\qasm2\__init__.py", line 604, in loads
    return _parse.from_bytecode(
  File "C:\work\quantum\qiskit\lib\site-packages\qiskit\qasm2\parse.py", line 214, in from_bytecode
    for op in bc:
qiskit.qasm2.exceptions.QASM2ParseError: "<input>:4,0: 'u' is not defined in this scope"

But if replace in generated code last line to "**U(0.3,0.2,0.1) q[0];**" then code imported correctly

**Comment by abbycross** [comment]
Thanks for opening an issue, @sergeysalata! Can you provide a URL where the code appears?

**Comment by sergeysalata** [comment]
> Thanks for opening an issue, @sergeysalata! Can you provide a URL where the code appears?

https://github.com/Qiskit/qiskit/blob/main/qiskit/qasm2/export.py

**Comment by abbycross** [comment]
Looks like this belongs in the Qiskit/qiskit repo rather than the qiskit/documentation repo. ~I'll transfer the issue.~ EDITED TO ADD: "transfer issue" isn't working for me!... @sergeysalata can you please open your issue here: https://github.com/Qiskit/qiskit/issues/new/choose

**Comment by sergeysalata** [comment]
moved to https://github.com/Qiskit/qiskit/issues/11508
