### ISSUE TITLE
Fix deprecation messages for 0.46 release

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit#11512]
### Summary

The standard deprecation message states that features will not be removed for 3 months after their deprecation, which is not quite true for deprecations of the 0.46 release that are removed in 1.0. We should ensure we consistently use a deprecation message phrased something like 
```
<this feature> is deprecated since Qiskit 0.46 and will be removed in Qiskit 1.0.
```
This is already done in some places in `quantumcircuit.py` using the [`removal_timeline`](https://github.com/Qiskit/qiskit/blob/273945c0dc82b475e67d9dcee401fcfc6217d045/qiskit/circuit/quantumcircuit.py#L1600) kwarg, but is not yet done in some other places such as [here](https://github.com/Qiskit/qiskit/blob/273945c0dc82b475e67d9dcee401fcfc6217d045/qiskit/pulse/library/discrete.py#L30) or [here](https://github.com/Qiskit/qiskit/blob/273945c0dc82b475e67d9dcee401fcfc6217d045/qiskit/providers/basicaer/unitary_simulator.py#L207). 

We should do this just before the release, such that we only need to do it once 🙂

**Comment by 1ucian0** [comment]
I think https://github.com/Qiskit/qiskit/pull/11296 (`1.0.0`) and https://github.com/Qiskit/qiskit/pull/11564 (`0.46.0`) should address this.

**Comment by jakelishman** [comment]
Changing the decorator will do some/most, definitely. Not all deprecations can be done with the decorator though - sometimes there's just a small part of the inner function, or we're deprecating fetching from one module in favour of another, and those need custom handling. The issue's just to remind us to scan all of them.

**Comment by jakelishman** [comment]
#11564 is being pushed from 0.46 due to the API break, so we'll need to do this manually.  For practicality, I think we can just fold it into #11697, and I'll start pushing up bits to that.

**Comment by jakelishman** [comment]
Done by #11697.
