### ISSUE TITLE
Shor Algorithm should be added to qiskit_algorithms library

### ISSUE THREAD

**Issue by Waliur003** [Qiskit/qiskit#11533]
### What should we add?

Some days ago, I try to implement Shor's Algorithm using the Following code..

`import math
import numpy as np
from qiskit import *
from qiskit.utils import QuantumInstance
from qiskit_algorithms import Shor`

but it showing ImportError and I also learned that Shor’s algorithm was deprecated and removed from 0.22.0 release. the code of ibm quantum learning of Shor' Algorithm [https://learning.quantum.ibm.com/course/fundamentals-of-quantum-algorithms/phase-estimation-and-factoring#introduction](url) is too much hard to learn and understand for beginner's like me and less practical use  for the upcoming quantum computer's future.

can qiskit developers can make arrangements to reestablish it.... :)

**Comment by stubbi** [comment]
found this one: https://github.com/kazawai/shor_qiskit

**Comment by stubbi** [comment]
this one might be even better suited: https://github.com/Shailaja87/BE_PROJECT/tree/main

**Comment by Waliur003** [comment]
Thanks, A lot..... @stubbi

**Comment by jakelishman** [comment]
I'll close this as "stale" or "can't fix here" now - core Qiskit doesn't include any large-scale implementations of full quantum algorithms.  This could be taken up at https://github.com/qiskit-community/qiskit-algorithms, but my understanding is that Shor was removed for a reason, so I'd imagine it's unlikely to be re-added.

I'd note that if it's just a tutorial in implementation that's of interest, the IBM Quantum platform has an example: https://learning.quantum.ibm.com/course/fundamentals-of-quantum-algorithms/phase-estimation-and-factoring#shors-algorithm.
