### ISSUE TITLE
PrimitiveJob should stop inheriting from JobV1

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit#11541]
### What should we add?

Based on the discussion in https://github.com/Qiskit/qiskit/pull/11531

`PrimitiveJob` today inherits from `JobV1`. While it's not actually documented (because it predates the use of type hint), the `.result()` method of `JobV1` is expected to return a `Result` object. This of course is not true for a `PrimitiveJob`. 

In addition, there are a number of improvements that we can do to `Job`. But since we already have `PrimitiveJob`, it's easier to just change `PrimitiveJob` instead of coming up with `JobV2` for `PrimitiveJob` to inherit. 

Here's my proposal:
1. Copy the same methods from `JobV1` to `PrimitiveJob`, unless otherwise noted below
1. Remove `submit()`. This is useless as a public method, since it's invoked by `primitive.run()` and cannot be invoked again. 
2. Return a string instead of enum for `status()`. While it's nice to have a predefined enums, it disallows implementers to add additional statuses. We can keep individual status-related methods like `running()` etc, and the implementers just need to overwrite that if needed.
3. Remove `backend()`. `JobV1` is not required to be initialized with a `backend`, but `backend()` raises an error if it's missing? 
4. Change `job_id` to an attribute instead of a method, mostly to match the fact `name` is an attribute in `BackendV2`. This is of course a huge breaking change, so I don't feel too strongly about.

**Comment by jyu00** [comment]
fyi @ikkoham and @t-imamichi

**Comment by ihincks** [comment]
@jyu00 this all makes sense. I'm wondering if you have ideas for how to maintain support for those things tha rely on how `submit()` is currently implemented (setting up the thread pool and making the future based on init function, etc). Add a `PrimitiveJobV1(PrimitiveJob)` or something?

**Comment by jyu00** [comment]
We can change known `primitive.run()` to

```python
job = PrimitiveJob()
executor = ThreadPoolExecutor(max_workers=1)
job._future = executor.submit(self._call, circuit_indices, observable_indices, parameter_values, **run_options)
executor.shutdown(wait=False)
return job
```

If you worry there are other primitive implementers that rely on this, we can (1) deprecate `submit()` in 0.46 and remove in 1.0 or (2) start versioning `PrimitiveJob`. 

I prefer (1) since there is less maintenance, but the runway is pretty short.

**Comment by t-imamichi** [comment]
Since `PrimitiveJob.submit` is supposed to be invoked internally and not expected to be invoked by users explicitly, I agree with (1) to deprecate `submit`. I think there is an option to make `submit` method private, e.g., `_submit`, not to repeat the thread pool part in Estimator and Sampler.

**Comment by jakelishman** [comment]
On point 3: this is one place where you might want to make the return value a generic type.  As you say, the `status` field is unlikely to port between implementations of a primitive (if you make it a string or generic, you encode that users _must not_ assume it ports for all primitives, though doubtless some will try anyway), but if you make the relevant part of the job:
```python
class PrimitiveJob[Status](ABC):
    @abstractmethod
    def status(self) -> Status: ...
```
then IBM Runtime (say) can define their job
```python
class IBMPrimitiveJob(PrimitiveJob[IBMPrimitiveStatus]):
    def status(self): ...
```
and then a user of the IBM primitives specifically can get type hinting and checking against the proper return value.  If they're working with primitives interchangeably, their type checker will complain at them.  If it's hard-coded to be a `str`, users will still _try_ and compare to known values and whatnot, and we risk creating a system where a sort of de facto convention pops up, so people will then _want_ the string values to be the same for everything, etc, etc, and there's no scope for implementors to have rich status returns in the future.

Bear in mind that making `running`, `cancelled`, etc abstract is a breaking change to an interface.  To keep the interface backwards compatible, you'll likely need to have those methods continue to have concrete implementations that do what they do now (with `JobStatus`), and just say that now the class is generic / stringly-typed, implementors must override them if they don't return `JobStatus`.

**Comment by ihincks** [comment]
@t-imamichi would you be able to take this one on?

**Comment by jyu00** [comment]
Also, ignore my [comment](https://github.com/Qiskit/qiskit/issues/11541#issuecomment-1885607881) here. 

I realized `JobV1` is an abstract class and `PrimitiveJob` isn't. So really we can have a new `BasePrimitiveJob` that replaces  `JobV1` as the parent, does not have `submit()` etc. Then `PrimitiveJob` can continue to have a `submit()` that will be deprecated and replaced by `_submit()`.

**Comment by t-imamichi** [comment]
OK. I take this issue.

**Comment by t-imamichi** [comment]
I made #11552. Could you check whether this follows the discussions?
