### ISSUE TITLE
ImportError: cannot import name 'Initialize' from 'qiskit.circuit.library.data_preparation'

### ISSUE THREAD

**Issue by ACE07-Sev** [Qiskit/qiskit#11551]
### Environment

- **Qiskit Terra version**: 0.45.1
- **Python version**: 3.10
- **Operating system**: Windows

### What is happening?

I am trying to run the Pytket AerBackend, and it requires importing :
`from pytket.extensions.qiskit import AerBackend`

However, when I run this I get the following error :
`Traceback (most recent call last):
  Cell In[53], line 1
    from pytket.extensions.qiskit import AerBackend
  File /opt/conda/lib/python3.10/site-packages/pytket/extensions/qiskit/__init__.py:18
    from .backends import (
  File /opt/conda/lib/python3.10/site-packages/pytket/extensions/qiskit/backends/__init__.py:16
    from .ibm import IBMQBackend, NoIBMQCredentialsError
  File /opt/conda/lib/python3.10/site-packages/pytket/extensions/qiskit/backends/ibm.py:37
    from qiskit.primitives import SamplerResult  # type: ignore
  File /opt/conda/lib/python3.10/site-packages/qiskit/primitives/__init__.py:55
    from .base import BaseEstimator
  File /opt/conda/lib/python3.10/site-packages/qiskit/primitives/base/__init__.py:17
    from .base_estimator import BaseEstimator
  File /opt/conda/lib/python3.10/site-packages/qiskit/primitives/base/base_estimator.py:95
    from ..utils import init_observable
  File /opt/conda/lib/python3.10/site-packages/qiskit/primitives/utils.py:25
    from qiskit.circuit.library.data_preparation import Initialize
ImportError: cannot import name 'Initialize' from 'qiskit.circuit.library.data_preparation' (/opt/conda/lib/python3.10/site-packages/qiskit/circuit/library/data_preparation/__init__.py)`

### How can we reproduce the issue?

Just run :
`from pytket.extensions.qiskit import AerBackend
`

### What should happen?

Well it should pass this, and allow for running the pytket code.

### Any suggestions?

I ran this, and it didn't give an issue, but I can't use this as I still need this to be fixed through the package or pytket import won't work :
`from qiskit.circuit.library.data_preparation.initializer import Initialize`

**Comment by Cryoris** [comment]
I'm not able to reproduce this error using `qiskit==0.45.1` and `pytket-qiskit==0.47.0`. Does the plain import
```
from qiskit.circuit.library.data_preparation.initializer import Initialize
```
work for you? If not you might not be using 0.45.1.

**Comment by jakelishman** [comment]
`Initialize` is definitely importable in Qiskit 0.45 from both `qiskit.circuit.library` and `qiskit.circuit.library.data_preparation`, so you shouldn't need the over specific import.  It's possible that your Python environment is a bit messed up somehow - your error message suggests that everything is installed in the global `site-packages`, and not in a virtual environment (conda or otherwise).

I'd recommend [using `conda` (since you're using that) to create virtual environments](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) for different tasks; it's much easier to verify that your environment is sound in those cases.

Similar to Julien, I can't reproduce this is in a fresh environment initialised with `pip install pytket-qiskit`.

**Comment by ACE07-Sev** [comment]
I am using IBM Quantum Lab. I can try to make a virtual env externally, I usually just use the notebook online and it's never had any issues to be honest.

**Comment by ACE07-Sev** [comment]
> I'm not able to reproduce this error using `qiskit==0.45.1` and `pytket-qiskit==0.47.0`. Does the plain import
> 
> ```
> from qiskit.circuit.library.data_preparation.initializer import Initialize
> ```
> 
> work for you? If not you might not be using 0.45.1.

This works. The one that has the issue doesn't.

**Comment by ACE07-Sev** [comment]
It's alright, I'll try to create a virtual env using conda. If the issue persists there I'll reopen this issue. 

Thank you for the prompt response and kind support. Please feel free to close this for now if you wish.
