### ISSUE TITLE
Issue in RZXCalibrationBuilder class

### ISSUE THREAD

**Issue by filippo-phasecraft** [Qiskit/qiskit#11616]
### Environment

- **Qiskit Terra version**: 0.45.2
- **Python version**: 3.10.13
- **Operating system**: MacOS 12.4

### What is happening?

There is an bug in the `__init__` function of the `RZXCalibrationBuilder` class (in the `qiskit.transpiler.passes.calibration.builders` module). In particular, the error occurs when the `instruction_schedule_map` attribute of an `IBMBackend` object is called: 

```python
File ~/miniforge3/envs/qiskit_new/lib/python3.10/site-packages/qiskit/transpiler/passes/calibration/rzx_builder.py:91, in RZXCalibrationBuilder.__init__(self, instruction_schedule_map, verbose, target)
     89 self._verbose = verbose
     90 if target:
---> 91     self._inst_map = target.instruction_schedule_map()
     92 if self._inst_map is None:
     93     raise QiskitError("Calibrations can only be added to Pulse-enabled backends")

TypeError: 'InstructionScheduleMap' object is not callable
```

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit
from qiskit.transpiler.passes.calibration.builders import RZXCalibrationBuilder
from qiskit.circuit import Gate
from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService()
backend = service.backend(name='ibm_brisbane')

# Build the circuit

theta = 0.5
qubits = (0,1)
circuit = QuantumCircuit(2)

gate = Gate('RZX', 2, [theta])

circuit.compose(
    gate,
    qubits=qubits,
    inplace=True
    )

circuit.measure_all()

inst_map = backend.instruction_schedule_map

RZX_builder = RZXCalibrationBuilder(
    instruction_schedule_map = inst_map,
    target = backend
    )
    
pulse_schedule = RZX_builder.get_calibration(gate,qubits)

gate_with_schedule = (gate,qubits,pulse_schedule)
    
circuit.add_calibration(*gate_with_schedule)
```

### What should happen?

The code above should not return an error.

### Any suggestions?

The issue should be solved by replacing `self._inst_map = target.instruction_schedule_map()` with `self._inst_map = target.instruction_schedule_map ` in line 91 of the `qiskit/transpiler/passes/calibration/rzx_builder.py` file.

**Comment by jakelishman** [comment]
The argument to `target` in `RZXCalibrationBuilder` should be a `Target` instance, not a `Backend` instance - you likely meant `target=backend.target` rather than `target=backend`.

**Comment by filippo-phasecraft** [comment]
Thanks for the clarification, Jake! This fixed the issue.
