### ISSUE TITLE
Disjoint handling in transpiler fails to rejoin barriers

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit#11649]
### Environment

- **Qiskit Terra version**: `main` @ ce02f06
- **Python version**: 3.10
- **Operating system**: macOS

### What is happening?

The preset passmangers for `transpile` are failing to correctly reconstruct barriers temporarily inserted during the compiler routing, which is leaking out invalid `UUID` objects inside the `label` field of those barriers.

### How can we reproduce the issue?

Given a set up of:

```python
from qiskit import transpile, QuantumCircuit
from qiskit.transpiler import CouplingMap

cm = CouplingMap([
    (0, 1),
    (1, 2),
    #
    (3, 4),
])
qc = QuantumCircuit(cm.size(), cm.size())
qc.cx(0, 1)
qc.cx(1, 2)
qc.cx(2, 0)
#
qc.cx(3, 4)
qc.measure(qc.qubits, qc.clbits)

out = transpile(qc, coupling_map=cm, seed_transpiler=0)
```

`out` contains `Barrier` instructions whose `label` attributes are not strings (they're `UUID` objects) and shouldn't exist at all, because the input circuit doesn't have any:

```python
for i, ins in enumerate(out.data):
    if ins.operation.name == "barrier":
        print(i, repr(ins.operation.label))
        # Coerce to string so I can draw the circuit after.
        ins.operation.label = str(ins.operation.label)
```
```text
8 UUID('31558989-c21a-4e5c-b014-01639295df7b')
10 UUID('31558989-c21a-4e5c-b014-01639295df7b')
12 UUID('31558989-c21a-4e5c-b014-01639295df7b')
14 UUID('31558989-c21a-4e5c-b014-01639295df7b')
15 UUID('31558989-c21a-4e5c-b014-01639295df7b')
```

I can't draw the circuit because the visualiser will explode, as will QPY (how this issue was detected).  If I coerce those particular labels just to be string instances, the circuit looks like this:
```text
                                                    ┌───┐                          ┌───┐                  31558989-c21a-4e5c-b014-01639295df7b ┌─┐
q_2 -> 0 ───────────────────────X───────────────────┤ H ├───────■──────────────────┤ H ├───────────────────────────────────░───────────────────┤M├───
                                │                   └───┘       │                  └───┘                                   ░                   └╥┘
                                │                   ┌───┐     ┌─┴─┐                ┌───┐                  31558989-c21a-4e5c-b014-01639295df7b  ║ ┌─┐
q_0 -> 1 ──■────────────────────X───────────────────┤ H ├──■──┤ X ├────────────────┤ H ├───────────────────────────────────░────────────────────╫─┤M├
           │                                        └───┘  │  └───┘                └───┘                                   ░                    ║ └╥┘
         ┌─┴─┐                ┌───┐                      ┌─┴─┐┌───┐ 31558989-c21a-4e5c-b014-01639295df7b                  ┌─┐                   ║  ║
q_1 -> 2 ┤ X ├────────────────┤ H ├──────────────────────┤ X ├┤ H ├──────────────────░────────────────────────────────────┤M├───────────────────╫──╫─
         └───┘                └───┘                      └───┘└───┘                  ░                                    └╥┘                   ║  ║
               31558989-c21a-4e5c-b014-01639295df7b  ┌─┐                                                                   ║                    ║  ║
q_3 -> 3 ──■────────────────────░────────────────────┤M├───────────────────────────────────────────────────────────────────╫────────────────────╫──╫─
           │                    ░                    └╥┘                                                                   ║                    ║  ║
         ┌─┴─┐ 31558989-c21a-4e5c-b014-01639295df7b   ║   ┌─┐                                                              ║                    ║  ║
q_4 -> 4 ┤ X ├──────────────────░─────────────────────╫───┤M├──────────────────────────────────────────────────────────────╫────────────────────╫──╫─
         └───┘                  ░                     ║   └╥┘                                                              ║                    ║  ║
    c: 5/═════════════════════════════════════════════╩════╩═══════════════════════════════════════════════════════════════╩════════════════════╩══╩═
                                                      3    4                                                               1                    0  2
```
so it's clear the temporary barrier we insert before measures isn't being recombined and then deleted.

### What should happen?

* The temporary barrier should have been recombined after the disjoint handling
* The temporary barrier should have been removed before the circuit exited
* We probably shouldn't use a literal `UUID` in the `Barrier.label` field since that's supposed to be constrained to be a string (everything except `Barrier` seems to enforce that, too).

**Comment by mtreinish** [comment]
So the root of the issue here is a shared state issue. When `SabreLayout` (or other layout passes too) calls `qiskit.transpiler.passes.layout.disjoint_utils.run_pass_over_connected_components` it passes the input dag directly and when there is >1 connected component the first thing as part of it does is split the barriers on the dag it receives in place to enable separating the circuit into it's connected components. This is modifying the input dag which when there is more > 1 connected component gets returned as is because we need to run routing separately. This is causing the barrier to leak out with the uuid label and that barrier isn't getting removed (from #10323) because the label changed. 

There are two paths to fixing this, the first is just making a deepcopy of the dag so that there isn't a shared state when we split the barriers which will preserve the original input dag.  The other option is to run `disjoint_utils.combine_barriers(retain_uuid=False)` before returning the input dag when there is more than one connected component to reverse the barrier splitting (this will also involve fixing the uuid piece to work with existing labels).

**Comment by jakelishman** [comment]
My feeling is that running the barrier combiner with a limit to ensure it considers only the barriers split by the previous step is the cleaner approach, and the more reliable from a performance standpoint.
