### ISSUE TITLE
Add API docs section for synthesis plugins post-1.0.0rc1

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#11675]
### What should we add?

We should have a dedicated page in the api docs that enumerate all the built-in transpiler synthesis plugins. These should list the plugin name and the details of all the plugins. Right now we only have this page:

https://github.com/Qiskit/qiskit/blob/main/docs/apidoc/transpiler_builtin_plugins.rst

which only lists aqc. 

This was attempted in #10657 but was removed from that PR because it was larger scope than just adding that method. What was attempted in that PR was to use the class docstrings for the plugin classes. The issue with that though is that the plugin method interface isn't actually the class, but instead is the plugin name. It was a bit awkward to link to all the classes in the documentation but say the interface being documented isn't the thing you should use, that link just contains the details of some other interface not explicitly documented.

We should try to include this in the final 1.0.0 release, as it's only documentation changes we can do this post-rc1 as it won't change any interfaces being released.

**Comment by kevinsung** [comment]
It appears that https://github.com/Qiskit/qiskit/pull/11763 only added documentation for the `aqc` unitary synthesis plugin, but not the `default` and `sk` plugins. Am I missing something? How do I find the documentation for the `default` unitary synthesis plugin?

**Comment by ShellyGarion** [comment]
> It appears that #11763 only added documentation for the `aqc` unitary synthesis plugin, but not the `default` and `sk` plugins. Am I missing something? How do I find the documentation for the `default` unitary synthesis plugin?

You can find all unitary synthesis plugins here: https://docs.quantum.ibm.com/api/qiskit/transpiler_synthesis_plugins#unitary-synthesis-plugins-2

The Solovay-Kitaev plugin is here: https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.synthesis.solovay_kitaev_synthesis.SolovayKitaevSynthesis

The default unitary plugin is here: https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.synthesis.unitary_synthesis.DefaultUnitarySynthesis

**Comment by kevinsung** [comment]
> > It appears that #11763 only added documentation for the `aqc` unitary synthesis plugin, but not the `default` and `sk` plugins. Am I missing something? How do I find the documentation for the `default` unitary synthesis plugin?
> 
> You can find all unitary synthesis plugins here: https://docs.quantum.ibm.com/api/qiskit/transpiler_synthesis_plugins#unitary-synthesis-plugins-2
> 
> The Solovay-Kitaev plugin is here: https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.synthesis.solovay_kitaev_synthesis.SolovayKitaevSynthesis
> 
> The default unitary plugin is here: https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.synthesis.unitary_synthesis.DefaultUnitarySynthesis

This is what I was looking for, thank you!
