### ISSUE TITLE
Documentation of HighLevelSynthesisPlugin doesn't show abstract properties

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit#11683]
### Environment

- **Qiskit version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

See https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.synthesis.plugin.HighLevelSynthesisPlugin.

In comparison, https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.synthesis.plugin.UnitarySynthesisPlugin does document them.

### How can we reproduce the issue?

N/A

### What should happen?

N/A

**Comment by jakelishman** [comment]
Those two links go to the same place at the moment - did you mean the good example is https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.synthesis.plugin.UnitarySynthesisPlugin?

**Comment by kevinsung** [comment]
> Those two links go to the same place at the moment - did you mean the good example is https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.synthesis.plugin.UnitarySynthesisPlugin?

Yes, thank you, I've updated my post.

**Comment by atharva-satpute** [comment]
Does it not show after adding a new abstract property? Currently at the tip of `main` there isn't any abstract property in `HighLevelSynthesisPlugin`

**Comment by kevinsung** [comment]
Hmm I don't recall what I was thinking about in my original post. I'll just close.
