### ISSUE TITLE
Misspelling of "probabilities" (currently "probablities") in stabilizerstate.py and test_stabilizerstate.py tests

### ISSUE THREAD

**Issue by DerekMiner** [Qiskit/qiskit#11688]
### Environment

There are several method calls that are misspelled as "probablities" instead of "probabilities" in the 
`qiskit/quantum_info/states` and 
`test/python/quantum_info/states` classes.

methods found with misspelling:

<img width="534" alt="Screenshot 2024-01-30 at 4 11 57 PM" src="https://github.com/Qiskit/qiskit/assets/9966028/28679c47-4947-43a7-8e72-c01b61979b90">

### What is happening?

Misspelling for the word probabilities for several of the stabilizerstate.py methods and tests for stabilizerstate

### How can we reproduce the issue?

no reproduce needed
misspelling is in release Qiskit 0.45.2

### What should happen?

spelling should be corrected to align with spelling throughout project

### Any suggestions?

update the method and test names

**Comment by DerekMiner** [comment]
I am already working on issue #11425 which works with these methods, I would be happy to take this issue and fix as well

**Comment by ShellyGarion** [comment]
Since all the misprints are only in internal functions and tests, you can go ahead and fix them. thanks!
