### ISSUE TITLE
Default values for `approximation_degree` differ in `transpile` and `generate_preset_pass_manager`

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit#11693]
### Environment

- **Qiskit version**: 0.45
- **Python version**: 
- **Operating system**: 

### What is happening?

The `transpile` function has a default value of `approximation_degree=1.0` while the `generate_preset_pass_manager` function has `approximation_degree=None`. This can lead to drastically different default behavior when transpiling with these two functions on certain backends which was found by some recent researchers using the pass manager based code.

### How can we reproduce the issue?

To quote the example I was given:
> we had circuits with ~700 gates when  using v1 backends and/or transpile, but this dropped down to ~200 gates when using the preset pm.
on top of this, the approximation is also dependent on the actual 2Q unitary.

### What should happen?

The default values should be consistent between `transpile` and the preset pass manager.

### Any suggestions?

I believe the intended behavior is what is done in `transpile` (no approximation), so the preset pass manager should be updated to have a default kwarg value of `approximation_degree=1.0` to match

**Comment by jakelishman** [comment]
Yeah, this sounds very surprising in a very bad way, and we (eventually) did come to the conclusion that `approximation_degree=None` was a bad default.  Flicking quickly through the history, it looks like we changed the `transpile` default in #8595 and missed doing `generate_preset_pass_manager`, which was quite new at the time.

I think we can quickly fold this into 1.0 - I think it's better to squeeze in the "bug fix" API break after the feature-freeze deadline than to navigate a changing default through the 1.0 stability policy.
