### ISSUE TITLE
Add `two_qubit_cnot_decompose` to `qiskit.synthesis` docstring

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit#11709]
I think this `two_qubit_cnot_decompose` is missing an `.. autofunction::` in the docstring?  If it's meant to be there, let's take a note to add it after rc1 - no need to hold up the PR over a documentation thing.

_Originally posted by @jakelishman in https://github.com/Qiskit/qiskit/pull/11687#discussion_r1475028459_

**Comment by ShellyGarion** [comment]
I wasn't sure what to do with this function, since it has no docstring, and also due to the comment here: 
https://github.com/Qiskit/qiskit/blob/a234ff2dc717884fa9b1c3dce3e3d8c4c3eccbfb/qiskit/synthesis/two_qubit/two_qubit_decompose.py#L1531
