### ISSUE TITLE
`parallel_map` documents Events that it no longer publishes

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit#11708]
https://github.com/Qiskit/qiskit/blob/a73bf7c3be3d6a105b10b4f7c2c7b0d7e62102c4/qiskit/tools/parallel.py#L133-L136

I had been looking to update the parallel_map usage in Nature, given the change in location for 1.0 and noticed it still has these documented (we use TextProgressBar too that will have to go - it was just in logging so no big deal)

**Comment by jakelishman** [comment]
Thanks - we can squash a documentation-only change in after 1.0.0rc1.
