### ISSUE TITLE
`qiskit.synthesis.two_qubit_cnot_decompose` is missing documentation

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#11710]
> I think this `two_qubit_cnot_decompose` is missing an `.. autofunction::` in the docstring?  If it's meant to be there, let's take a note to add it after rc1 - no need to hold up the PR over a documentation thing.

_Originally posted by @jakelishman in https://github.com/Qiskit/qiskit/pull/11687#discussion_r1475028459_

**Comment by jakelishman** [comment]
#11709 

there's a parrot in here ;)
