### ISSUE TITLE
Preset pass manager ignores basis_gates

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit#11746]
### Environment

- **Qiskit version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

Title

### How can we reproduce the issue?

```python
from qiskit.transpiler.preset_passmanagers.level1 import level_1_pass_manager
from qiskit.transpiler import PassManagerConfig
from qiskit.providers.fake_provider import FakeNairobiV2

backend = FakeNairobiV2()
pmc = PassManagerConfig.from_backend(backend, basis_gates=["cx", "x"])
pm = level_1_pass_manager(pmc)
pm.run(circuit)
```

### What should happen?

It should be `TranspilationError`.

**Comment by jakelishman** [comment]
I'll close this one in favour of #11747 which has a bit more detail.
