### ISSUE TITLE
FutureWarning: The default matplotlib

### ISSUE THREAD

**Issue by steve-beaver** [Qiskit/qiskit#11762]
### Environment

- **Qiskit version**: 0.46
![image](https://github.com/Qiskit/qiskit/assets/74922210/3df1bbfb-5119-4863-9519-5c3635a79de3)

### What is happening?

C:\Users\Steve\PycharmProjects\pythonProject4\.venv\Scripts\python.exe C:\Users\Steve\PycharmProjects\pythonProject4\main.py 
C:\Users\Steve\PycharmProjects\pythonProject4\.venv\Lib\site-packages\qiskit\visualization\circuit\matplotlib.py:266: FutureWarning: The default matplotlib drawer scheme will be changed to "iqp" in a following release. To silence this warning, specify the current default explicitly as style="clifford", or the new default as style="iqp".
  self._style, def_font_ratio = load_style(self._style)

Process finished with exit code 0

### How can we reproduce the issue?

from qiskit.circuit.library import MCXGate

gate = MCXGate(4)

from qiskit import QuantumCircuit

circuit = QuantumCircuit(5)
circuit.append(gate, [0, 1, 4, 2, 3])
circuit.draw('mpl')

### What should happen?

It should not die here \matplotlib.py:266

### Any suggestions?

Let me know how to fix the problem

**Comment by jakelishman** [comment]
The warning message explains what is happening and how to fix/suppress the warning.  If you require the old style in `QuantumCircuit.draw`, specify a `style='clifford'` argument, or `style='iqp'` if you're happy to use the new style (which will become the default in Qiskit 1.0).

The code should not be "dying", it's just issuing a warning.

**Comment by steve-beaver** [comment]
I think I will wait for 1.0 – Since IBM generally in the zOS world bundles PTF’s in  RSU’s cover many al ill

 

Which begs the question when will 1.0 be available such that I can  “python.exe -m pip install --upgrade pip”

 

 

 

 

Regards,

 

 

Steve Beaver

***@***.***

 

Office : 806-368-3859

Cell      : 806-300-9481

 

No man is a true believer unless he desires for his brother that, what he desires for himself. 





--------------------------------------------------------------------------------

This electronic mail (including any attachments) may contain information that is privileged, confidential, and/or otherwise protected from disclosure to anyone other than its intended recipient(s). Any dissemination or use of this electronic email or its contents (including any attachments) by persons other than the intended recipient(s) is strictly prohibited. If you have received this message in error, please notify us immediately by reply email so that we may correct our internal records. Please then delete the original message (including any attachments) in its entirety. Thank you

**Comment by jakelishman** [comment]
Qiskit 1.0 is currently expected to be released on the 15th of February.  In the mean time, you could install `qiskit<0.46`, use one of the remedies suggested in the message or [using a Qiskit configuration file](https://docs.quantum.ibm.com/start/configure-qiskit-local), filter the warning out using the standard Python tools, or just ignore it.

I'm going to close this issue as "resolved", but feel free to re-open if there's more that needs discussing.

**Comment by steve-beaver** [comment]
Qiskit 1.0 is currently expected to be released on the 15th of February.

do I need to uninstall Qiskit and re-install it?

**Comment by jakelishman** [comment]
We will be recommending that you create a new virtual environment to install Qiskit 1.0 in, rather than trying to upgrade in-place, once it is released.

**Comment by steve-beaver** [comment]
It will be just as easy to pip uninstall Qiskit and then pip install qiskit matplotlib pylatexenc

 

 

Regards,

 

 

Steve Beaver

***@***.***

 

Office : 806-368-3859

Cell      : 806-300-9481

 

No man is a true believer unless he desires for his brother that, what he desires for himself. 





--------------------------------------------------------------------------------

This electronic mail (including any attachments) may contain information that is privileged, confidential, and/or otherwise protected from disclosure to anyone other than its intended recipient(s). Any dissemination or use of this electronic email or its contents (including any attachments) by persons other than the intended recipient(s) is strictly prohibited. If you have received this message in error, please notify us immediately by reply email so that we may correct our internal records. Please then delete the original message (including any attachments) in its entirety. Thank you
