### ISSUE TITLE
Qiskit 1.0 release notes page has unreleased notes for 0.46.1

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit#11835]
https://github.com/Qiskit/documentation/blob/f88b31e9e500ad87b465be1b1eb6702e8345d757/docs/api/qiskit/release-notes/1.0.md?plain=1#L1142

From Slack:

> Jake: our reno config is assuming that a stable branch won’t have any unreleased updates if we’re making a new minor. or major
> Matthew: We should probably strip the old branches from the release_notes.rst on stable/1.x  and main
> Jake: I guess with our current syncing process that probably works the best, yeah

**Comment by jakelishman** [comment]
Is this / can this be fixed on the docs side now 1.0.1 is out?

**Comment by Eric-Arellano** [comment]
Yep, confirmed fixed in https://github.com/Qiskit/documentation/pull/877 🙌
