### ISSUE TITLE
Weird header from bullet list for 0.46 release notes

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit#11836]
https://docs.quantum.ibm.com/api/qiskit/release-notes/0.46#any-fake-backend-contained-in-qiskitprovidersfake_providerbackends

<img width="276" alt="Screenshot 2024-02-02 at 8 37 59 AM" src="https://github.com/Qiskit/documentation/assets/14852634/c1c3c513-0d61-487d-bf34-c42033457bf4">
<img width="818" alt="Screenshot 2024-02-02 at 8 38 19 AM" src="https://github.com/Qiskit/documentation/assets/14852634/33738603-34a3-437d-8155-a339bfa9508b">

The bullet list is being set as an h2.

https://github.com/Qiskit/documentation/blob/c6ef8cd69ba150791646ea05e0de55f4f861f6cd/docs/api/qiskit/release-notes/0.46.md?plain=1#L245

This is the HTML from Sphinx:

```html
<p>The <a class="reference internal" href="apidoc/providers_fake_provider.html#module-qiskit.providers.fake_provider" title="qiskit.providers.fake_provider"><code class="xref py py-mod docutils literal notranslate"><span class="pre">qiskit.providers.fake_provider</span></code></a> module has been migrated to
   the <code class="docutils literal notranslate"><span class="pre">qiskit-ibm-runtime</span></code> Python package. For this reason, the following elements in
   the <a class="reference internal" href="apidoc/providers_fake_provider.html#module-qiskit.providers.fake_provider" title="qiskit.providers.fake_provider"><code class="xref py py-mod docutils literal notranslate"><span class="pre">qiskit.providers.fake_provider</span></code></a> have been deprecated as of Qiskit 0.46 and will be
   removed in Qiskit 1.0:
</p>
<ul class="simple">
<li>
   <p><a class="reference internal" href="stubs/qiskit.providers.fake_provider.FakeProvider.html#qiskit.providers.fake_provider.FakeProvider" title="qiskit.providers.fake_provider.FakeProvider"><code class="xref py py-class docutils literal notranslate"><span class="pre">qiskit.providers.fake_provider.FakeProvider</span></code></a></p>
</li>
<li>
   <p><a class="reference internal" href="stubs/qiskit.providers.fake_provider.FakeProviderForBackendV2.html#qiskit.providers.fake_provider.FakeProviderForBackendV2" title="qiskit.providers.fake_provider.FakeProviderForBackendV2"><code class="xref py py-class docutils literal notranslate"><span class="pre">qiskit.providers.fake_provider.FakeProviderForBackendV2</span></code></a></p>
</li>
<li>
   <p><code class="xref py py-class docutils literal notranslate"><span class="pre">qiskit.providers.fake_provider.FakeProviderFactory</span></code></p>
</li>
<li>
   <p><code class="xref py py-class docutils literal notranslate"><span class="pre">qiskit.providers.fake_provider.fake_backends.FakeBackendV2</span></code></p>
</li>
<li>
   <dl class="simple">
      <dt>any fake backend contained in <code class="xref py py-mod docutils literal notranslate"><span class="pre">qiskit.providers.fake_provider.backends</span></code></dt>
      <dd>
         <p>(accessible through the provider)</p>
      </dd>
   </dl>
</li>
```

**Comment by Eric-Arellano** [comment]
This still isn't fixed for some reason by https://github.com/Qiskit/documentation/pull/822! Even though the HTML is fixed in the HTML we use for 1.0 from Box:

```
<li><p>any fake backend contained in <code class="docutils literal notranslate"><span class="pre">qiskit.providers.fake_provider.backends</span></code> (accessible through the provider)</p></li>
```

I'm not sure what's happening.

**Comment by Eric-Arellano** [comment]
This is still happening because the same release note is showing up both in 1.0 and 0.46. We only fixed the formatting in the 1.0 file. If you look at `release_notes.html` from the CI Sphinx output at https://ibm.box.com/shared/static/9mgo99x54z3rpo8irs23olqsov3uo1ly.zip, search for "any fake backend" and you'll see two entries.

https://github.com/Qiskit/documentation/blob/2aba8eb27650dcf4371c2b593e12bce82a9b0f12/docs/api/qiskit/release-notes/0.46.md?plain=1#L239-L253

https://github.com/Qiskit/documentation/blob/2aba8eb27650dcf4371c2b593e12bce82a9b0f12/docs/api/qiskit/release-notes/1.0.md?plain=1#L748-L754

@jakelishman @mtreinish would you expect the release note to show up in both places? Note that they are different messages, particularly the first line.

If this is expected, then I think the fix is to fix the release note on the `stable/0.46` branch.

**Comment by jakelishman** [comment]
From #11835: sorting out which branches of release notes we build into particular version docs builds (and hence get synced to docs.quantum.ibm.com) is something we'll probably need to think about a little more long term, but for now, removing 0.x branches from the 1.x release-notes builds is probably the right for way us to go.  I'll mark #11837 as closing this issue completely, and the rest can be tracked through #11835.

**Comment by Eric-Arellano** [comment]
Fixed in https://github.com/Qiskit/documentation/pull/995.
