### ISSUE TITLE
No module named qiskit error

### ISSUE THREAD

**Issue by tylerstewartt** [Qiskit/qiskit#11845]
### Environment

- **Qiskit version**: 1.0.0
- **Python version**: 3.12.1 and 3.8
- **Operating system**: Windows 10

### What is happening?

After following numerous guides [example](https://subscription.packtpub.com/book/programming/9781838828448/1/ch01lvl1sec04/installing-qiskit) to install qiskit via anaconda and jupyter notebook, I keep getting the error no module named qiskit after doing import qiskit; qiskit.__qiskit_version__

I have tried making a conda enviroment running the latest version of python, as well as python 3.8. I've also tried installing qiskit via pip as well as pip3. When I run pip list, I can see qiskit 1.0.0 listed.

I get the error in jupyter notebook and also running python3 in Anaconda Prompt. No matter what I try, I keep getting the error. Anyone know where I could have gone wrong?

### How can we reproduce the issue?

Install qiskit through anaconda prompt by making a new enviroment and install qiskit and jupyter notebook using pip or pip3.

### What should happen?

 import qiskit; qiskit.__qiskit_version__ should display the version of qiskit installed

**Comment by jakelishman** [comment]
If you're struggling to `import qiskit`, the chances are that you're not activating your virtual environment before trying to use the package.  Make sure you `conda activate <your-environment-name>` (assuming you're using `conda`, as in that guide) before trying to open Jupyter, and every time you open a new Anaconda prompt session.

This is unlikely to be a problem with Qiskit.  You might also want to check if you're able to successfully install over packages and then import them.

**Comment by tylerstewartt** [comment]
> Make sure you `conda activate <your-environment-name>` (assuming you're using `conda`, as in that guide) before trying to open Jupyter, and every time you open a new Anaconda prompt session.

Sorry, forgot to mention that this was the first step I did.  I made two different Anaconda virtual environments, one running the latest version of python and one running 3.8 just to troubleshoot, but for both I started with activating the environment before running pip installs and jupyter.

**Comment by jakelishman** [comment]
Whenever you try and launch a Python interpreter, you also need to make sure the environment is active - it's not just before installation. You may also want to verify that the package is being installed into the expected place. Are you able to install and use other packages using `pip`?

**Comment by tylerstewartt** [comment]
I'm pretty sure the environment is active the whole time. Here are the steps I took:

```
conda create -n qiskitenv python=3

conda activate qiskitenv

pip install qiskit

pip install jupyter notebook

jupyter notebook
```

Side note, maybe this is improvement, but I tried recreating it again and this time when inputting:

```
import qiskit

qiskit.__qiskit_version__
```

into a Jupyter notebook, I got the error: module 'qiskit' has no attribute '__qiskit_version__'.

**Comment by jakelishman** [comment]
Ok, your second example is a working Qiskit installation.  `qiskit.__qiskit_version__` was removed in Qiskit 1.0 because Qiskit isn't a metapackage anymore (i.e. there's no `qiskit-terra` component, and so on).  If you query `qiskit.__version__` (the standard Python attribute), you should see `"1.0.0"`.

**Comment by tylerstewartt** [comment]
That worked, thank you!
