### ISSUE TITLE
cannot import name 'execute' from 'qiskit'

### ISSUE THREAD

**Issue by Sergemozg** [Qiskit/qiskit#11846]
### Environment

- **Qiskit version**: 1.00
- **Python version**: 3.12.2
- **Operating system**: Windows 10

### What is happening?

Hi all! Can anybody help me?

I have a qasm-file and want to run (execute) it in python. I installed Qiskit 1.0.0, but got the error: cannot import name 'execute' from 'qiskit'.

### How can we reproduce the issue?

Here is my code:

from qiskit import QuantumCircuit, execute, Aer
import json

--- Creating a quantum circuit from a qasm file
circuit = QuantumCircuit.from_qasm_file('NAME.qasm')

--- Backend selection
backend = Aer.get_backend('qasm_simulator')

--- Executing the scheme on the selected backend
job = execute(circuit, backend, shots=1024)

--- Getting results
result = job.result().get_counts()
result_json = json.dumps(result)

print(result_json)

**Comment by Cryoris** [comment]
It seems you're using a bit an outdated snippet. The ``execute`` function has been removed in Qiskit 1.0 (see https://github.com/Qiskit/qiskit/pull/11565) after being deprecated in 0.46. The release notes (see https://docs.quantum.ibm.com/api/qiskit/release-notes/0.46#deprecation-notes) describe what you can use as replacement. Also, your example is using a legacy import of ``Aer``, which should now be import from ``qiskit_aer`` instead. 

Here's an updated version of your snippet
```python
from qiskit import QuantumCircuit
from qiskit_aer import Aer
import json

# Creating a quantum circuit from a qasm file
circuit = QuantumCircuit.from_qasm_file('NAME.qasm')

# Backend selection
backend = Aer.get_backend('qasm_simulator')

# Executing the scheme on the selected backend
job = backend.run(circuit, shots=1024)

# Getting results
result = job.result().get_counts()
result_json = json.dumps(result)

print(result_json)
```
Alternatively you could also use the ``Sampler`` primitive to execute the circuit.

**Comment by 1ucian0** [comment]
Alternatively, you can continue in the 0.* series (by installing `pip install qiskit==0.46`) which end-of-life is in August 2024.
