### ISSUE TITLE
API Docs Mistake: Wrong Primitive & Wrong subtitle

### ISSUE THREAD

**Issue by malteschade** [Qiskit/qiskit#11847]
### Environment

- **Qiskit version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

Two mistakes/typos in Qiskit primitives API docs: https://docs.quantum.ibm.com/api/qiskit/primitives

Mistake 1: 'sampler' should be 'estimator'
![2024-02-21 08 00 32-1](https://github.com/Qiskit/qiskit/assets/67964243/fb1fd220-b702-4220-9ce1-481d1f78eb44)

Mistake 2: 'Primitives V2' should be 'Estimator V2'
![2024-02-21 08 02 47 png-1](https://github.com/Qiskit/qiskit/assets/67964243/9e4a9bff-01ff-4865-9758-9d4bbc350d98)

### How can we reproduce the issue?

Read v1.0.0 Qiskit primitives API docs: https://docs.quantum.ibm.com/api/qiskit/primitives

### What should happen?

Mistakes should be there

**Comment by Raghav-Bell** [comment]
Pleas raise this issue at [Qiskit/documentation](https://github.com/Qiskit/documentation/issues) as all documentation shifted to that repo.
For this issue, changes should be made at [primitives.md](https://github.com/Qiskit/documentation/blob/main/docs/api/qiskit/primitives.md). Please assign this issue to me. Thanks

**Comment by atharva-satpute** [comment]
Can I take this up?

**Comment by t-imamichi** [comment]
I close this because they are both fixed now.
