### ISSUE TITLE
inconsistencies in the options for the drawer (circuit, and timeline)

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit#11858]
### What should we add?

When I was looking at visualizations for the timeline_drawer and the circuit_drawer it would be good to have both have the same options for the same thing. I.e idle_wires does not work in the timeline and it took me a while to figure out it is show_idle. 

To get both to work one use option show_idle and the other idle_wires it would be good to have both have the same name. 

`timeline_drawer(qc_ibm, show_idle=False)`
and 
`circuit_drawer(qc_ibm, idle_wires=False)`

my proposal is make it 

`timeline_drawer(qc_ibm, idle_wires=False)`
and 
`circuit_drawer(qc_ibm, idle_wires=False)`

**Comment by 1ucian0** [comment]
I agree with your proposal. Let's deprecate `timeline_drawer(..., show_idle=...)` in favor of `timeline_drawer(..., idle_wires =...)`.
