### ISSUE TITLE
add `graphviz` to the visualization tool dependency

### ISSUE THREAD

**Issue by haimeng-zhang** [Qiskit/qiskit#11865]
### Environment

- **Qiskit version**: 1.0.0
- **Python version**: 3.11.6
- **Operating system**: macOS

### What is happening?

When calling function `plot_circuit_layout` in the module `qiskit.visualization`, got the following error: 
```
MissingOptionalLibraryError: "The 'graphviz' library is required to use 'plot_coupling_map'. You can install it with ''brew install c' if on Mac, or by downloding it from their website'."
```

### How can we reproduce the issue?

A minimal working example
```
import numpy as np
from qiskit import QuantumCircuit
from qiskit_ibm_runtime.fake_provider import FakeSherbrooke
from qiskit import transpile
from qiskit.visualization import plot_circuit_layout
backend = FakeSherbrooke()
 
qc = QuantumCircuit(2, 1)
 
qc.h(0)
qc.x(1)
qc.cp(np.pi/4, 0, 1)
qc.h(0)
qc.measure([0], [0])
qc.draw(output='mpl')
qct = transpile(qc, backend)
plot_circuit_layout(qct, backend)
```

### What should happen?

Add the `graphviz` package to the `pyproject.toml` file for the `visualization` dependency under the section `[project.optional-dependencies]`.

**Comment by jakelishman** [comment]
The Python `graphviz` package is not the actual Graphviz executable, which is what's required - the error message should hopefully explain this.

**Comment by haimeng-zhang** [comment]
I see. In the case, it is desirable to add the `graphviz` [python wrapper ](https://pypi.org/project/graphviz/) to the `qiskit.visualization` dependency?

**Comment by jakelishman** [comment]
Not really, unfortunately - we don't use the Python wrapper from within Qiskit, and installing the wrapper doesn't install Graphviz, so it wouldn't really change the situation.  If you've got more helpful wording for the error that would make it more understandable, we could change that?
