### ISSUE TITLE
Collapse measurements when drawing

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit#11895]
### What should we add?

As circuits get larger, the measurements can take up a significant chunk of the displayed circuit, see e.g. this example from @ElePT 

![Screenshot 2024-02-26 at 14 53 03](https://github.com/Qiskit/qiskit/assets/5978796/01a30502-31e6-4951-8462-439a6cc90670)

It would be nice if our drawers could collapse such measurement blocks into a single-width instruction.

**Comment by jakelishman** [comment]
See also: #4149.

**Comment by Cryoris** [comment]
Ha I thought there was already one but I didn't find it anymore -- thanks!
