### ISSUE TITLE
dynamic circuit fail to transpile without a backend

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#11906]
### Environment

- **Qiskit version**: `1.1.0.dev0+afdd1b7`
- **Python version**: `3.11.7`
- **Operating system**: MacOS

### What is happening?

When transpiling a dynamic circuit without any backend, it fails with `The control-flow construct 'if_else' is not supported by the backend.`
This seems to be the backendless version of https://github.com/Qiskit/qiskit-ibm-runtime/issues/1253

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, transpile

q = QuantumRegister(1)
c = ClassicalRegister(1)
circuit = QuantumCircuit(q, c)
circuit.h(q)
circuit.measure(q, c)
with circuit.if_test((c, 1)):
    circuit.x(q)

transpile(circuit)
```
```
TranspilerError: "The control-flow construct 'if_else' is not supported by the backend."
```

### What should happen?

transpilation should work with dynamic circuits, just like the non-dynamic circuits:
```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, transpile

q = QuantumRegister(1)
c = ClassicalRegister(1)
circuit = QuantumCircuit(q, c)
circuit.h(q)
circuit.measure(q, c)

transpiled = transpile(circuit)
transpiled.draw('mpl')
```
<img width="245" src="https://github.com/Qiskit/qiskit/assets/766693/9f957908-d939-4743-a40a-fc2d04cd3ad7">

**Comment by jakelishman** [comment]
Whoops, looks like an oversight in the control-flow error check.  Something like #11907 should do the job.

**Comment by jakelishman** [comment]
Fwiw, the linked issue doesn't appear to be a problem with Terra (though could be related via #11877) - it seems like there are/were some backends in the IBM Runtime that weren't reporting their support for control-flow operations.

**Comment by 1ucian0** [comment]
wow! that's a quick fix! Thanks!
