### ISSUE TITLE
Qiskit 0.45.3 FakeBackendV2 reports 2 qubits for a 133Q device

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#11943]
### Environment

- **Qiskit version**: 0.45.3
- **Python version**: 3.12
- **Operating system**: any

### What is happening?

Because there is currently no Fake Torino system we have made our own for offline benchmarking:

```python
import os
try:
    from qiskit_ibm_runtime.fake_provider.fake_backend import FakeBackendV2
except ImportError:
    from qiskit.providers.fake_provider import FakeBackendV2

class FakeTorino(FakeBackendV2):
    """A fake 133 qubit backend."""

    dirname = os.path.dirname(__file__)  # type: ignore
    conf_filename = "conf_torino.json"  # type: ignore
    props_filename = "props_torino.json"  # type: ignore
    backend_name = "fake_torino"  # type: ignore
```

When using `FakeBackendV2` from the Runtime everything works.  However, using the same class from the old fake provider results in a target consisting of only 2 qubits.

The loaded files are in the Benchpress repo.

### How can we reproduce the issue?

Run the above.

### What should happen?

I should be able to load a FakeBakendV2 from older versions of Qiskit for benchmarking purposes.

**Comment by jakelishman** [comment]
For some reason, Qiskit <1.0 had two `FakeBackendV2` classes.  The one that implements the logic you're expecting here is in `qiskit.providers.fake_provider.fake_backend`, and isn't imported into the `qiskit.providers.fake_provider` root.  Hopefully switching the import should cause it to work for you.

**Comment by nonhermitian** [comment]
Haha, yep that fixes it.  Thanks!
