### ISSUE TITLE
Meaningless Circuit with `c_if` used in test case

### ISSUE THREAD

**Issue by MattePalte** [Qiskit/qiskit#11950]
### Environment

- **qiskit.__version__**: 0.45.2
- **Python version**: 3.10.12
- **Operating system**: Ubuntu 20.04

### What is happening?

In the Python file [test_circuit_methods.py](https://github.com/Qiskit/qiskit/blob/main/test/python/qasm2/test_circuit_methods.py#L190) the circuit created in the test case is not very meaningful, the `c_if` gate is never triggered because the condition is always `False`.

https://github.com/Qiskit/qiskit/blob/f4b50fbb2d3fe7871589fae898f6eadbad7c959b/test/python/qasm2/test_circuit_methods.py#L190

### How can we reproduce the issue?

Run the following code in the Python file:

```python
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from qiskit import execute, Aer
qr = QuantumRegister(1, "q")
cr0 = ClassicalRegister(4, "c0")
cr1 = ClassicalRegister(4, "c1")
ref = QuantumCircuit(qr, cr0, cr1)
ref.x(qr[0])
ref.x(qr[0]).c_if(cr1, 4)
ref.measure(qr[0], cr0[0])
backend = Aer.get_backend('qasm_simulator')
counts = execute(ref, backend).result().get_counts()
print(counts)
```
Output:
```
{'0000 0001': 1024}
```
The `c_if` gate is never triggered because the condition is always `False`.

### What should happen?

I would have expected the `c_if` gate to be triggered in some cases.

### Any suggestions?

I know that this is only a test checking another feature, however I believe having a realistic circuit would be better. What about replacing the gate with an hadamard gate and a `c_if` condition to check its result?

```python
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from qiskit import execute, Aer
qr = QuantumRegister(1, "q")
cr0 = ClassicalRegister(4, "c0")
cr1 = ClassicalRegister(4, "c1")
ref = QuantumCircuit(qr, cr0, cr1)
ref.h(qr[0])
ref.x(qr[0]).c_if(cr1, 1)
ref.measure(qr[0], cr0[0])
backend = Aer.get_backend('qasm_simulator')
counts = execute(ref, backend).result().get_counts()
print(counts)
```
Output:
```
{'0000 0000': 507, '0000 0001': 517}
```

Thanks in advance, I wish you a happy and productive day.

**Comment by jakelishman** [comment]
We're not testing the execution here, we're testing the structure of the import from the OpenQASM 2 file.  It doesn't matter what the circuit does at all, only that that conditional gets faithfully represented in the Qiskit result.  We want all valid circuits to work there - we don't necessarily want to only test cases that we deem are useful circuits, because you never know what a user might want/need.

**Comment by MattePalte** [comment]
Make sense, I imagined the answer, I guess these other cases are the same:
- https://github.com/Qiskit/qiskit/blob/f4b50fbb2d3fe7871589fae898f6eadbad7c959b/test/python/circuit/test_circuit_qasm.py#L33
- https://github.com/Qiskit/qiskit/blob/f4b50fbb2d3fe7871589fae898f6eadbad7c959b/test/python/transpiler/test_decompose.py#L115
- https://github.com/Qiskit/qiskit/blob/f4b50fbb2d3fe7871589fae898f6eadbad7c959b/test/python/qasm2/test_structure.py#L264

**Comment by jakelishman** [comment]
The first and third are OpenQASM 2 tests in the exact same vein, yeah.  The second is a bit different, but it's the same sort of thing: we wouldn't want an unrelated operation to do things like "tidy up" conditionals, so I think it's fine to include them in tests.

(Fwiw, there's probably hundreds of "useless" circuits throughout the test suite - it's often better to strip a lot of the extraneous stuff from a test circuit, so we can test the specific bits we're aiming at in the unit test.  Things like the transpiler test module have some larger integration tests.)

**Comment by MattePalte** [comment]
It makes sense, thanks for the very fast and precise feedback @jakelishman

**Comment by 1ucian0** [comment]
It seems to me this issue can be closed as the original request was explained. Feel free to reopen if that's not the case.
