### ISSUE TITLE
Add function to remove inactive qubits from circuit

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit#11970]
### What should we add?

This is a common task, and having it in qiskit would remove the need for everyone to define their own version. mapomatic has it as `deflate_circuit`: https://github.com/qiskit-community/mapomatic/blob/7d4d923cccf404e036c3622ee88c4634584a70e0/mapomatic/circuits.py#L19

**Comment by jakelishman** [comment]
For simple non-dynamic circuits (things get rather more complicated if we need to handle registers), your own `QuantumCircuit.from_instructions(qc)` will automatically do this - `QuantumCircuit` is itself an iterable of `CircuitInstruction`, and that method deliberately only uses the qubit/clbit instances encountered in the instructions - the active ones.

That said, what situations do you have that needs this, especially commonly?  Mapomatic is doing something quite specialised here, and stripping down a physical circuit back to an abstract one so it can be re-laid out again, and making quite a lot of assumptions about the input circuit (e.g. delays weren't intended, barriers weren't intended, there's no control-flow, etc).  Anything we do would need to have quite a complex "configuration" API to determine "what counts as active?", or boil down to something very close to `QuantumCircuit.from_instructions(instr for instr in qc if filter_fn(instr))` for some user-given `filter_fn`.

**Comment by kevinsung** [comment]
I hadn't thought of `QuantumCircuit.from_instructions(qc)`. That's very nice, thanks! It serves my purposes.
