### ISSUE TITLE
DAG `node._node_id` should be public

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#11987]
### What should we add?

I am not sure why the node id of a node in a DAG is private.  It is useful to have as a public attribute.

**Comment by jakelishman** [comment]
_In theory_, the underlying graph object of `DAGCircuit` is private, so there was no expected use from getting indices into a graph that you can't access, and all the methods on `DAGCircuit` should take `DAGNode`s.  What were you planning to do with the indices?

**Comment by nonhermitian** [comment]
I need to track a collection of nodes along with some data. Right now I am using a dict with node id as the key

**Comment by nonhermitian** [comment]
Will close as having a node as a key gives the same result.
