### ISSUE TITLE
Pip information missing home-page and author information for Qiskit 1.0.2

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit#11985]
### Environment

- **Qiskit version**: 1.0.2
- **Python version**: 3.10
- **Operating system**: macOS 14.2.1

### What is happening?

Pip information missing home-page and author information when running `pip show qiskit` command.

<img width="1144" alt="Screenshot 2024-03-11 at 12 23 01" src="https://github.com/Qiskit/qiskit/assets/7631333/658e8ed8-f3b7-4643-9e55-ba5d60ee8562">

### How can we reproduce the issue?

* Install qiskit 1.0
* Run `pip show qiskit`

### What should happen?

It should show the link to home page which is now (?) https://docs.quantum.ibm.com/ and author should be "Qiskit Development Team" like in qiskit 0.46.1

<img width="535" alt="Screenshot 2024-03-11 at 12 22 37" src="https://github.com/Qiskit/qiskit/assets/7631333/d5340eed-b41b-47a2-b136-3cf20026f2ba">

**Comment by jakelishman** [comment]
The author information and home page aren't really missing (and going to https://pypi.org/project/qiskit will show they're being properly interpreted), I think it's just a bit of a mismatch when mapping the more descriptive form that Qiskit now uses for packaging onto PyPA metadata format that predates it.

You can see in `Author-Email` that we do supply a full name and email in the preferred format, and we supply `Home-Page` in `Project-URLs` now (try `pip show -v qiskit`).

The older metadata format has special fields for `Home-Page` and `Author`, but when we swapped to the recommended structure of using `pyproject.toml`, which has a far more descriptive configuration than the legacy distutils/setuptools-fixed format, it doesn't automatically backfill those fields.  Fwiw, this is the same behaviour as `pip` itself:

```bash
pip show pip
```
```
Name: pip
Version: 24.0
Summary: The PyPA recommended tool for installing Python packages.
Home-page: 
Author: 
Author-email: The pip developers <distutils-sig@python.org>
License: MIT
Location: /Users/jake/code/qiskit/venv310/lib/python3.10/site-packages
Requires: 
Required-by: pip-tools
```

**Comment by HuangJunye** [comment]
That's very interesting. Thanks for the detailed explanation. pip 23.1 still shows home-page and author fields but 24.0 as you indicated has same behaviour as Qiskit. So this is rather a bug for pip.

**Comment by jakelishman** [comment]
Yeah, looks like pip just changed super recently: pypa/pip#11909.

**Comment by jakelishman** [comment]
I wouldn't call it a bug, but if anything, it'd be setuptools, because it's about whether the underlying metadata fields are filled or not.  But we don't fill `Author` or `Home-Page` any more; we use the more descriptive full sets of fields (`Author-Email` and `Project-URLs`) and abide by their conventions.  Pip's reporting the "standard" set of metadata which is a bit old now, and I'd imagine that if they changed the default behaviour of `pip show`, they'd break things that parsed its output.
