### ISSUE TITLE
Add `SXGate` to supported gates in `TwoLocal` circuits

### ISSUE THREAD

**Issue by samanthavbarron** [Qiskit/qiskit#12002]
### What should we add?

A common decomposition of single qubit gates is `Rz-Sx-Rz-Sx-Rz`, therefore it would be nice to support `SXGate`s in the `TwoLocal` circuit rotation gates.

https://github.com/Qiskit/qiskit/blob/230e91cb810de8f3911fa1958815fe8ed25c9980/qiskit/circuit/library/n_local/two_local.py#L276

**Comment by jakelishman** [comment]
Thanks for the report - I think that code block is a bit out of date, and likely just wants updating to use `qiskit.circuit.library.get_standard_gate_mapping`, which is the complete dictionary of how to construct all those gates with their parameters.  That would automatically make `sx` available as a valid gate, whereas here it looks like an oversight that it's been missed.
