### ISSUE TITLE
SamplerV2Converter for converting SamplerV1 to SamplerV2

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#12047]
### What should we add?

Converter tool for SamplerV1 to SamplerV2 to help the transition. Users need a single workflow (using V2) while waiting for primitive implementors transitioning.

This is a followup on https://github.com/Qiskit/qiskit/pull/11899#issuecomment-2009228813

**Comment by t-imamichi** [comment]
It's technically impossible because SamplerV2 (list of bitstrings, i.e., `memory=True`) requires more information than SamplerV1 (quasi-distribution of bitstrings).
