### ISSUE TITLE
Addition of ctrl_state Parameter to mcx() Function

### ISSUE THREAD

**Issue by elucidator8918** [Qiskit/qiskit#12044]
### Feature Description

Currently, the mcx function in the quantum circuit library lacks a ctrl_state parameter, which limits its flexibility in certain use cases. This feature request proposes the addition of a ctrl_state parameter to the mcx function, similar to what is present in the ch and cy functions.

### Proposed Change:
Modify the mcx function to include a ctrl_state parameter, allowing users to specify the control state of the multi-controlled X gate. This parameter should accept either a decimal value or a bitstring (e.g., '1') and default to controlling the '1' state if not provided.

### Expected Behavior:
Upon calling the mcx function, users can pass the ctrl_state parameter to specify the control state for the multi-controlled X gate. This parameter will enhance the functionality and flexibility of the function, enabling users to perform more complex quantum operations.

### Implementation Details:
The mcx function should be modified to accept the ctrl_state parameter. This parameter should then be passed to the appropriate gate implementation for constructing the multi-controlled X gate.

**Comment by ShellyGarion** [comment]
@elucidator8918 - this is a good suggestion. Would you like to be assigned for this issue?
also note that the same holds for the `mcp()` function, as well as the `MCPhaseGate`, see #11386

**Comment by elucidator8918** [comment]
@ShellyGarion Yes I would like to be assigned this issue. For the ```mcp()``` function as well as the MCPhaseGate, I looked into the issue and I would like to work on it separately to this issue after resolving this issue :)

**Comment by ShellyGarion** [comment]
@elucidator8918 - I've assigned you to this issue. When you open a PR, please tag me.
In the meanwhile, I'm checking the status of PR https://github.com/Qiskit/qiskit/pull/11386.
