### ISSUE TITLE
SamplerV2 does not support `get_[int_]counts` across all registers

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit#12063]
### What should we add?

SamplerV2 exposes each individual register's results as a `BitArray`.  `BitArray` then contains methods `get_counts` and `get_int_counts` to use if one wants to deal with outcomes as a dictionary of counts.

However, this is of limited utility if the output bits are spread among multiple classical output registers.  The reason is that typically each unique outcome should be considered over all bits, else covariance information is lost.  For example, if I prepare a Bell state and measure the qubits into two single-bit classical registers, then the individual `get_counts()` of each register would not even provide evidence that it is any different from a classical mixture.

```python
from qiskit.circuit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.primitives import BackendSamplerV2
from qiskit_aer import AerSimulator

q = QuantumRegister(2, "q")
c1 = ClassicalRegister(1, "c1")
c2 = ClassicalRegister(1, "c2")
qc = QuantumCircuit(q, c1, c2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])

backend = AerSimulator()
sampler = BackendSamplerV2(backend=backend)
result = sampler.run([qc], shots=20).result()

print("c1 counts: ", result[0].data.c1.get_counts())
print("c2 counts: ", result[0].data.c2.get_counts())
```

```
c1 counts:  {'0': 9, '1': 11}
c2 counts:  {'0': 9, '1': 11}
```

It would be great to have a way of consolidating all unique outcomes across _all_ registers into a counts dictionary.

**Comment by jsaroni** [comment]
I guess the old `backend.run` method should give the counts output across all registers
```
from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator

backend = AerSimulator()
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0,1)
qc.measure_all()
job = backend.run(qc)
result = job.result()
counts = result.get_counts()

print(counts)
```

**Comment by garrison** [comment]
The workaround I've been using the qiskit-addon-cutting is to process each outcome individually instead of relying on an aggregated counts dictionary ([code here](https://github.com/Qiskit/qiskit-addon-cutting/blob/5175a7cd0d2c6d803a9e92b09521d61e5b3841c5/qiskit_addon_cutting/cutting_reconstruction.py#L152-L162)).

**Comment by t-imamichi** [comment]
Does `join_data` helps it?
https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.SamplerPubResult#join_data

```python
print("joined counts: ", result[0].join_data().get_counts())
```

```
joined counts:  {'00': 11, '11': 9}
```

**Comment by garrison** [comment]
> Does `join_data` helps it?

It looks like it is exactly what I am looking for.  In that case, #12143 could have been marked as closing this issue 🙂.
