### ISSUE TITLE
Spellcheck API docs (Unity Fund Hackathon) 

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit#12067]
This is part of https://github.com/Qiskit/documentation/issues/818. We still have to decide in that ticket what we long-term with spellchecking the API docs in qiskit/qiskit. In the meantime, it is valuable to fix all current spelling violations.

To do this:

1. Clone https://github.com/Qiskit/documentation
2. Edit the cspell config at https://github.com/Qiskit/documentation/blob/b7737fb4f8e7c0483a8e0af0ed62c59c828720c9/cspell/cSpell.json#L51 to not ignore `/api/qiskit/dev`, but we still want to ignore the other `api/qiskit` folders like `/api/qiskit/0.*/*.mdx` and `/api/qiskit/*.mdx` (current docs)
3. Run cspell with the instructions at https://github.com/Qiskit/documentation#spellcheck
4. Fix the spelling violations in a PR in this repository. It's plausible there will be legit words/phrases that are not issues. Those should instead be added to the dictionaries in qiskit/documentation as valid words (see the section "Fixing false positives")

It's best to keep these changes in one PR, rather than opening up a bunch of tiny PRs.

**Comment by Raghav-Bell** [comment]
I would like to work on this issue. Kindly please assign this issue to me. Thanks

**Comment by 1ucian0** [comment]
hi @Raghav-Bell , we are setting some issues (like this one) for coming events. Let's hold it for now :)

**Comment by CRTejaswi** [comment]
Hi, @Eric-Arellano @1ucian0 !
I'd like to work on this issue as a part of unitaryhack.

**Comment by 1ucian0** [comment]
sure thing @CRTejaswi ! Because the nature of the event, go ahead and PR it. The first/best PR can get the bounty (or could be shared if they complement).

**Comment by CRTejaswi** [comment]
> sure thing @CRTejaswi ! Because the nature of the event, go ahead and PR it. The first/best PR can get the bounty (or could be shared if they complement).

Are EN-UK words to be treated as spelling mistakes (hence corrected)?
eg. organised, behaviour (vs organized, behavior in EN-US)

**Comment by Eric-Arellano** [comment]
> Are EN-UK words to be treated as spelling mistakes (hence corrected)?

Yes, please. We use EN-US for consistency.

**Comment by CRTejaswi** [comment]
Minor Update: Of the 25k identified spelling issues (non-unique), I've added most false positives to respective dictionaries, and fixed common typos (eg. neighbour/visualisation/...) through simple scripting. I'm taking a few hours off to rest, and will finish & update you once my cspell output is error-free.

**Comment by Eric-Arellano** [comment]
Thanks, @CRTejaswi! 

~Any other Unitary Fund Hackathon people interested in this issue, please wait to get started on this ticket until @CRTejaswi has had some more time to finish. We want to respect how much time they've already put into this ticket and avoid duplicate work.~ Update: I misunderstood how the hackathon is intended to work, and it's still fair game for others to contribute.

**Comment by CRTejaswi** [comment]
I apologise for the delay. I've been occupied with some work, so, couldn't finish up. Will do shortly.

**Comment by Eric-Arellano** [comment]
All good, @CRTejaswi. By the way, in case it wasn't already clear, the fixes will need to happen in this repo qiskit/qiskit, not qiskit/documentation. That's because the docs are generated from qiskit/qiskit, so it's the "source of truth".

**Comment by 1ucian0** [comment]
just few remainders to everyone:
 * this is is closed by PRing [Qiskit/qiskit](https://github.com/Qiskit/qiskit), not [Qiskit/documentation](https://github.com/Qiskit/documentation) :)
 * more than one PR can be submitted and even accepted (in case they complement each other)
 * the bounty will be decided based on when it was submitted, how much hand holding required, and how complete it is. It can even be split amount submitters.

**Comment by ljcamargo** [comment]
@1ucian0 ok then, here is the PR on Qiskit/qiskit https://github.com/Qiskit/qiskit/pull/12501

**Comment by ljcamargo** [comment]
hello @1ucian0 I guess the owner has to do some checks before the PR to be merged, but I guess my job is done. Let me know to consider this bounty is achieved, thanks!

**Comment by 1ucian0** [comment]
You need to address the comments and conflicts in [the PR](https://github.com/Qiskit/qiskit/pull/12564). The bounty will be assigned to you after that. The issue will be crossed out from the website once this issue is closed (because the PR was merged)

**Comment by ljcamargo** [comment]
hi @1ucian0 I resolved the conflict, I think there is no other comment for me, let me know is something else is missing
