### ISSUE TITLE
typos in `TranspileLayout` methods' docstrings

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit#12064]
### Environment

- **Qiskit version**: 1.0.2
- **Python version**: n/a
- **Operating system**: n/a

### What is happening?

Typos in the docstrings of two `TranspileLayout` methods, where the explanation of each example has a couple of typo'ed qubit indices. One references qubit 3, which can't exist in a 3-qubit circuit, and the other is missing the number altogether. Should be straightforward to fix.

https://github.com/Qiskit/qiskit/blob/f713c78c28d7d9adad60882be9515bcf95eccbeb/qiskit/transpiler/layout.py#L569-L575

https://github.com/Qiskit/qiskit/blob/f713c78c28d7d9adad60882be9515bcf95eccbeb/qiskit/transpiler/layout.py#L635-L645

### How can we reproduce the issue?

See docs

### What should happen?

Fix typos

**Comment by qiaoyi213** [comment]
I'm interested in this issue, could I work on it?

**Comment by alexanderivrii** [comment]
I have been looking at the `TranspileLayout` explanations earlier this week and also noticed these and a few other inaccuracies. I have pushed a small PR with a few improvements (I hope).

**Comment by alexanderivrii** [comment]
@qiaoyi213, sorry, I did not see your request to work on this issue, I absolutely did not know about it when trying to understand the `TranspileLayout` code. Having said that, I believe the documentation can be considerably additionally improved, is this something that you would be still interested to look into?

**Comment by qiaoyi213** [comment]
@alexanderivrii  It's great if you already fix this issue. I would find other thing to work. Thanks.
