### ISSUE TITLE
justify keyword arg in circuit draw does not raise on bad input

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#12089]
### Environment

- **Qiskit version**:  latest
- **Python version**: 
- **Operating system**: 

### What is happening?

`justify` will not raise on bogus inputs, e.g.

```python
qc.draw('mpl',justify='midldsfasdfse')
```

### How can we reproduce the issue?

Try above

### What should happen?

Bad inputs should raise rather than default implicitly

**Comment by Waliur003** [comment]
I want to solve this... Can you make me an assignee, Please?

**Comment by jakelishman** [comment]
Sure, thanks!

**Comment by GuillermoAbadLopez** [comment]
@jakelishman I see this was not tackled in the end, right? Do you still want to implement it?

If so, could you reassign it to me? Thanks! 🙌

**Comment by GuillermoAbadLopez** [comment]
Now that the [PR #12458](https://github.com/Qiskit/qiskit/pull/12458) is merged 🚀🚀:

Should we wait for the full deprecation cycle (raising error), to close the Issue? Or would you close it already? 
For me do as you consider 👍

----
@1ucian0, @Eric-Arellano @kevinsung

**Comment by 1ucian0** [comment]
It can be closed I think. Thanks!
