### ISSUE TITLE
Adding conjugated state preparation <0|, <1| ?

### ISSUE THREAD

**Issue by JarekDuda** [Qiskit/qiskit#12110]
### What should we add?

Hello,
I am working on two-way quantum computers (2WQC, https://arxiv.org/pdf/2308.13522) - extension adding conjugated state preparation: <0|, <1|.

For physical realization it needs to prepare a situation, such that looking from T/CPT symmetry perspective, we get the process used for state preparation - what seems realizable e.g. for silicon quantum dots below (e.g. https://www.nature.com/articles/s41467-020-20280-3 ), just using reversed impulse after.

As I believe it is a matter of time they will reach mainstream, I wanted to ask if <0|, <1| could be added to Qiskit?
Like in the diagram below, for current state it needs to multiply the qubits on the chosen positions, and then normalize the state.

![silicon](https://github.com/sw1sh/QuantumFramework/assets/6699208/12a1a01e-dd40-48ff-889e-f1e9e12cf7e9)

**Comment by jakelishman** [comment]
I'm not 100% sure I understand the ask, here.  $\langle 0\rvert$ isn't a point in state space, so it doesn't appear to make sense to me for it to have a preparation raw in the circuit model of computation, and Qiskit is primarily about the circuit model.

You can get a circuit that represents the adjoint of some isometry $\lvert0\rangle \to \lvert\psi\rangle$ by using `StatePreparation` and taking its `inverse`, but since `StatePreparation` of course represents an operator taking state space to itself, the result will still be an operator on the same space.

If you're just talking about the `quantum_info` module, I'm not sure there's enough motivation here - again, Qiskit's components are in support of the circuit model of computation.  You might want to look at a more general-purpose linear-algebra library like [QuTiP](https://github.com/qutip/qutip) for that, which _does_ already come with a built-in way of representing and working with the dual space.

**Comment by JarekDuda** [comment]
Hello, while this operation is not available in the current quantum circuits, there are many arguments it should be in near future.

For example for above QC based of silicon quantum dots, using electric impulse for state preparation - just use the opposite impulse at the end of the process, and from perspective of CPT symmetry it becomes the original state preparation. 

Or below for photonic QC - which uses laser impulse for state preparation. Using unidirectional ring laser as below, from perspective of CPT symmetry we perform analogous state preparation on the original final state.

Adding this missing operation to make their set CPT symmetric as physics is believed to be ( https://en.wikipedia.org/wiki/CPT_symmetry ), interested people would start working on better understanding of its consequences - improvements to the known algorithms, and search for new ones - hopefully to be realized in hardware in a few years.

This operation brings new model of quantum computation, similar but slightly different than postselection e.g. in postBQP, requiring more symmetric way of thinking (as unitary evolution is) - even if unsuccessful for realization, might bring new ideas, algorithms, and more attention/citations for Qiskit ... from looking simple and natural addition.

![2WQC](https://github.com/Qiskit/qiskit/assets/6699208/85105224-6a99-4162-a1fe-437c44dd575e)

**Comment by jakelishman** [comment]
> just use the opposite impulse at the end of the process, and from perspective of CPT symmetry it becomes the original state preparation.

Unitary operators are reversible, and Qiskit's method of representing the reverse action of a unitary operator is the `Gate.inverse` method. You can use this on the `StatePreparation` object I mentioned before to represent the inverse state-preparation operation, which could be represented in hardware, as you say, by some inverted laser sequence.

Perhaps you might find it easier to write an extension Python package to Qiskit somewhere that adds the functionality you are thinking of. At any rate, I don't believe there's anything in this ask that is sufficiently notable yet to be suitable for the core library.

**Comment by JarekDuda** [comment]
Indeed unitary operations are reversible, but the boundary treatment is not - in the beginnings of quantum computation there was arbitrarily assumed possibility of state preparation, but forgetting about its symmetric counterpart - which existence is required by CPT symmetry, and it seems relatively straightforward to physically realize e.g. for silicon quantum dots ... 

And new possibilities it brings in theory allow for much more powerful next generation of quantum computers - but for that we need to use both: apply boundary treatment simultaneously from both directions.

Thank you for your suggestions, we will think about it. Maybe please don't close this issue - high demand to add it to the core library is a matter of time.

**Comment by jakelishman** [comment]
If there is wide-scale interest in the future, we can discuss more. For now, I will close the issue.

**Comment by JarekDuda** [comment]
Turns out in Wolfram QuantumFramework <0|, <1| just works out-of-the box:

![Zrzut ekranu 2024-04-09 174647](https://github.com/sw1sh/QuantumFramework/assets/6699208/9524421a-0327-4792-8f68-5014e1e1f7c8)
