### ISSUE TITLE
Port `synth_clifford_ag` to Rust

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#12233]

**Comment by ShellyGarion** [comment]
I think that this algorithms has been superseded by `synth_clifford_greedy` which has better CX count and depth, so I don't think it's worth to transfer it to rust, and perhaps it can be deprecated.

**Comment by mtreinish** [comment]
Ok sure, I just went through everything in the synthesis module to open these issues. If this function isn't useful anymore then I'll close this issue and can you open a separate one to track deprecating and removing it instead?
