### ISSUE TITLE
Port `StarPrerouting` to Rust

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#12337]
This PR can be started now and partially completed before #11721 and #12205 as it only does structural analysis and inserts swaps. We can leverage the existing mechanisms used for `SabreLayout` and `SabreSwap` in rust currently to do this. To full mark this issue as complete we will need #11721 and #12205 so that the pass can operate solely in rust, but as a first step this isn't blocked.

**Comment by henryzou50** [comment]
I am interested!
