### ISSUE TITLE
EfficientSU2 should support specifying two-qubit gate

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit#12342]
### What should we add?

Currently, [EfficientSU2](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.EfficientSU2#efficientsu2) always uses CX gates for the entangling layers. It should let the user specify which gate to use. This can be implemented by adding an argument
```python
entangling_gate: str | Instruction
```

**Comment by ShellyGarion** [comment]
I think that the [`TwoLocal`](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.TwoLocal) class should support any 2-qubit gate, and  [`EfficientSU2`](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.EfficientSU2) is a special case for using only `CX` gates. Could you please check this ?

**Comment by kevinsung** [comment]
Yes, you're right. Thank you!
