### ISSUE TITLE
SamplerResult

### ISSUE THREAD

**Issue by eggjpeg** [Qiskit/qiskit#12404]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.SamplerResult

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

The sampler returns a PrimitiveResult type not a SamplerResult type, this seems outdated.

**Comment by t-imamichi** [comment]
SamplerV1 returns SamplerResult while SamplerV2 returns PrimitiveResult.
When we introduced SamplerV2, we had to update to the page to clarify it's SamplerV1.
SamplerResult will be deprecated #12575

**Comment by t-imamichi** [comment]
Fixed by #12575
