### ISSUE TITLE
Some Syntax errors in the Primitives Sampler V2 docs

### ISSUE THREAD

**Issue by sahilohe** [Qiskit/qiskit#12452]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit/primitives#overview-of-samplerv2
![Screenshot from 2024-05-21 13-32-13](https://github.com/Qiskit/documentation/assets/31381367/bf6751ed-78e7-4b5a-9348-b112de6dbfa0)

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

Found some syntax errors in the Sampler example code. Two extra and one missing ')'

Corrected code (with no comments)
`
from qiskit.primitives import StatevectorSampler as Sampler
from qiskit import QuantumCircuit
from qiskit.circuit.library import RealAmplitudes
 
bell = QuantumCircuit(2)
bell.h(0)
bell.cx(0, 1)
bell.measure_all()

pqc = RealAmplitudes(num_qubits=2, reps=2)
pqc.measure_all()
pqc2 = RealAmplitudes(num_qubits=2, reps=3)
pqc2.measure_all()
 
theta1 = [0, 1, 1, 2, 3, 5]
theta2 = [0, 1, 2, 3, 4, 5, 6, 7]
 
sampler = Sampler()
 
job = sampler.run([bell], shots=128)
job_result = job.result()
print(f"The primitive-job finished with result {job_result}")

job2 = sampler.run([(pqc, theta1), (pqc2, theta2)])
job_result = job2.result()
print(f"The primitive-job finished with result {job_result}")

`

**Comment by jschuhmac** [comment]
Fixed in https://github.com/Qiskit/qiskit/pull/12587
