### ISSUE TITLE
Setting layout_method='noise_adaptive' fails in generate preset passmanager

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#12465]
### Environment

- **Qiskit version**: 1.1
- **Python version**: 
- **Operating system**: 

### What is happening?

```python
pm = generate_preset_pass_manager(backend=backend,
                                  optimization_level=3,
                                  layout_method='noise_adaptive')
```

TranspilerError: 'Invalid plugin name noise_adaptive for stage layout'

but the docs say I can do it here https://docs.quantum.ibm.com/api/qiskit/0.43/qiskit.transpiler.preset_passmanagers.generate_preset_pass_manager

### How can we reproduce the issue?

run above 

### What should happen?

it should work

**Comment by mtreinish** [comment]
The noise adaptive layout method was removed in qiskit 1.0. The docs you linked were from qiskit 0.43 when it was a valid option.

**Comment by nonhermitian** [comment]
Yeah, I just noticed that I was taken to a old version of the docs in the search.  Thanks
