### ISSUE TITLE
final_measurement_mapping function in qiskit.primitive.utils.py does not work properly with mid-circuit measurements

### ISSUE THREAD

**Issue by StS-Ph** [Qiskit/qiskit#12492]
### Environment

- **Qiskit version**: 0.45.1 and 1.0.0
- **Python version**: 3.9.12
- **Operating system**: MacOS 13.6.7

### What is happening?

The `final_measurement_mapping` function in `qiskit.primitives.utils.py` creates an  errorous mapping between measured qubits and classical bits if the considered circuit uses mid-circuit measurements. Specifcally, if one qubit is measured twice in the circuit (outcome mapped to different classical bits), only the last measurement is considered the mapping because the `final_measurement_mapping` function does not consider already meaasured qubits any further.

This results in unexpected errors when trying to run the circuit, e.g., with the sampler primitive from qiskit-aer.

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit
from qiskit.primitives.utils import final_measurement_mapping

# create minimal example circuit
c = QuantumCircuit(1,2)
c.h(0)
c.measure(0,0)
c.h(1)
c.measure(0,1)

# create measurement mapping using qiskit.primitives.utils. returns {0: 1}
map = final_measurement_mapping(c)
print("result from final_measurement_mapping function: {}".format(map))

print("expected outcome: {0: (0,1)}")
```

### What should happen?

From the above code example the `final_measurement_mapping` function outputs the dictionary {0: 1}. 
The first measurement, where the outcome is mapped to classical bit 0 is not considered. 

### Any suggestions?

From the function decription the expected output should consider all measurements, including mid-circuit measurements. 
The dictionary should thus have a list as its values carrying all classical bits to which measurement outcomes of the qubit where mapped.

**Comment by nonhermitian** [comment]
I believe this can be solved by using the M3 version that does account for mid-circuit measurements: https://github.com/Qiskit-Extensions/mthree/blob/30d35d03b2a4ffdd9c4d0a29299dd41a683f5a84/mthree/utils.py#L52

**Comment by t-imamichi** [comment]
`final_measurement_mapping` will be deprecated #12575. I suggest migrating to the M3 version.

**Comment by t-imamichi** [comment]
I close this because the function is deprecated #12575.
