### ISSUE TITLE
Deprecate v1 primitives

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit#12497]
### What should we add?

We should have deprecated V1 primitives in Qiskit 1.1, given its replacement (v2) had co-existed for 1 minor release. We should make sure it's deprecated in 1.2. 

cc @t-imamichi, @ihincks

**Comment by 1ucian0** [comment]
related to https://github.com/Qiskit/qiskit/pull/11490

**Comment by 1ucian0** [comment]
I'm putting this PR `on hold` as there are still open conversations on if or how are we going to do this.

**Comment by 1ucian0** [comment]
After some off line conversations, we agree too:
 * Deprecate the Interface type aliases `qiskit.primitives.BaseEstimator` (while leaving `qiskit.primitives.BaseEstimatorV1`). The recommendation is to use `qiskit.primitives.BaseEstimatorV2` directly.
 * Deprecate the Interface type aliases `qiskit.primitives.BaseSampler` (while leaving `qiskit.primitives.BaseSamplerV1`). The recommendation is to use `qiskit.primitives.BaseEstimatorV2` directly.
 * Deprecate `qiskit.primitives.Estimator` as reference implementation. The recommendation is to use `qiskit.primitives.EstimatorV2` directly. 
 * Deprecate `qiskit.primitives.Sampler` as reference implementation. The recommendation is to use `qiskit.primitives.SamplerV2` directly. 
 * Deprecate `qiskit.primitives.backend_estimator.BackendEstimator` as a tool. The recommendation is to use `qiskit.primitives.BackendEstimatorV2` directly. 
 * Deprecate `qiskit.primitives.backend_estimator.BackendSampler` as a tool. The recommendation is to use `qiskit.primitives.BackendSamplerV2` directly.

**Comment by t-imamichi** [comment]
How about other items in the PR https://github.com/Qiskit/qiskit/pull/12575#issue-2352107004, e.g., `BasePrimitivesResult `, `EstimatorResult`, and `SamplerResult`? They are used for only EstimatorV1 and SamplerV1 while V2 uses PubResult and SamplerPubResult.

`BasePrimitives` is a base class of `BaseSamplerV1` and `BaseEstimatorV1`.

**Comment by ElePT** [comment]
Given that `BasePrimitives` is not part of the deprecation (according to @1ucian0's message), I think it would make sense not to deprecate `BasePrimitivesResult`. 

For `EstimatorResult` and `SamplerResult`, they are documented as the result types for the run method of `BaserSamplerV1`/`BaseEstimatorV1`, so I see a point for keeping them. Especially if we want to avoid breaking external implementations of the V1 interface (which I think is why the Base interface should be kept). However, I see how the names can lead to confusion. Would it make sense to "rename" them to `SamplerV1Result` or `SamplerResultV1`/ `EstimatorV1Result` or `EstimatorResultV1` and deprecate the non-V1 name? In practice, we could deprecate the class and introduce a new type alias that doesn't raise a warning. This is however, this is still a breaking change, so I am not 100% sure it's the right way to go. The safest way would be keeping and not renaming them.

**Comment by t-imamichi** [comment]
Sorry, I misunderstood `BasePrimitiveResult` status. It's already deprecated #11054 at 0.46 (renamed as a private class `_BasePrimitiveResult`) and `BasePrimitiveResult` was removed #11576 at 1.0. We need to decide when we remove `_BasePrimitiveResult`.

**Comment by t-imamichi** [comment]
I have a concern to rename `SamplerResult` and `EstimatorResult` because it's a breaking change. I updated the docstrings to clarify that they are for V1 https://github.com/Qiskit/qiskit/pull/12575/commits/0b66c6a71b25fe19fd8c6e70e1607452db085104. How about this approach?
