### ISSUE TITLE
Bug when using pulse draw with backend set up

### ISSUE THREAD

**Issue by pop756** [Qiskit/qiskit#12518]
### Environment

- **Qiskit version**:  1.1.0
- **Python version**:  3.11.9
- **Operating system**:  jupyter notebook

### What is happening?

When I used real backend, pulse draw cause this error 
![image](https://github.com/Qiskit/qiskit/assets/108378864/636e5db9-252e-437f-963c-6a2808999a89)

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit
from qiskit import pulse
from qiskit import schedule



circ = QuantumCircuit(2, 2)
circ.ecr(1, 0)
from qiskit import transpile
circ = transpile(circ,backend,optimization_level=0)
pulse_schedule = schedule(circ,backend=backend)
pulse_schedule.draw(backend=backend)
```

### What should happen?

TypeError: 'str' object is not callable

### Any suggestions?

![image](https://github.com/Qiskit/qiskit/assets/108378864/b193152b-629c-437b-abec-ccc53ac6782e)
When I changed the code like this, bug is fixed.

**Comment by HuangJunye** [comment]
I can reproduce the error.

**Comment by HuangJunye** [comment]
It is fixed by https://github.com/Qiskit/qiskit/pull/12608. Verified this issue is fixed by installing from the main branch.
