### ISSUE TITLE
Incorrect expectation estimation when Reset is used in circuit

### ISSUE THREAD

**Issue by SillieWous** [Qiskit/qiskit#12519]
### Environment

- **Qiskit version**:  1.1.0
- **Python version**:  3.12.3
- **Operating system**:  Fedora 40 Workstation

### What is happening?

In a circuit (aimed at simulation of a hamiltonian with disipation) I am getting incorrect estimation values of observables. The system I am simulating has two identical (non-interacting) qubit oscilators. For dissipation a non-unitary operation is implemented with an ancilla qubit that is reset at the start of a trotterisation step and measured at the end of the step to get the dissipation factor.

### How can we reproduce the issue?

See [GitLab repo](https://gitlab.com/SillieWous/qiskit-bug-report/-/blob/main/bug.ipynb) for an example.

### What should happen?

Since these are two identical systems without interaction they ought to measure the exact same state trajectory. However there are frequently values that do not agree between the two systems.

The image that is in the example (`Out[8]`) illustrates this pretty obviously.

Moreover the way the observables are defined they should always sum to 1 (see `Out[6]` in the example notebook). But at the indices where the image shows odd behaviour this is not the case. Looking at the values of the observables it seems a value of an earlier measurement is used instead of the correct one.

**Comment by t-imamichi** [comment]
I made a fix #12862. I modified the notebook to use `StatevectorEstimator` (EstimatorV2) and confirmed that #12862 behaves fine.
script: https://gist.github.com/t-imamichi/81f4b38ee572af03cf0c3d6b34e4ebd4

main branch:
![12519_main](https://github.com/user-attachments/assets/a88acbc7-6260-4c4e-ab97-57107fc9d940)
------
#12862 
![12519_fixed](https://github.com/user-attachments/assets/e8e1c89f-287b-499c-905a-b5c8256402b1)

**Comment by t-imamichi** [comment]
I updated #12862 based on @Cryoris's comment.

I confirmed that the sum of all observables are 1.

the new output of https://gist.github.com/t-imamichi/81f4b38ee572af03cf0c3d6b34e4ebd4
![tmp](https://github.com/user-attachments/assets/c6355429-3b03-40b7-901b-3cc0a4e1c50a)
