### ISSUE TITLE
'QuantumCircuit' object has no attribute 'qasm'

### ISSUE THREAD

**Issue by NikhilaYeturi** [Qiskit/qiskit#12549]
### Environment

- **Qiskit version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

I'm getting an error saying 'QuantumCircuit' object has no attribute 'qasm'

### How can we reproduce the issue?

Not sure need help

### What should happen?

I want my code to run

**Comment by Cryoris** [comment]
To dump to QASM you can use the `qiskit.qasm3` (or `qiskit.qasm2`) module. In the docs you should find what you're looking for: https://docs.quantum.ibm.com/api/qiskit/qasm3.
