### ISSUE TITLE
Strange things about `ParameterVector`

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit#12541]
### Environment

- **Qiskit version**: main
- **Python version**: 
- **Operating system**: 

### What is happening?

There are some weird things I have noticed while staring at the `ParameterVector` code.  One design choice is that it stores previous elements even if an array has been down-sized:

https://github.com/Qiskit/qiskit/blob/03d107e1f68f2a47ffdcf5599f906120e4efba63/qiskit/circuit/parametervector.py#L99-L104

Some methods, such as `__iter__` and `__str__` and a few others, correctly account for this:

https://github.com/Qiskit/qiskit/blob/03d107e1f68f2a47ffdcf5599f906120e4efba63/qiskit/circuit/parametervector.py#L87-L88
https://github.com/Qiskit/qiskit/blob/03d107e1f68f2a47ffdcf5599f906120e4efba63/qiskit/circuit/parametervector.py#L93-L94

However, other methods do not account for this, such as `index` and the `params` property:

https://github.com/Qiskit/qiskit/blob/03d107e1f68f2a47ffdcf5599f906120e4efba63/qiskit/circuit/parametervector.py#L69-L76

It appears that it may be intentional for `params` to return everything.  If so, this should be documented.  Also, it might be worth changing `index` to return only elements that currently exist.

### How can we reproduce the issue?

```python
pv = ParameterVector("theta", 20)
last = pv[-1]
pv.resize(3)
pv.index(last)  # returns 19, which is greater than len(pv) - 1
pv.params  # is a list of 20 elements, which is greater than len(pv)
```

### What should happen?

Up for discussion

**Comment by Cryoris** [comment]
The resizing feature is something used in blueprint circuits, e.g. the `RawFeatureVector` which is essentially a parameterized `Initialize` instruction. Until these objects exists we should keep this feature. The `params` and `index` methods seem to not handle this correctly, after resizing the available parameters should correspond to the new size.

**Comment by garrison** [comment]
> The resizing feature is something used in blueprint circuits, e.g. the `RawFeatureVector` which is essentially a parameterized `Initialize` instruction. Until these objects exists we should keep this feature. The `params` and `index` methods seem to not handle this correctly, after resizing the available parameters should correspond to the new size.

OK great, this is a very reasonable outcome.  I will open a PR that does this.
