### ISSUE TITLE
ImportError: DLL load failed while importing _accelerate

### ISSUE THREAD

**Issue by sonny-life** [Qiskit/qiskit#12586]
### Environment

- **Qiskit version**: 1.1.0 and 1.1.0rc1
- **Python version**:  3.8.8
- **Operating system**:  Windows 7 64bit

### What is happening?

When I try to execute ```import qiskit``` I received ImportError.

### How can we reproduce the issue?

Execute ```import qiskit``` in jupyter.

### What should happen?

Received output:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-578b7f7e9727> in <module>
----> 1 import qiskit

C:\ProgramData\Anaconda3\lib\site-packages\qiskit\__init__.py in <module>
     53 
     54 
---> 55 import qiskit._accelerate
     56 import qiskit._numpy_compat
     57 

ImportError: DLL load failed while importing _accelerate: The specified procedure could not be found.
```

### Any suggestions?

This is not happening with qiskit versions 1.0.2 or below.

**Comment by mtreinish** [comment]
As was documented in the release notes here: https://docs.quantum.ibm.com/api/qiskit/release-notes/1.1#misc-upgrade-notes due to upstream changes in the rust compiler the minimum supported version of windows for qiskit in 1.1.0 is windows 10. If you [install the rust compiler](https://www.rust-lang.org/tools/install) and use rust < 1.78 you can build and install qiskit from source with `pip install --no-binary qiskit qiskit`

**Comment by sonny-life** [comment]
Thanks for your fast response.
```pip install --no-binary qiskit qiskit``` with rust < 1.78 is a great suggestion.
Is it possible to put the minimum requirements for Windows 10 in visible place here:
https://github.com/Qiskit/qiskit/blob/main/README.md
also here:
https://pypi.org/project/qiskit/1.1.0/
and here:
https://pypi.org/project/qiskit/1.1.0rc1/
I think this will do a great help for everyone else that didn't find minimum requirement for Windows in those links.

**Comment by mtreinish** [comment]
The official platform support docs are located here:

https://docs.quantum.ibm.com/start/install#operating-system-support

they're a bit more intracite and detailed than what we'd normally put in the readme. There is a link to the broader install docs in the readme but we can refine that readme section a bit to mention supported platforms and linking to the appropriate subsection

**Comment by sonny-life** [comment]
Thanks for your message. The connection between qiskit version and respective operating system version is not available there. They also refer to: https://pypi.org/project/qiskit/
It will be great if you could add a brief operating system support with a few lines there.

**Comment by 1ucian0** [comment]
The first link in https://pypi.org/project/qiskit/ is to the documentation, where the install docs are there.

Closing it as wontfix.
