### ISSUE TITLE
Pulse drawer does not work with V2 backends from IBM Runtime 

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#12580]
### Environment

- **Qiskit version**: 1.1
- **Python version**: 
- **Operating system**: 

### What is happening?

```python
from qiskit import QuantumCircuit, transpile, schedule
from qiskit.visualization.pulse_v2 import draw
from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService()

backend = service.get_backend('ibm_sherbrooke')
 
qc = QuantumCircuit(2)
qc.cx(0, 1)
trans_qc = transpile(qc, backend)
sched = schedule(trans_qc, backend)
 
draw(sched, backend=backend)
```

File ~/mambaforge/envs/qiskit/lib/python3.11/site-packages/qiskit/visualization/pulse_v2/device_info.py:113, in OpenPulseBackendInfo.create_from_backend(cls, backend)
    110 defaults = backend.defaults()
    112 # load name
--> 113 name = backend.name()
    115 # load cycle time
    116 dt = configuration.dt

TypeError: 'str' object is not callable

### How can we reproduce the issue?

do above

### What should happen?

It should draw

### Any suggestions?

It is obviously just the change from method to attribute in the classes

**Comment by ElePT** [comment]
Fixed by @nkanazawa1989 in https://github.com/Qiskit/qiskit/pull/12608.
