### ISSUE TITLE
TwoLocal doc strings not valid

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#12590]
### Environment

- **Qiskit version**: 1.1
- **Python version**: 
- **Operating system**: 

### What is happening?

https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.TwoLocal

The docstrings uses old code which is no longer valid

### How can we reproduce the issue?

try to run doc strings on page

### What should happen?

It works

**Comment by Cryoris** [comment]
Should be fixed by #12609 🙂 (#12515 already removed `+=` but we missed that `+` was also used)
