### ISSUE TITLE
Parameter cache is preserved after copy_empty_like

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit#12617]
### Environment

- **Qiskit version**: main
- **Python version**: 
- **Operating system**: 

### What is happening?

Parameter appears in empty circuit after copy

### How can we reproduce the issue?

```python
p1 = Parameter("P1")
qc = QuantumCircuit(1)
qc.rz(p1, 0)
qc.parameters  # dummy call to fill cache

cpy = qc.copy_empty_like()
cpy.parameters
```
I see
```
ParameterView([Parameter(P1)])
```
which should not exist.

### What should happen?

Parameter should be empty

### Any suggestions?

Nullify `_parameters` after copy

**Comment by jakelishman** [comment]
Thanks for the report Naoki.  I think this has actually been in existence for some time, more than just the Rust changes.

**Comment by jakelishman** [comment]
Yeah, this appears to be in 1.1 and 0.46 - might well have been around for a long time.
