### ISSUE TITLE
Include pure python wheel in the release

### ISSUE THREAD

**Issue by nihaocami** [Qiskit/qiskit#12674]
### What should we add?

I am working on a project that requires the pure python wheel to be available on the build. Currently I don't see the wheel [here](https://pypi.org/project/qiskit/#files) which would be a `*py3-none-any.whl` file.

While I can certainly do it as a custom build for myself, was wondering if that's something we can add? is there anything preventing us from adding that to the build pipeline?

**Comment by jakelishman** [comment]
I'm not quite sure what you're asking for here: there is no pure-Python version of Qiskit. We've had compiled extensions as part of the core distribution for nearly as long as the package has existed.

**Comment by jakelishman** [comment]
If you mean the source, so you can build it yourself, we package the sdists as `.tar.gz` archives on PyPI. You'll need a functional Rust compiler (language version 1.70+) to build, but all the package sources are in the sdist.

**Comment by nihaocami** [comment]
@jakelishman oh right it makes sense then. Yeah I was thinking maybe there's a possibility of having the core python module wheels but it seems that's not how things are designed. closing issue. thx.

**Comment by jakelishman** [comment]
No worries, yeah. Generally the _most_ core parts are actually the compiled bits, especially these days - they're the part that's most performance and memory critical.
