### ISSUE TITLE
Typo in the RZZgate documentation

### ISSUE THREAD

**Issue by bowangle** [Qiskit/qiskit#12685]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.RZZGate#rzzgate
examples section
third equation

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

In example section, third equation:
R ZZ (θ=π)=−iZ⊗Z
The i is missing.

**Comment by shraddha-aangiras** [comment]
Hi, I addressed it in https://github.com/Qiskit/qiskit/pull/12678 on the qiskit repo since the documentation text in the code was to be changed
