### ISSUE TITLE
Incoherence in notation for RZX gate

### ISSUE THREAD

**Issue by bowangle** [Qiskit/qiskit#12684]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.RZXGate

In examples section, third equation

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

If we follow the notation introduce for RZX(θ) q0,q1=exp(−i θ/2 X⊗Z) which are the default notation, it would mean that in the "examples" section, we should have RZX(θ=π)=−iX⊗Z instead of −iZ⊗X. 
It's not coherent with the fact that in the note section, we use big-endian convention for the tensor notation.
Or else we have to tell in which way we apply the gate by adding the q1,q0 index like this: RZX(θ=π)q1,q0=−iZ⊗X.

**Comment by Eric-Arellano** [comment]
Thanks! This is an issue in the API docs, so it needs to be fixed in qiskit/qiskit. I'm transferring it there.

**Comment by Ameya28Bhave** [comment]
Hi @1ucian0 . Can you please assign me this issue. This would be helpful as my first qiskit contribution.
