### ISSUE TITLE
should we add matplotlib into the requirements.txt

### ISSUE THREAD

**Issue by haoxins** [Qiskit/qiskit#12728]
### What should we add?

Hi,
Should we add `matplotlib` into the `requirements.txt`?
1. The `qiskit.visualization` depends on it and is public for the end-users;
2. We should specify the version of the `matplotlib` in the `requirements.txt`.

It is not optional.

**Comment by jakelishman** [comment]
The matplotlib visualisations are optional parts of Qiskit - they're not needed for core use. We have them specified as optionals, and you can `pip install qiskit[visualization]` to pull in all optional Python dependencies that enhance visualisations.

Even for circuit visualisation, there is a text-only drawer that has no additional dependencies.

**Comment by haoxins** [comment]
ok, thx
