### ISSUE TITLE
error in the interface between ansys and qiskit metal

### ISSUE THREAD

**Issue by SimonaZaccaria** [Qiskit/qiskit#12748]
### Environment

- **Qiskit version**:  qiskit metal 0.1.5
- **Python version**:  python 3.11.9
- **Operating system**: Windows

### What is happening?

Running the code in order to do epr simulation (look at thi page https://qiskit-community.github.io/qiskit-metal/tut/4-Analysis/4.02-Eigenmode-and-EPR.html#), after a cfertain time the code didn't finish to run and the follow message appears "'Exception.', (0, None, None, None, 0, -2147024382), None))". On ansys also appears "Script macro error: Invalid PropServer 'Freq. vs. pass:re(Mode(1)):Curve1'"

### How can we reproduce the issue?

Follow this tutorial https://qiskit-community.github.io/qiskit-metal/tut/4-Analysis/4.02-Eigenmode-and-EPR.html# and when you arrivwe at the part that run epr analysis you should see the same error

### What should happen?

The program starts to run correctly but at the certain time it stops and give me an error message

### Any suggestions?

I don't know if it is something related to the version of ansys

**Comment by jakelishman** [comment]
Hi - I think you're looking for the qiskit-metal repository, which is here, and totally separate to the Qiskit SDK: https://github.com/qiskit-community/qiskit-metal.

We can't do anything about this here, but that repo is your best bet - you might want to refile this issue there.
