### ISSUE TITLE
`InstructionDurations.from_backend(...)` does not support BackendV2

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#12760]
### Environment

- **Qiskit version**: 1.2.0.dev0+8f6714d
- **Python version**: 3.8.19
- **Operating system**: MacOs

### What is happening?

While migrating `test/python/transpiler/test_instruction_durations.py` to BackendV2  (see https://github.com/Qiskit/qiskit/pull/12660 for context), I realized that  `InstructionDurations.from_backend` does not support `BackendV2` instances.

### How can we reproduce the issue?

```
from qiskit.providers.fake_provider import GenericBackendV2
from qiskit.transpiler import InstructionDurations

backend = GenericBackendV2(num_qubits=2, calibrate_instructions=True, seed=42)
InstructionDurations.from_backend(backend)
```
```
AttributeError: 'GenericBackendV2' object has no attribute 'properties'
```

### What should happen?

Either this method (preferred option) or a potential `InstructionDurations.from_backendV2` should support creating an `InstructionDurations` from a BackendV2, the current preferred way.

**Comment by shravanpatel30** [comment]
Hi @1ucian0, I was looking into this issue and had a question. I looked at the `BackendV1` fake backends and they are using old IBM device data for the `properties` and so I was wondering what date and time should be used to create the properties dictionary for `GenericBackendV2`?

**Comment by 1ucian0** [comment]
> I looked at the `BackendV1` fake backends and they are using old IBM device data for the `properties` and so I was wondering what date and time should be used to create the properties dictionary for `GenericBackendV2`?

Thanks for explaining this in https://github.com/Qiskit/qiskit/pull/12901 . The PR to understand this question. The point is to construct `InstructionDuration` from a `BackendV2` without extending `BackendV2`. This might not be an easy issue.

**Comment by Cryoris** [comment]
You should be able to just do
```python
instruction_durations = backend.target.durations()   # where backend is a BackendV2
```
