### ISSUE TITLE
Add parameterized gates to the `CommutationChecker`

### ISSUE THREAD

**Issue by MarcDrudis** [Qiskit/qiskit#12790]
### What should we add?

I realized that currently the `CommutationChecker` class can not handle Pauli Rotations if they are parameterized. In many cases our circuits are paramterized and the commutation relationships for this rotations are just the same ones as the ones for their generators. I propose to add this functionality into Qiskit. There are 2 ways to go about it. One would be to make the `standard_gate_commuation` dictionary bigger or to map the rotation gates to their generators.

I already have already implemented it for myself because I need it for my research so I would be happy to implement it for Qiskit.

**Comment by jakelishman** [comment]
I believe your #13302 solved this, but feel free to re-open if there was more to go.

**Comment by aeddins-ibm** [comment]
Are `Pauli` gates currently supported by the commutation checker? (they can have e.g. `'ZZ'` as a parameter)

On 1.3.0rc2, I'm getting `QiskitError: 'Unable to hash a non-float instruction parameter.'`, but I'm also doing some hacky stuff so the problem could be unique to my end.
