### ISSUE TITLE
reg_ prefix is unexpectedly added to a register name starting with capital when exported to OpenQASM 2

### ISSUE THREAD

**Issue by rht** [Qiskit/qiskit#12798]
### Environment

- **Qiskit version**: 1.1
- **Python version**: 3.12
- **Operating system**: NixOS 24.11 (Vicuna)

### What is happening?

When converting a qiskit circuit with a register which name starts with a capital (e.g. N, Nn, ...), to a OpenQASM 2 string, a prefix `reg_` is being added.

### How can we reproduce the issue?

```python
a = QuantumRegister(5, "N")
b = QuantumRegister(5, "n")
qc = QuantumCircuit(a, b)
for i in range(10):
    qc.h(i)
qasm_str = qiskit.qasm2.dumps(qc)
print(qasm_str)
```

Output
```
OPENQASM 2.0;
include "qelib1.inc";
qreg reg_N[5];
qreg n[5];
h reg_N[0];
h reg_N[1];
h reg_N[2];
h reg_N[3];
h reg_N[4];
h n[0];
h n[1];
h n[2];
h n[3];
h n[4];
```

### What should happen?

The OpenQASM 2 output for register `N` should have `N` as the name, not `reg_N`. Note that Nn becomes reg_Nn, but nN stays as nN.

### Any suggestions?

I haven't tried OpenQASM 3 yet.

**Comment by jakelishman** [comment]
OpenQASM 2 identifiers are not permitted to start with capital letters, per the letter of the spec; they were reserved for built-in symbols.

**Comment by jakelishman** [comment]
From [the OQ2 paper](https://arxiv.org/abs/1707.03429), page 4:

> Identifiers, such as name, must start with a lowercase letter and can contain alpha-numeric characters and underscores.

OpenQASM 3 doesn't include that restriction, so the OQ3 exporter shouldn't escape identifiers that involve capitals at the start (other than the built-in `U`).

**Comment by rht** [comment]
I see, thank you for the close to $c$ speed of reply! I will just migrate to OQ3 then.
