### ISSUE TITLE
BasicSimulator uses deprecated BackendConfiguration

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#12843]
While deprecating the models in `qiskit.providers.models` I realized that BasicSimulator uses `BackendConfiguration`, which is one of those models.

**Comment by ElePT** [comment]
When migrating `BasicSimulator` to `BackendV2` we decided to keep the `configuration` attribute for backward-ish compatibility with the interface of `BasicAer` (`BackendV1`), but it's not a required attribute for `BackendV2`. I think that now that `BackendConfiguration` is deprecated we can simply deprecate `BasicSimulator.configuration`.

**Comment by ghost** [comment]
Hello @ElePT,  What would be the equivalent of the deprecated `BackendConfiguarion.from_dict()` in Qiskit 2.0? Is there a method to initiate a configuration from a dictionary, as in Qiskit 1.2?

**Comment by ElePT** [comment]
Hi @csi21, what's deprecated is the `BackendConfiguration` class as a whole. The alternative to communicate backend constraints is using a [`Target`](https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.Target). As a transition step, you can build a `Target` from the configuration values using the following method:

```
Target.from_configuration(
         basis_gates, 
         num_qubits=None, 
         coupling_map=None, 
         inst_map=None, 
         backend_properties=None, 
         instruction_durations=None, 
         concurrent_measurements=None, 
         dt=None, 
         timing_constraints=None, 
         custom_name_mapping=None)
```
