### ISSUE TITLE
Stop storing default `unit="dt"` in rust space extra attributes by default

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#12900]
### What should we add?

Right now when adding gates to a circuit from Python the default value of the `unit` field ends up meaning we populate the rust space extra attributes field in the circuit instruction and filling it with a unit of "dt". This is just wasted memory that we shouldn't need to waste since everything has an implicit default of `"dt"`, the extra attributes in the rust data model was designed only to store custom values for the mutable state for instructions. We should update the logic when adding gates from Python to Rust space to avoid setting extra attributes if `unit="dt"`.

**Comment by tonmoy-b** [comment]
Can I take a shot at this?
