### ISSUE TITLE
Poor image quality while saving circuit image using qc.draw(output = 'latex').

### ISSUE THREAD

**Issue by crystaldot** [Qiskit/qiskit#12914]
### Environment

- **Qiskit version**: 1.1.1
- **Python version**: 3.12.3 
- **Operating system**: Linux fedora 6.9.6-200.fc40.x86_64

### What is happening?

I want to save a good quality image of circuit using `output = 'latex'` in `QuantumCircuit.draw()`.  It provides with a _good quality_ circuit image for `pdf` format but _very poor quality_ image for format like `png`,` jpeg`, `tiff`, `bmp` or any other. The return type in this case is `PIL.Image`. So, it does not support `svg`.  It already support 'svg' for `output = 'mpl'`; if possible, please add the feature for saving image with `svg` format while using `output = 'latex'` too.

### How can we reproduce the issue?

The code given below will generate an `png` file with _poor quality_ image. The file extension in `filename`  can be changed to `pdf` and  image quality can be compared.
```python3
from qiskit import QuantumCircuit
qc = QuantumCircuit(4)
qc.h(0)
qc.measure_all()
qc.draw(output = 'latex', filename = 'circuit.png')
```

### What should happen?

The above code should generate _good quality_ circuit image irrespective of the `filename` extension. It may generate lossy image for preview purpose but it should not generate the same while saving as an external file.

**Comment by jakelishman** [comment]
The LaTeX drawer produces vectorised PDF output.  PNG is a raster format. If you want to more precisely control how the rasterisation of the PDF is done, I would suggest you save the PDF and then rasterise it yourself, where you can fully control the tool. You might want to use a specialised tool like Inkscape for that.

**Comment by jakelishman** [comment]
I missed the SVG comment earlier.  That conversion is another thing you will likely want a specialised vector tool for. Qiskit isn't really an image-manipulation library - it's best for us to leave that to users to use proper tools, where you'll have more control over it.

Matplotlib has native output to SVG, so no conversion is necessary.

**Comment by crystaldot** [comment]
I have been using Inkscape to convert a PDF to SVG for my work. I know `qc.draw(output = 'mpl', filename = 'image.svg')` can generate a SVG file with high quality as Matplotlib has a native output. If the support for same can be added for `qc.draw(output = 'latex', filename = 'image.svg')` it would be highly useful in certain cases. I understand that process is not straightforward. I was hoping if it can be added in future releases; making it easier for _basic qiskit users_ not to worry about post processing. :)

I do agree that user can always use a proper tools for conversion with more control.

**Comment by jakelishman** [comment]
I'm not aware of any simple method that can convert a PDF to SVG without highly specialised tools, and given we do have a path to SVG support (using the Matplotlib backend) in the visualisers, I'm not sure attempting to hack in support for arbitrary backends to produce arbitrary file-format output is a good idea.  Put another way: we similarly wouldn't expect `draw("text", filename="file.svg")` to produce any sensible SVG.

The correct solution if an advanced user _really_ wants to use the LaTeX-produced output and convert it to an SVG is to use Inkscape, or some other vector-graphics package.
