### ISSUE TITLE
add samplerv2 support for qiskit/algorithms/state_fidelities/compute_uncompute.py

### ISSUE THREAD

**Issue by quark365** [Qiskit/qiskit#12940]
### Environment

- **Qiskit version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

sampler is Deprecated since version 0.23 and will get removed by July 15, 2024.    so this wont work fix it

### How can we reproduce the issue?

just run using sampler after July 15, 2024. and u will see

### What should happen?

add support for samplerv2

### Any suggestions?

please update it as fast as possible

**Comment by 1ucian0** [comment]
This issue seems to have been accidentally submitted to the wrong repo. Closing it. Please consider sending it to https://github.com/qiskit-community/qiskit-algorithms/issues/new/choose.
