### ISSUE TITLE
Port `QuantumCircuit.count_ops()` to rust

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#12971]
### What should we add?

Right now the `QuantumCircuit.count_ops()` method is written in Python by iterating over the circuit data and collecting counts in a dictionary, sorting it by gate name and returning that dictionary. However, the underlying data is stored in rust's `CircuitData` struct and it would be much more efficient to do the counting and in rust. We should port this utility method to rust to provide and provide a significant speedup for the method.

**Comment by melechlapson** [comment]
@mtreinish I can work on this issue

**Comment by mtreinish** [comment]
Cool, thanks I've assign the issue to you.

**Comment by mtreinish** [comment]
Implemented by https://github.com/Qiskit/qiskit/pull/13050
