### ISSUE TITLE
Documentation of `dag_drawer` is unclear on allowed types

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit#13021]
Talking about `qiskit.visualization.dag_visualization`:

              What's the reason to have a `not isinstance(dag, DAGCircuit)` path in this function?

_Originally posted by @jakelishman in https://github.com/Qiskit/qiskit/pull/12550#discussion_r1713726314_

The documentation of `dag_drawer` implies that only `DAGCircuit` is allowable, but actually the function is intended to work with `DAGDependency` as well.  We should update the documentation to be accurate.

**Comment by azhar-ikhtiarudin** [comment]
Hi, I am new to contributing to Qiskit and would like to learn. Is this issue still open, and may I be assigned to it? Thank you.

**Comment by AngeloDanducci** [comment]
@azhar-ikhtiarudin assigned, thanks!

**Comment by azhar-ikhtiarudin** [comment]
Hi, I apologize for the delay in my response. I’ve reviewed the case. Is it correct that I only need to add `DAGDependency` to the `dag` parameter? If so, the documentation should read:

`dag (DAGCircuit, DAGDependency)`

Is it correct? or should I also include example code or other details?

Thank you!

I refer to this page: https://github.com/Qiskit/documentation/blob/main/docs/api/qiskit/qiskit.visualization.dag_drawer.mdx

**Comment by azhar-ikhtiarudin** [comment]
Hi, I've checked this issue again and realized that maybe the appropriate documentation to update is located here:

https://github.com/Qiskit/qiskit/blob/main/qiskit/visualization/dag_visualization.py

particularly in this section:

```
    Args:
        dag (DAGCircuit or DAGDependency): The dag to draw.
```

Could you kindly confirm if this is the correct place for the update? My apologies for any earlier confusion, and thank you for your understanding.
