### ISSUE TITLE
`Clifford.to_circuit()` returns a circuit with emtpy `qregs`

### ISSUE THREAD

**Issue by matteoacrossi** [Qiskit/qiskit#13041]
### Environment

- **Qiskit version**: 1.2
- **Python version**: 3.10
- **Operating system**: Linux

### What is happening?

`Clifford.to_circuit()` returns a `QuantumCircuit` with empty `qregs`. I don't know if this is an expected behaviour, but it has changed since qiskit 1.1.2.

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit
from qiskit.quantum_info import Clifford

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
cli = Clifford(qc)
cli.to_circuit().qregs
```

### What should happen?

I would expect the `QuantumCircuit` to contain one `QuantumRegister` with the correct size, as it was the case in qiskit 1.1.2

```
>>> cli.to_circuit().qregs
[QuantumRegister(2, 'q')]
```

**Comment by matteoacrossi** [comment]
With `git bisect` I found out that the regression was introduced in #12714

**Comment by jakelishman** [comment]
This change was unintentional and we will backport to fix it, but as a follow up: what are you doing that requires the `QuantumRegister`? The quantum register type is very close to meaningless in Qiskit, and I'm not sure how other libraries might be using it.

(Fwiw, registers are neither necessary for a circuit nor required to contain only unique bits, so the output of the function is still a valid circuit object, it's only a bug that we deviated from the prior behaviour without meaning to.)
