### ISSUE TITLE
Clarify docstring: Pauli-types `conjugate()` is complex conjugate, not Hermitian conjugate

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit#13051]
### Environment

- **Qiskit version**: 1.2
- **Python version**: 3.11
- **Operating system**: macOS

### What is happening?

Not strictly a bug, just a doc clarification.

The docstring for the `conjugate` method of Pauli is:
```
Return the conjugate of each Pauli in the list.
```
and for SparsePauliOp is
```
Return the conjugate of the SparsePauliOp.
```

Personally, when I hear "conjugate of an operator" I think Hermitian conjugate. To avoid confusion with Hermitian conjugate, can we change the docstring of `conjugate` for Pauli, SparsePauliOp, etc to specify explicitly:
```
Return the complex conjugate of each Pauli in the list.
```
and
```
Return the complex conjugate of the SparsePauliOp.
```

(It's also weird there's a reference to a "list" in the docstring for a single Pauli, but I'm not concerned about that here).

### How can we reproduce the issue?

n/a

### What should happen?

n/a

**Comment by Cryoris** [comment]
I would agree, that can be confusing. Would you like to open an issue to fix this? 🙂

**Comment by boonware** [comment]
@Cryoris Can you assign this to me, please? A fix is in this PR: https://github.com/Qiskit/qiskit/pull/13312

**Comment by aeddins-ibm** [comment]
Thanks all -- would it be worth doing this for `SparsePauliOp` as well?

It would be updating the description of `conjugate` that shows up here in the docs: https://docs.quantum.ibm.com/api/qiskit/qiskit.quantum_info.SparsePauliOp#conjugate
![Image](https://github.com/user-attachments/assets/24a40df5-c627-4bc4-a92c-c368936cafbd)

However I do not see where this string is defined in qiskit's code.

**Comment by boonware** [comment]
@aeddins-ibm Indeed, it looks like there are more references that could do with updating. I have created an issue and will tackle this soon: https://github.com/Qiskit/qiskit/issues/13322
