### ISSUE TITLE
Deprecate pulse module and related functionality for removal in 2.0

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#13063]
### What should we add?

It's been decided that moving into Qiskit 2.0 we'll be removing the pulse module and all the related functionality (such as the [schedule](https://docs.quantum.ibm.com/api/qiskit/compiler#schedule) function along with it's backing module and calibrations in the target) as it's not in scope for the direction of the project anymore. We should ensure that we mark all these features as deprecated in 1.3.0 so there is sufficient warning prior to the release of Qiskit 2.0. These features will continue to be supported in Qiskit through the EoL with the 1.x.y release series into the 2H of 2025.

**Comment by eliarbel** [comment]
I'd be happy to work on this.

**Comment by Zonaldo7** [comment]
Will pulse related module become another independent package?

**Comment by eliarbel** [comment]
Hi @Zonaldo7, the Pulse module will be part of [Qiskit Dynamics](https://github.com/qiskit-community/qiskit-dynamics) once removed.

**Comment by chookity-pokk** [comment]
> Hi [@Zonaldo7](https://github.com/Zonaldo7), the Pulse module will be part of [Qiskit Dynamics](https://github.com/qiskit-community/qiskit-dynamics) once removed.

Just a small note here in the event others find this. The Pulse module won't be part of Qiskit Dynamics as mentioned [in this PR](https://github.com/qiskit-community/qiskit-dynamics/pull/365#issuecomment-2804010180).
