### ISSUE TITLE
Build warning with Rust 1.81.0

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#13096]
### What should we add?

When building Qiskit with the latest Rust release, 1.81.0, a future incompatibility warning is raised at the end of the build:

```
warning: the following packages contain code that will be rejected by a future version of Rust: ra_ap_stdx v0.0.188
```

Looking at the cargo report this is caused by code in the crate that might lead to undefined behavior in a future release of Rust. 

This isn't a direct issue in Qiskit, as the `ra_ap_stdx` dependency gets pulled in by: https://github.com/Qiskit/openqasm3_parser but I opened so we can track it on the Qiskit side as people building qiskit will encounter this. It also will let us track upgrading the openqasm3_parser version once this is addressed over there.

The upstream tracking issue is: https://github.com/Qiskit/openqasm3_parser/issues/229

**Comment by jlapeyre** [comment]
The most recent version of `ra_ap_stdx` that is compatible with rust v1.70 is 0.0.190. But version 0.0.190 still causes the warning to be printed when compiling with rust v1.81.0

We need to find a workaround.

EDIT: See mention below regarding removing dependence on `ra_ap_stdx`.
