### ISSUE TITLE
Change `DAGCircuit::collect_runs()` return to not be an `Option`

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#13109]
> It looks like `DAGCircuit::collect_runs` returns an `Option` only because it directly returns the result of the Rustworkx core function, which uses `None` to represent a cycle in the graph (...which is questionable lol). 

> Perhaps it is beyond the scope of this PR, but it might be nice if you can change `DAGCircuit::collect_runs` to unwrap that option internally. If it fails, it should be on `DAGCircuit` for getting itself into an invalid state.

_Originally posted by @kevinhartman in https://github.com/Qiskit/qiskit/pull/13013#discussion_r1744485781_

To fix this issue we should update the `collect_runs()` method in `crates/circuit/src/dag_circuit.rs` to internally unwrap the return from rustworkx and not return an option.

**Comment by tonmoy-b** [comment]
Hi, while I'm working on another issue I would love to work on this one as well. If it's ok to assign a second issue to me, kindly do so. Thanks

**Comment by AngeloDanducci** [comment]
@tonmoy-b assigned, thanks!

**Comment by cameron-d28** [comment]
i have created a [pull request for this issue](https://github.com/Qiskit/qiskit/pull/13222). please let me know if formatting is correct and perhaps how to test better - this is my first qiskit issue and not too familiar with rust.

**Comment by tonmoy-b** [comment]
> i have created a [pull request for this issue](https://github.com/Qiskit/qiskit/pull/13222). please let me know if formatting is correct and perhaps how to test better - this is my first qiskit issue and not too familiar with rust.

Hi Cameron, someone will review your PR code but I think you need to sign the CLA first. I'm not sure how to transfer the assignee tag to you but maybe that can be done later. You probably should sign the CLA for now.

**Comment by cameron-d28** [comment]
i just signed it - thank you for the heads up.

**Comment by cameron-d28** [comment]
any suggestion on my pull request? happy for feedback.

**Comment by cameron-d28** [comment]
is it okay that some of the workflows are failing?

**Comment by tonmoy-b** [comment]
> is it okay that some of the workflows are failing?

Make sure you run tox, tox -eblack and tox -elint in your local system before you push. The last in particular will give you code formatting errors that you should correct so there's no issues later on

**Comment by tonmoy-b** [comment]
> any suggestion on my pull request? happy for feedback.

I need till this weekend or Monday, I'll get back to you then but maybe one of the project maintainers will give a review before that.

**Comment by cameron-d28** [comment]
do you know how long it may take for [pull request](https://github.com/Qiskit/qiskit/pull/13222) to be approved or to get feedback? it has just passed all the tests. @tonmoy-b @AngeloDanducci
