### ISSUE TITLE
Document `get_standard_gate_name_mapping`

### ISSUE THREAD

**Issue by wshanks** [Qiskit/qiskit#13108]
`get_standard_gate_name_mapping` is referenced in the `Target` documentation now and used in several other projects (GitHub search brings up qiskit-experiments, qiskit-aer, blackwater, and qiskit-ibm-runtime among others). It would be nice to document it so it is officially part of the public API.

**Comment by Shivansh20128** [comment]
@1ucian0 Hi! I am new to Qiskit open source, and want to work on this issue. Can you please assign it to me? 
Thanks

**Comment by 1ucian0** [comment]
Welcome!

**Comment by Shivansh20128** [comment]
Hi, @1ucian0! I have prepared the material for the function _get_standard_gate_name_mapping()_, but I am unsure where to write it. Shall I write it under the Standard Gates section [here](https://docs.quantum.ibm.com/api/qiskit/circuit_library#standard-gates), as the function is a part of _qiskit.circuit.library.standard_gates_ as you can see [here](https://github.com/Qiskit/qiskit/blob/79a99a1ca46c742a1d5ecfc6a84dbef5a467a430/qiskit/circuit/library/standard_gates/__init__.py#L49).

Apologies if this is an inappropriate question.
Thank You

**Comment by 1ucian0** [comment]
I think the original issue is to document the function itself. It can definitely link to Standard gate section.

**Comment by Shivansh20128** [comment]
Pull request has been created [link](https://github.com/Qiskit/qiskit/pull/13207). I hope it is fine.
Thank You

**Comment by Shivansh20128** [comment]
I have created a new PR—I apologize for the inconvenience.
Thank You
