### ISSUE TITLE
Incomplete deletion of the parametric gate

### ISSUE THREAD

**Issue by ahsan-quantum** [Qiskit/qiskit#13113]
### Environment

- **Qiskit version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

Qiskit doe snot automatically delete the parameter from the circuit when the parametric gate is removed using ckt.data.pop( .. ). Developers should have it fixed. Thanks

### How can we reproduce the issue?

num_qubits = 2
ansatz_opt = RealAmplitudes(num_qubits, entanglement =  [(0, 1)], reps=1,skip_unentangled_qubits= True,flatten = True)
print('Circuit parameters BEFORE deleting the parametric gate and the parameter',ansatz_opt.parameters.data)
ansatz_opt.data.pop(4)
ansatz_opt.parameters.data.pop(3)
print('Circuit parameters AFTER deleting the parametric gate and the parameter',ansatz_opt.parameters.data)

### What should happen?

Desired output
[ParameterVectorElement(θ[0]), ParameterVectorElement(θ[1]), ParameterVectorElement(θ[2])]

Actual output
[ParameterVectorElement(θ[0]), ParameterVectorElement(θ[1]), ParameterVectorElement(θ[2]), ParameterVectorElement(θ[3])]

**Comment by Cryoris** [comment]
The `QuantumCircuit.data` attribute is not safe to mutate, as mentioned in [the docs](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#circuit-attributes):

> The core attribute is [data](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#qiskit.circuit.QuantumCircuit.data). This is a sequence-like object that exposes the [CircuitInstruction](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.CircuitInstruction)s contained in an ordered form. You generally should not mutate this object directly; [QuantumCircuit](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#qiskit.circuit.QuantumCircuit) is only designed for append-only operations (which should use [append()](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#qiskit.circuit.QuantumCircuit.append)). [...]

If you need to remove gates from an existing circuit the safest approach would be to rebuild it without the gate you want to remove.

**Comment by Cryoris** [comment]
I'll go ahead and close this, but feel free to comment to discuss further, or re-open this in case we're missing something!
