### ISSUE TITLE
VQE with intermediate measurements

### ISSUE THREAD

**Issue by Symphysy** [Qiskit/qiskit#13129]
### Environment

- **Qiskit version**: 1.0.2
- **Python version**: 
- **Operating system**: 

### What is happening?

I am trying to run a VQE, where my ansatz contains intermediate measurements + feedback, or dynamic circuits; the error is:

QiskitError: 'Cannot apply instruction with classical bits: measure'

### How can we reproduce the issue?

import numpy as np
from qiskit import *
from qiskit.circuit import ParameterVector,Parameter
from qiskit.circuit.classical import expr
from qiskit.circuit.library import RYGate

from qiskit.quantum_info import SparsePauliOp

ham=SparsePauliOp(["II", "XZ"], [-1.0,-2.0])

q=QuantumRegister(2)
c=ClassicalRegister(2)
qc=QuantumCircuit(q,c)

theta=Parameter("t")
qc.ry(theta,0)
qc.measure(0,c[0])
result=expr.lift(c[0])
with qc.if_test(result):
    qc.z(1)

from qiskit.primitives import Estimator 
from qiskit_algorithms.optimizers import COBYLA
from qiskit_algorithms import VQE

estimator = Estimator()
iterations = 1000
cobyla= COBYLA(maxiter=iterations)
vqe = VQE(estimator, qc, cobyla)
result = vqe.compute_minimum_eigenvalue(operator=ham)
print(result)

### What should happen?

It should run the circuit with shots, and for each shot a different measurement outcome may occur. The Aer simulator already has the functionality to perform shots on dynamic circuits, but it seems VQE can't...

**Comment by Cryoris** [comment]
The `qiskit.primitives.Estimator` does not support mid-circuit measurements. To run an algorithm (like VQE) with such circuits, you have to use a simulator/backend that supports mid-circuit measurements, like the Aer primitives you've already mentioned.

**Comment by Symphysy** [comment]
I was able to fix it by changing my simulator (and some other things). Thanks!
