### ISSUE TITLE
qc_compiled.draw(output="mpl",idle_wires=False) collapses to display only 1 qubit for dynamic circuits

### ISSUE THREAD

**Issue by mrvee-qC-bee** [Qiskit/qiskit#13146]
### Environment

- **Qiskit version**: 1.2.1
- **Python version**: 3.11
- **Operating system**: macOS 15

### What is happening?

When using qc_compiled.draw(output="mpl", idle_wires=False) for dynamic circuits, the resulting plot collapses to display only 1 qubit, even when multiple qubits are present in the circuit. This behavior occurs only when setting idle_wires=False, which is expected to retain and display all active wires (qubits) that are used dynamically in the circuit.

### How can we reproduce the issue?

```python3
# Step 1: Map the problem to a quantum-native format
# Create the circuit with 3-qubits and 1-bit
qc = QuantumCircuit(3,3)    

# Alice creates an unknown quantum state using the u-gate.
qc.u(theta, varphi, 0.0, 0)
qc.barrier()    # for visual separation

# Eve creates EPR pair and sends q1 to Alice and q2 to Bob
##your code goes here##
qc.h(1)
qc.cx(1, 2)
qc.barrier()

# Alice entangles the unknown state with her EPR part, using the CNOT gate & H gate.
##your code goes here##
qc.cx(0, 1)
qc.h(0)
qc.barrier()

# Alice measures the two qubits.
##your code goes here##
qc.measure(0, 0)
qc.measure(1, 1)

# Alice sent the results to Bob. Now, Bob applies correction
##your code goes here##
with qc.if_test((0, 1)):
    qc.z(2)
with qc.if_test((1, 1)):
    qc.x(2)
qc.barrier()

# Apply the inverse of u-gate to measure |0>   
qc.u(theta, varphi, 0.0, 2).inverse()    
qc.measure(2, 2)

qc.draw(output="mpl", idle_wires=True)
```

```python3
service = QiskitRuntimeService(channel="ibm_quantum")
service.backends()

# You can specifiy the device 
backend = service.backend('ibm_sherbrooke')

# Step 2: Optimize the circuits
# Transpile the circuit into basis gates executable on the hardware
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
pm = generate_preset_pass_manager(backend=backend, optimization_level=2)
qc_compiled = pm.run(qc)

qc_compiled.draw(output="mpl",idle_wires=False)

```

### What should happen?

Expected Behavior:
The qc_compiled.draw(output="mpl", idle_wires=False) should display all qubits, even if they are used dynamically, when idle_wires=False is specified. The plot should reflect the full set of qubits involved in the circuit.

<img width="638" alt="Screenshot 2024-09-13 at 2 04 10 PM" src="https://github.com/user-attachments/assets/61e531b4-161a-4925-b7b7-3344ba5d71b2">

Actual Behavior:
The plot collapses and displays only 1 qubit, ignoring the presence of other qubits in the dynamic circuit, which limits the visibility of the full circuit structure.

<img width="638" alt="Screenshot 2024-09-13 at 2 04 00 PM" src="https://github.com/user-attachments/assets/b0ec4db8-1615-4db0-a24f-b9408a40a55e">

**Comment by mrvee-qC-bee** [comment]
@kifumi -san for your awareness!

**Comment by 1ucian0** [comment]
Is this a https://github.com/Qiskit/qiskit/issues/13128 duplicated?

**Comment by mrvee-qC-bee** [comment]
Hi @1ucian0! Yes, this seems to be repeated, sorry about that. Closing the issue!
