### ISSUE TITLE
Adding `GlobalPhaseGate` does not update the `circuit.global_phase` attribute

### ISSUE THREAD

**Issue by ACE07-Sev** [Qiskit/qiskit#13206]
### Environment

- **Qiskit version**: 1.2
- **Python version**: 3.11.9
- **Operating system**: Ubuntu 22.04 (running using WSL)

### What is happening?

Greetings there,

Hope all are well. I noticed that adding the global phase gate to a circuit doesn't update the `global_phase` attribute. I am not sure if this is intentional or not, but I think it should update the attribute as I was told one could just manually set the global phase attribute to some value if they don't want to add a gate for it https://github.com/Qiskit/qiskit/issues/12163#issuecomment-2045250336.

I did some testing, and found the functionality is correct (if you extract the unitary representation of the circuit, it should take the global phase into account, which it is). However, I noticed that whilst `global_phase` is not updated it's instead added to the circuit as a new instruction, which is why the code doesn't have issues.
```
[CircuitInstruction(operation=Instruction(name='global_phase', num_qubits=0, num_clbits=0, params=[0.15]), qubits=(), clbits=())]
```
Nonetheless, I think given `global_phase` attribute is supposed to keep track of the circuit's global phase, and that `GlobalPhaseGate`'s main purpose is to allow for adding global phase to a circuit, I think it would make more sense to just update `global_phase` attribute, and to avoid duplicating the effect, to ignore `GlobalPhaseGate` in the unitary definition of a circuit. Otherwise, it just feels one makes the other redundant.

### How can we reproduce the issue?

```py
from qiskit import QuantumCircuit
from qiskit.circuit.library import GlobalPhaseGate

qc = QuantumCircuit(2)

global_phase = GlobalPhaseGate(0.15)
qc.append(global_phase, (), ())

print(qc.global_phase)

qc.global_phase = 0.15

print(qc.global_phase)
```
```
0.0
0.15
```

### What should happen?

After applying the global phase gate, I believe the `global_phase` attribute should also be updated. Essentially, if you set the `global_phase` attribute manually, it should simply overwrite the global phase of a circuit, however, if you apply a global phase, it should be added to the `global_phase`.

In simple terms, it's like `a=1` and `a+=1`.

### Any suggestions?

So, I did the below fix which is admittedly ugly as it ruins the abstraction of `QuantumCircuit`'s `._append()` method. I would be a bit more effective if this is indeed an issue and not a design choice.

```py
def _append(self, instruction, qargs=(), cargs=(), *, _standard_gate: bool = False):
        """Append an instruction to the end of the circuit, modifying the circuit in place.

        .. warning::

            This is an internal fast-path function, and it is the responsibility of the caller to
            ensure that all the arguments are valid; there is no error checking here.  In
            particular:

            * all the qubits and clbits must already exist in the circuit and there can be no
              duplicates in the list.
            * any control-flow operations or classically conditioned instructions must act only on
              variables present in the circuit.
            * the circuit must not be within a control-flow builder context.

        .. note::

            This function may be used by callers other than :obj:`.QuantumCircuit` when the caller
            is sure that all error-checking, broadcasting and scoping has already been performed,
            and the only reference to the circuit the instructions are being appended to is within
            that same function.  In particular, it is not safe to call
            :meth:`QuantumCircuit._append` on a circuit that is received by a function argument.
            This is because :meth:`.QuantumCircuit._append` will not recognize the scoping
            constructs of the control-flow builder interface.

        Args:
            instruction: A complete well-formed :class:`.CircuitInstruction` of the operation and
                its context to be added.

                In the legacy compatibility form, this can be a bare :class:`.Operation`, in which
                case ``qargs`` and ``cargs`` must be explicitly given.
            qargs: Legacy argument for qubits to attach the bare :class:`.Operation` to.  Ignored if
                the first argument is in the preferential :class:`.CircuitInstruction` form.
            cargs: Legacy argument for clbits to attach the bare :class:`.Operation` to.  Ignored if
                the first argument is in the preferential :class:`.CircuitInstruction` form.

        Returns:
            CircuitInstruction: a handle to the instruction that was just added.

        :meta public:
        """
        if _standard_gate:
            self._data.append(instruction)
            self.duration = None
            self.unit = "dt"
            return instruction

        old_style = not isinstance(instruction, CircuitInstruction)
        if old_style:
            instruction = CircuitInstruction(instruction, qargs, cargs)
         
        # If the operation is the :class:`GlobalPhaseGate`, then apply the global phase
        # to the `self.global_phase` attribute directly and return `None` to avoid duplicating
        # the instruction's effect.
        if instruction.name == "global_phase":
            self.global_phase += instruction.params[0]
            return
   
        # If there is a reference to the outer circuit in an
        # instruction param the inner rust append method will raise a runtime error.
        # When this happens we need to handle the parameters separately.
        # This shouldn't happen in practice but 2 tests were doing this and it's not
        # explicitly prohibted by the API.
        try:
            self._data.append(instruction)
        except RuntimeError:
            params = [
                (idx, param.parameters)
                for idx, param in enumerate(instruction.operation.params)
                if isinstance(param, (ParameterExpression, QuantumCircuit))
            ]
            self._data.append_manual_params(instruction, params)

        # Invalidate whole circuit duration if an instruction is added
        self.duration = None
        self.unit = "dt"
        return instruction.operation if old_style else instruction
```

**Comment by jakelishman** [comment]
This is expected behaviour - the `GlobalPhaseGate` is an explicit way u
of interacting with the global phase, in addition to the circuit attribute. It'll compile to be equivalent to an update the `global_phase` attribute, but it's provided as an explicit circuit instruction, so it can be combined with other higher-order constructs like `
control` or the like.

We can't have `GlobalPhaseGate` _also_ update `global_phase`, otherwise we'd be duplicating the update.

**Comment by ACE07-Sev** [comment]
I see. In that case we can close the issue since it's not a bug, rather a design choice.

Thank you very much as always, Jake!
