### ISSUE TITLE
Typo on api/qiskit/providers page

### ISSUE THREAD

**Issue by dbowmansqc** [Qiskit/qiskit#13211]
### Environment

- **Qiskit version**: 1.2.2 
- **Python version**: 3.x
- **Operating system**: -

### What is happening?

Code snippet in section custom basis gates on page api/qiskit/providers: 
```import numpy as np
 
from qiskit.circuit import Gate
from qiskit.circuit import QuantumCircuit
 
class SYGate(Gate):
    def __init__(self, label=None):
        super().__init__("sy", 1, [], label=label)
 
    def _define(self):
        qc = QuantumCircuit(1)
        q.ry(np.pi / 2, 0)
        self.definition = qc
```

penultimate line should read 
```
qc.ry(np.pi / 2, 0)
```

### How can we reproduce the issue?

Typo

### What should happen?

should read 
```
qc.ry(np.pi / 2, 0)
```

**Comment by hegdeashwin** [comment]
I would like to pick this bug as "good first issue".

**Comment by Cryoris** [comment]
Nice, go ahead @hegdeashwin 👍🏻

**Comment by DisantHoridnt** [comment]
is this issue still open? or are you still working on it @hegdeashwin . I can help you if you need it. lets connect
