### ISSUE TITLE
Incorrect Equality in Documentation: Gate Ryy(θ=π) ≠  iY ⊗ Y

### ISSUE THREAD

**Issue by jofrevalles** [Qiskit/qiskit#13225]
### Environment

- **Qiskit version**: 1.2.2
- **Python version**: -
- **Operating system**: -

### What is happening?

Hey there!

I noticed a potential mistake in the API documentation where Gate `Ryy` is said to fulfill $R_{yy}(\theta=\pi)=iY\otimes Y$, and instead the proper value I think it should be $R_{yy}(\theta=\pi)=-iY\otimes Y$, if I am not mistaken.
I know it is a rather small detail, but I just wanted to let you know.

Thanks!

### How can we reproduce the issue?

See documentation.

### What should happen?

I expected the docstring to be 
```
            R_{YY}(\theta = \pi) = -i Y \otimes Y
```

**Comment by jakelishman** [comment]
Yeah, that's a typo, thanks.  I wouldn't be surprised if the same typo is made on `RXXGate`, `RZXGate` and `RZZGate` (I expect the documentation was just copy-pasted at some point).  Would you be interested in making a PR to fix it?

**Comment by jofrevalles** [comment]
> Yeah, that's a typo, thanks. I wouldn't be surprised if the same typo is made on `RXXGate`, `RZXGate` and `RZZGate` (I expect the documentation was just copy-pasted at some point). Would you be interested in making a PR to fix it?

Yes, okay! I check for these other gates and do the PR. Thanks!

**Comment by jakelishman** [comment]
Ace, thanks! I've assigned you so others know you're working on it, but no pressure - if you're not able to for any reason at all, just let us know.
