### ISSUE TITLE
Potential error in the code example used in circuit_drawer function API Docs

### ISSUE THREAD

**Issue by Shivansh20128** [Qiskit/qiskit#13233]
### Environment

- **Qiskit version**: NA
- **Python version**: NA
- **Operating system**: NA

### What is happening?

In the API docs for _circuit_drawer_ function [here](https://docs.quantum.ibm.com/api/qiskit/dev/qiskit.visualization.circuit_drawer#qiskitvisualizationcircuit_drawer), the code example given (at the end) uses the function _draw_, which I think is not the same as the function being documented here. 
Both these function belongs to different libraries, hence should not used as the same.

```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
qc = QuantumCircuit(1, 1)
qc.h(0)
qc.measure(0, 0)
qc.draw(output='mpl', style={'backgroundcolor': '#EEEEEE'})
```

### How can we reproduce the issue?

Read the API docs for _circuit_drawer_ function [here](https://docs.quantum.ibm.com/api/qiskit/dev/qiskit.visualization.circuit_drawer#qiskitvisualizationcircuit_drawer).

### What should happen?

The code example should use "circuit_drawer" instead of "draw" function.

```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
qc = QuantumCircuit(1, 1)
qc.h(0)
qc.measure(0, 0)
circuit_drawer(qc, output="mpl", style={"backgroundcolor":"#EEEEEE"})
```

**Comment by Shivansh20128** [comment]
If this needs to be corrected, please assign this to me. I think only the proposed changes are required to resolve this issue.
Thank You

**Comment by Eric-Arellano** [comment]
You're right, @Shivansh20128. Great catch! QuantumCircuit.draw ends up using circuit_drawer under-the-hood, but it's indeed confusing to not directly use `circuit_drawer` for `circuit_drawer`'s documentation.
