### ISSUE TITLE
Deprecate `instruction_durations`, `timing_constraints` and `backend_properties` in `generate_preset_pass_manager`

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#13306]
The function `generate_preset_pass_manager` should deprecate ``instruction_durations``, ``inst_map``, ``timing_constraints`` and ``backend_properties`` in favor of `target`.

**Comment by eliarbel** [comment]
`inst_map` will be deprecated as part of #13164

**Comment by blakejohnson** [comment]
`instruction_durations` can still be found in the `Target`?

**Comment by 1ucian0** [comment]
Yes. The goal is to move towards `Target`-define constrains and stop having loose constrains.
