### ISSUE TITLE
`InverseCancellation` does not run in classical blocks like `CXCancellation`

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#13437]
### Environment

- **Qiskit version**: `2.0.0.dev0+5de0232`

### What is happening?

In https://github.com/Qiskit/qiskit/issues/11212 we decided to "stop using `CXCancellation` as part of the preset pass managers as it's been superseded by `InverseCancellation`". However, `CXCancellation` runs inside flow controlled blocks but `InverseCancellation` does not.

### How can we reproduce the issue?

1. Create a circuit with control flow:
```python
from qiskit import QuantumCircuit
inner = QuantumCircuit(2,1)
inner.cx(0, 1)
inner.cx(0, 1)

qc = QuantumCircuit(2, 1)
qc.cx(0, 1)
qc.cx(0, 1)
qc.if_else((0, True), inner.copy(), inner.copy(), range(2), [0])
qc.draw()
```
![Image](https://github.com/user-attachments/assets/4b8630d5-64fc-45cb-8c23-8a4d080e37ca)

2. Run `InverseCancellation` on it
```python
from qiskit.transpiler.passes import InverseCancellation
from qiskit.circuit.library.standard_gates import CXGate
InverseCancellation([CXGate()])(qc).draw()
```
![Image](https://github.com/user-attachments/assets/7030af58-f80f-46be-9176-1589fd4c24b3)

Notice that the CX outside got cancelled, but not those inside.

### What should happen?

It should be like `CXCancellation`
```python
from qiskit.transpiler.passes import CXCancellation
CXCancellation()(qc).draw()
```
![Image](https://github.com/user-attachments/assets/fc90c3e9-c01b-49f4-9846-f8dd2eefaa70)

### Any suggestions?

Apply `InverseCancellation` recursively inside the code blocks.

**Comment by 1ucian0** [comment]
The fix is rather straightforward. It seems like just adding the decorator `@control_flow.trivial_recurse` should work. Tagging as `good first issue`.

**Comment by haimeng-zhang** [comment]
I am in. Please assign me.
