### ISSUE TITLE
cx(0,1) gate.to_matrix()

### ISSUE THREAD

**Issue by lmbibbo** [Qiskit/qiskit#13464]
### Environment

- **Qiskit version**: 1.2.4
- **Python version**: 3.10
- **Operating system**: Google Colab

### What is happening?

The gate.to_matrix() function returns an erroneous matrix for the gate cx(0,1). It returns the same matrix as for gate cx(1,0).

### How can we reproduce the issue?

qc = QuantumCircuit(2)
qc.cx(1, 0)
qc.cx(0, 1)

# Iterate through each gate in the quantum circuit
for gate_data in qc.data:
    gate = gate_data.operation  # Get the gate object
    matrix = gate.to_matrix()  # Get the matrix representation of the gate
    print(matrix)

### What should happen?

should answer different matrices for cx(0,1) and for cx(1,0). This is for cx(0,1)
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]]

This would be for cx(1,0).
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]]
Translated with DeepL.com (free version)

**Comment by jakelishman** [comment]
The gate object does not reference the qubits it is applied to, so this is expected. Put another way: if your circuit had 3 qubits in it, this logic would expect the CX matrix to be expanded to include the implicit identities, which can't scale.

**Comment by jakelishman** [comment]
but if you want the matrix form of a (small) circuit, you can do
```python
from qiskit.quantum_info import Operator

Operator(my_circuit)
```

**Comment by lmbibbo** [comment]
I assumed that these were the qubits where they were applied. Marked in bold!

for gate_data in qc.data:
    instruction, qubits, clbits = gate_data
    print(f"Gate: {instruction.name}, Qubits: {qubits}, Clbits: {clbits}")

Gate: x, Qubits: [Qubit(QuantumRegister(2, 'q'), **0**)], Clbits: []
Gate: h, Qubits: [Qubit(QuantumRegister(2, 'q'), **1**)], Clbits: []
Gate: cx, Qubits: [Qubit(QuantumRegister(2, 'q'), **0**), Qubit(QuantumRegister(2, 'q'), **1**)], Clbits: []

**Comment by lmbibbo** [comment]
operator = Operator(gate)

    matriz = operator.data
    display(array_to_latex(matriz))

for the gate cx(0, 1) and for the gate cx(1, 0) gives the same matrix. Mathematically this is not the case

**Comment by jakelishman** [comment]
Yes, a complete circuit instruction is a combination of the gate object and the qubits it's applied to. Your examples keep asking for the matrix of the gate object alone, though - you can see as you do `instruction, qubits, clbits = gate_data` that you're separating the gate object from the qubits it acts on.

A circuit is a full context that contains gates _applied to qubits_. If you want this, the easiest way is to use the `Operator` constructor on a circuit, like I showed above.

**Comment by lmbibbo** [comment]
It is clearly a bug. You can easily distinguish if it is cx(0, 1) from cx(1, 0). And the gate.to_matrix() method should return the correct matrix. 
Gate: cx, Qubits: [Qubit(QuantumRegister(2, ‘q’), **0**), Qubit(QuantumRegister(2, ‘q’), **1**)], Clbits: []
Gate: cx, Qubits: [Qubit(QuantumRegister(2, ‘q’), **1**), Qubit(QuantumRegister(2, ‘q’), **0**)], Clbits: []

**Comment by jakelishman** [comment]
For one further explanation: you are calling the method `Gate.to_matrix`.  The qubits are not part of a `Gate`.  The qubits _are_ attached part of a `CircuitInstruction`, which is what you get when you iterate through `QuantumCircuit`.  You can read more in the documentation: https://docs.quantum.ibm.com/api/qiskit/circuit#module-qiskit.circuit.

If you have further queries about the basic data model, I'd suggest you take them to a help forum like the [Qiskit slack](https://qisk.it/join-slack) rather than the bug tracker.  I'll close this issue now, because there's no bug here, but please feel free to ask for help in the Slack workspace.

**Comment by lmbibbo** [comment]
Do what you want. For me it's a bug.
Create this circuit and see what matrix responds to it.
qc = QuantumCircuit(2)
qc.cx(0, 1)

In the same way you can do this 
operator = Operator(gate)

matriz = operator.data
display(array_to_latex(matriz))

Thanks anyway
