### ISSUE TITLE
Surprising qubit labels in output of `QuantumCircuit.from_instructions(...)`

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit#13469]
### Environment

- **Qiskit version**: 1.3.0rc1
- **Python version**: 3.11
- **Operating system**: macos

### What is happening?

I'd expect `QuantumCircuit.from_instructions`, when applied to an existing `QuantumCircuit`, would create an identical copy. However the `draw` representation of the new circuit does not match that of the original, suggesting there is some difference. I think there should not be any difference between the original circuit and the new circuit, or at least it should be made apparent to the user what the difference is.

### How can we reproduce the issue?

I create a `QuantumCircuit`. When I draw it, the qubits are labeled as "q_0", "q_1", etc.
```
qc = QuantumCircuit(2)
qc.cx(0,1)
print(qc.draw())
print(qc.qubits)
```
Out:
![Image](https://github.com/user-attachments/assets/fdc29cf6-e22b-4fb3-b3ad-6e2ecccd5e64)

Now I try to make an identical circuit using `from_instructions(...)`:
```
qc2 = QuantumCircuit.from_instructions(qc)
print(qc2.draw())
print(qc2.qubits)
```
I thought `qc2` would be identical to `qc`. I inspected some attributes and it appeared to be the same. But the labels displayed on the drawn circuit are different:
![Image](https://github.com/user-attachments/assets/c3a6a4c7-ea16-4a89-8ee0-312759735983)

I tried a few variations on this and did not see a way to produce a circuit where the qubits are labeled as in the original:
```
qc2 = QuantumCircuit.from_instructions(qc, qubits=qc.qubits)
print(qc2.draw())
print(qc2.qubits)
```
Out:
![Image](https://github.com/user-attachments/assets/d6f93549-8058-47b7-9538-a174768e3e4e)

So evidently there is some way in which `qc2` does not match the original `qc`, though I don't understand the nature of this difference. The `qubits` attributes are apparently the same (`qc.qubits == qc2.qubits` is `True`).

### What should happen?

I think there should not be any difference between the original circuit `qc` and the new circuit created by `from_instructions(qc)`, or at least it should be made clear to the user what the difference is.

In the specific test above where we call `draw()`, both circuits should have the same qubit labels.

**Comment by Cryoris** [comment]
It looks like though the qubits are correctly added, the registers of the original circuit are not added to `qc2`, which will cause the comparison to fail. I've also run into a similar problem before and I also think that it can be quite confusing. Our current handling of bits allows quite easily to construct circuits you would expect to compare as equal, but are not, due to how bits and registers are handled.

You can likely resolve this by manually adding the `qregs` to `qc2`. Is there a reason you're not using `copy` here, or was this just a small example to showcase the surprising behavior?

**Comment by jakelishman** [comment]
The reason this happens is that "registers" are purely a circuit-level construction, not an instruction-level construction, and `QuantumCircuit.from_instructions` deals only with an iterable of `CircuitInstruction`s.  Normally to copy a circuit you'd just to `QuantumCircuit.copy`.  `from_instructions` doesn't treat `QuantumCircuit` specially (and it's probably better that way), it just sees it as "some iterator of `CircuitInstruction`.

Another important difference is that `QuantumCircuit.from_instructions` will add the qubits encountered in the order they're encountered, and _only_ those qubits - if a qubit is entirely idle in a circuit, it won't be added.  That's mentioned/implied by the documentation of the separate `qubits` argument, which lets you pre-add a bunch of qubits.

The little introductory paragraph before `QuantumCircuit.from_instructions` explains some of this ([in these docs](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#from_instructions), then scroll up a shade),  but that paragraph probably should move into the main docstring, and we could make it clearer there that registers (and metadata, calibrations, etc) are circuit-level constructs that will not be copied.

**Comment by aeddins-ibm** [comment]
Thanks for the helpful explanations and tips.

So the prefix "q" in the drawing appears only if the qubit belongs to the register named "q", AND that register has been added to the circuit.

In the example above, the qubits were added to the circuit, but the register "q" was not. So even though each qubit is part of register "q", the drawn qubit labels do not include "q" because that register has not been added to the circuit.

Well I'm convinced this is mostly me being confused about the chosen convention rather than a real "issue." I'll go ahead and close this.
