### ISSUE TITLE
`efficient_su2` & co should handle the `num_qubits=1` case

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit#13480]
### Environment

- **Qiskit version**: 1.3.0rc2
- **Python version**: 3.11.9
- **Operating system**: macOS

### What is happening?

Calling some library functions, like `efficient_su2` don't work for `num_qubits=1`, since the entangling gate requires 2 qubits. This should still work, but simply not add an entangling gate.

We should check this edge case for all other functions, as well.

### How can we reproduce the issue?

```python
from qiskit.circuit.library import efficient_su2

efficient_su2(1)
```

### What should happen?

Build a circuit without CX entangling gate. This should be handled in the `efficient_su2` function and adjust the internal call to `n_local`.

**Comment by trigpolynom** [comment]
I'd like to take this one on.

**Comment by Cryoris** [comment]
Great @trigpolynom! You can verify what should happen if you run the circuit-versions of these functions with a single qubit, e.g.
```python
from qiskit.circuit.library import EfficientSU2, efficient_su2

circuit = EfficientSU2(1, flatten=True)
also_circuit = efficient_su2(1)  # should equal ``circuit``
```
We also need to add tests in [this file](https://github.com/Qiskit/qiskit/blob/main/test/python/circuit/library/test_nlocal.py) and add a release note. You can check out the contributing guidelines on how to do that.

Let me know if you have any questions, I'm happy to discuss!

**Comment by trigpolynom** [comment]
Something like this @Cryoris ? https://github.com/Qiskit/qiskit/pull/13523/files
