### ISSUE TITLE
Swap mapper fails with certain inputs

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit#1348]
### Informations

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Mapper issue reported by @maikatakita 

```python
circuit = QuantumCircuit(qr,cr,name='test')
circuit.h(qr[0])
circuit.cx(qr[0],qr[1])
circuit.cx(qr[1],qr[2])
circuit.cx(qr[2],qr[3])
circuit.measure(qr[0],cr[0])
circuit.measure(qr[1],cr[1])
circuit.measure(qr[2],cr[2])
circuit.measure(qr[3],cr[3])
```

```python
from qiskit import compile, Aer
qobj=compile(circuit,
             backend=Aer.get_backend('qasm_simulator'),
             coupling_map = [[1, 0], [1, 2], [2, 3], [4, 3], [4, 10], [5, 4],
                             [5, 6], [5, 9], [6, 8], [7, 8], [9, 8], [9, 10],
                             [11, 3], [11, 10], [11, 12], [12, 2], [13, 1], [13, 12]],
            initial_layout={(qr.name, 0): ('q', 1),
                            (qr.name, 1): ('q', 2),
                            (qr.name, 2): ('q', 3),
                            (qr.name, 3): ('q', 5)})
```

Yields:
```python
MapperError: 'swap_mapper failed: layer 3, sublayer 0, "cx q[3],q[5];\n"'
```

**Comment by maddy-tod** [comment]
Is this an issue you still get? I can't seem to recreate it locally.

**Comment by 1ucian0** [comment]
@ajavadia can you confirm?

**Comment by kdk** [comment]
I was able to reproduce (or maybe a similar error) on the same circuit on master / 5f4102a8065ebf1772cde0acf69f2010b970d569 , `len(qr)==len(cr)==4`,  python3.5 .

Error is `MapperError: 'swap_mapper failed: layer 3, sublayer 0'` from https://github.com/Qiskit/qiskit-terra/blob/5f4102a8065ebf1772cde0acf69f2010b970d569/qiskit/mapper/mapping.py#L374 .
