### ISSUE TITLE
Add missing `AdderGate` class or remove references

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#13501]
### What should we add?

The 1.3.0 release notes referred to an `AdderGate` class, described as: "`AdderGate` implements standard addition including a carry-out" and this is also referred to in several docstrings for specific adder classes. But I have found no class definition for `AdderGate`. Either we should add the missing class or remove the references (I removed the release note for 1.3.0 in #13447 already)

**Comment by alexanderivrii** [comment]
There was an `AdderGate` class during the initial implementation, but it was later renamed to `HalfAdderGate`. Maybe we have indeed missed a few places.

**Comment by ShellyGarion** [comment]
closed by #13502
