### ISSUE TITLE
Doc string of `operation` in ParameterExpression._apply_operation

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit#13511]
It says
```
operation: One of operator.{add,sub,mul,truediv}.
```
But the function is already called also with other operations, for example `pow` in `ParameterExpression.__pow__`.

**Comment by Cryoris** [comment]
Good point, and while this is not user facing it would be nice to have the dev-facing docs correct. Would you like to open a small PR to fix it?
