### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by jrzingel** [Qiskit/qiskit#13518]
Hi all

I'm new to Qiskit and was following the guide in the README but some of the code was not working.

I believe that line 73 is incorrect and should change from

```python
print(f" > Counts: {result[0].meas.get_counts()}")
```

to

```python
print(f" > Counts: {result[0].data["meas"].get_counts()}")
```

Cheers

**Comment by 1ucian0** [comment]
closed via https://github.com/Qiskit/qiskit/pull/13519
