### ISSUE TITLE
qiskit 1.3 breaks Aer?

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#13524]
There seems to be a regression that breaks Aer:
 * https://github.com/Qiskit/qiskit-aer/issues/2270
 * https://github.com/Qiskit/qiskit-aer/actions/runs/12010092555/job/33476456561

I did not investigated deep enough to be sure that is a regression or Aer is doing something wrong.

**Comment by 1ucian0** [comment]
cc @gadial

**Comment by 1ucian0** [comment]
~Maybe dup https://github.com/Qiskit/qiskit/issues/13504 ?~ @Cryoris thinks this is not related.

**Comment by gadial** [comment]
It's a known bug that already has an open PR to fix it:

https://github.com/Qiskit/qiskit-aer/pull/2265

I hope we'll merge soon.

**Comment by 1ucian0** [comment]
In that case, I'm closing this one as it is fully covered by Aer. Thanks!
