### ISSUE TITLE
How to use Qiskit translation pass manager with Clifford + T gate basis?

### ISSUE THREAD

**Issue by alxthm** [Qiskit/qiskit#13574]
Hi ! this is more of a question regarding transpilation in qiskit than an issue (also [posted here](https://quantumcomputing.stackexchange.com/questions/40643/how-to-use-qiskit-translation-pass-manager-with-clifford-t-gate-basis)).

## Context

In qiskit, the translation stage of the transpilation "translates (or unrolls) the gates specified in a circuit to the native basis gates of a specified backend." ([cf doc](https://docs.quantum.ibm.com/guides/transpiler-stages#translation-stage))

For that, the [generate_translation_passmanager()](https://github.com/Qiskit/qiskit/blob/stable/1.3/qiskit/transpiler/preset_passmanagers/common.py#L412-L530) function accepts 2 options for the method argument :
- `"translator"` : applies `UnitarySynthesis / HighLevelSynthesis / BasisTranslator`
- `"synthesis"` : applies `UnitarySynthesis / HighLevelSynthesis / Unroll3qOrMore / Collect2qBlocks / Collect1qRuns / ConsolidateBlocks / UnitarySynthesis / HighLevelSynthesis`

Importantly, from what I understand :
- the `UnitarySynthesis` pass is able to "synthesize gates" by doing approximations. Example : `Rz(5π/4)` -> `Z / T`, with [the Solovay Kitaev plugin](https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.synthesis.solovay_kitaev_synthesis.SolovayKitaevSynthesis) (method = 'sk').
- the BasisTranslator pass is able to replace gates with equivalent gates in the target basis, using the [equivalence library](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.EquivalenceLibrary). Example : `cy` -> `Tdg / Tdg / cx / s`, after doing a graph search into the equivalence library graph.

## Issue

In my case, the desired target basis is clifford + T gate : `{cx, h, s, t}`, rather than rotations + cx.

Using the "translator" method, I am able to transpile circuits containing `rz(theta)` gates, but I am unable to transpile circuits that rely on `rz(theta)` as a target gate in the internals of the BasisTranslator step (e.g. transpiling cz fails if I don't have rz in the target basis).

It seems to me that, [just like explained here](https://quantumcomputing.stackexchange.com/questions/17219/how-to-use-qiskit-transpile-with-clifford-t-basis), a solution would be to
1. first, do the BasisTranslator pass with rotations in the target basis (even though they are not in the final target basis)
2. then only, do the UnitarySynthesis pass

## Questions

I wonder about the best way to combine the UnitarySynthesis and BasisTranslator passes :
- What is the difference between the "translator" and "synthesis" options ? Which one would be best here ?
- If using the "translator" method, does it make sense to simply add another UnitarySynthesis pass at the end of the translation pass ? (and if yes, do we even need multiple UnitarySynthesis passes ? why is the 1st one even necessary ?)
- Is there maybe an even simpler/better way to do it ? Using other qiskit passes ?

**Comment by Cryoris** [comment]
I agree something like `transpile(...., translation_method="synthesis", unitary_synthesis_method="sk")` should work but currently doesn't. Until we figure this out, you can transpile your circuit to `U + your_2q_gate` and then call the `SolovayKitaev` transpiler pass on the output, which will discretize the single-qubit U gates. For example:

```python
import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit.synthesis import generate_basic_approximations
from qiskit.transpiler.passes import SolovayKitaev
from qiskit.quantum_info import Operator
 
circuit = QuantumCircuit(3)
circuit.rxx(0.2, 0, 1)
circuit.ryy(2.5, 1, 2)
 
print(circuit.draw())

# generate the basic approximations (this can be stored locally, as doing this is expensive)
basis = ["h", "s", "t"]
approx = generate_basic_approximations(basis, depth=3)

skd = SolovayKitaev(recursion_degree=7, basic_approximations=approx)

transpiled = transpile(circuit, basis_gates=["u", "cx"])
discretized = skd(transpiled)
 
print(discretized.draw())
print("Error:", np.linalg.norm(Operator(circuit).data - Operator(discretized).data))
```

**Comment by alxthm** [comment]
Thanks for the fast answer 🙏 

I see, so the `synthesis` option is what I want eventually.

In my case, I am writing a custom `PassManagerStagePlugin`. Following your suggestion, in the meantime I was planning to change the `translation` stage from

```
# default passes returned by `generate_translation_passmanager`
[UnitarySynthesis, HighLevelSynthesis, BasisTranslator]
```

to

```
# the custom `translation` stage I need, to be able to transpile circuits for my clifford + T basis
[UnitarySynthesis(method='sk'), HighLevelSynthesis, BasisTranslator(basis_gates=["u", "cx"]), UnitarySynthesis(method='sk')]
```

Just to confirm,

1. from what I see in the doc and code of the `SolovayKitaevSynthesis` unitary synthesis plugin, adding a `UnitarySynthesis(method='sk')` pass should be equivalent to adding a `SolovayKitaev` pass ? or is there a reason to use one rather than the other ?
2. would `[BasisTranslator(basis_gates=["u", "cx"]), UnitarySynthesis(method='sk'), HighLevelSynthesis]` be an option as well for the translation stage ? or do we necessarily need to apply `[UnitarySynthesis, HighLevelSynthesis]` before `BasisTranslator` ?

**Comment by Cryoris** [comment]
1. I haven't tried myself but there shouldn't be a functional difference between the two. But if you specifically design a workflow using Solovay-Kitaev, I would suggest using the pass directly as it avoids any overhead from the `UnitarySynthesis` pass.
2. The `SolovayKitaev` pass should be the last pass running in the translation stage because it needs the circuit in terms of `["u", "cx"]`, so I would expect you can simply append it to the the default passes. (Though note that it generating these basic approximations can be very expensive and you might want to cache them.)

**Comment by alxthm** [comment]
That's clear, thanks a lot !
