### ISSUE TITLE
Typo in docs: Duplicate "each" in QDrift Trotterization method description

### ISSUE THREAD

**Issue by tj-amano** [Qiskit/qiskit#13576]
### URL to the relevant documentation

**Location of the typo**:  
- **URL**: [https://docs.quantum.ibm.com/api/qiskit/synthesis](https://docs.quantum.ibm.com/api/qiskit/synthesis)  
- **Section**: QDrift Trotterization method  

### Select all that apply

- [x] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### **Description of the Issue**

There is a small typo in the Qiskit documentation under the section describing the QDrift Trotterization method. Specifically, the word **"each"** is repeated.

---

**Current text**:  
> The QDrift Trotterization method, which selects each each term in the Trotterization randomly, with a probability proportional to its weight.

**Suggested correction**:  
> The QDrift Trotterization method, which selects each term in the Trotterization randomly, with a probability proportional to its weight.

---

### **Additional Information**

If there's any process to contribute a fix or PR for this documentation, I would be happy to help.

**Comment by beckykd** [comment]
@tj-amano - We would love your contribution!  There are instructions to help you get started here: https://github.com/Qiskit/documentation?tab=readme-ov-file#4-fix-an-open-issue
