### ISSUE TITLE
Need to test all transpiler passes leave input DAG intact

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit#1435]
### What is the expected enhancement?
We have defined transpiler passes as producers of a new DAG, not modifiers of the DAG that they read. As such, we need a test to check that for all passes in `qiskit.transpiler.passes`, the input DAG stays intact.

**Comment by 1ucian0** [comment]
Should it be "Need to test all transpiler transformation passes return the resulting DAG"?

**Comment by 1ucian0** [comment]
Is this check really necessary? The passmanager does things like `dag = pass.run(dag)`.

**Comment by kdk** [comment]
I think this is not an immediate concern. As @1ucian0 points out, the serial structure of the PassManager ensures that each pass terminates before any subsequent pass begins (and passes should not be holding internal state between runs), and there are performance gains to be had for passes which only modify a subset of the DAG (e.g. CXDirection in #3173.) We can revisit in the future if either of these change.

**Comment by mtreinish** [comment]
Not doing this actually makes certain performance optimization tricky to implement. I've had patches in the past that tried to optimize our performance by reducing run time overhead by making static gate decomposition definitions actually static and ran into this: https://github.com/Qiskit/qiskit-terra/pull/1445 and had to abandon it.

**Comment by kdk** [comment]
Agree, unfortunately that cat's already out of the bag. Maybe there is design work that can be done in #3146 to find a way to implement that optimization safely?

**Comment by 1ucian0** [comment]
If I understood the conclusion of the discussion correctly, I'm closing this issue as `wont fix`. Feel free to reopen if I understood correctly...
