### ISSUE TITLE
Create a tutorial example

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit#1442]
On Qiskit docs 2.0 we would like to divide documentation in different types using the [divio framework](https://documentation.divio.com/#about-the-system). For that, we are working on a tutorials audit to see what kind of documentation we already have. It's not been easy because no file fits 100% the framework.

Following @HuangJunye suggestion, having an example of every type of documentation could help us with the categorization.

The idea is convert one of the tutorials we already have in [one that follows divio framework](https://documentation.divio.com/tutorials/). It would be nice to have both to compare the old and the new in order to understand what we need for that update. If we already have an example of tutorial, please, you could just add the link :)

**Comment by HuangJunye** [comment]
Thanks for creating the issue. I will work on that. Please assign me.

**Comment by garrison** [comment]
@agata-branczyk points me to [the second tutorial](https://github.com/qiskit-community/prototype-entanglement-forging/blob/main/docs/1-tutorials/tutorial_2_H2O_molecule_statevector_simulator.ipynb) for the [entanglement forging prototype](https://github.com/qiskit-community/prototype-entanglement-forging) as one example.  (The prototypes team has been writing all its documentation with Divio/Diataxis style in mind.)

**Comment by HuangJunye** [comment]
@garrison That’s great. Thanks for sharing the tutorials for prototypes. Let me take a look at them.

**Comment by HuangJunye** [comment]
I created grover with sampler primitives on qiskit-ibm-runtime repo as an example for the tutorial. 
- PR: https://github.com/Qiskit/qiskit-ibm-runtime/pull/236
- Page: https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/grover_with_sampler.html

**Comment by HuangJunye** [comment]
@garrison You are very familiar with Diataxis framework. Would you like to have a look at the tutorial and give me some feedback?
