### ISSUE TITLE
Create a How-To example

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit#1443]
On Qiskit docs 2.0 we would like to divide documentation in different types using the divio framework. For that, we are working on a tutorials audit to see what kind of documentation we already have. It's not been easy because no file fits 100% the framework.

Following @HuangJunye suggestion, having an example of every type of documentation could help us with the categorization.

The idea is convert one of the tutorials we already have in a [How-To that follows divio framework](https://documentation.divio.com/how-to-guides/). It would be nice to have both to compare the old and the new in order to understand what we need for that update. If we already have an example of How-To, please, you could just add the link :)

**Comment by garrison** [comment]
The [quantum kernel training prototype](https://github.com/qiskit-community/prototype-quantum-kernel-training) has some [how-to guides](https://github.com/qiskit-community/prototype-quantum-kernel-training/tree/main/docs/how_tos).

**Comment by 1ucian0** [comment]
dynamics call how-to guides "user guide" https://github.com/Qiskit/qiskit-dynamics/tree/main/docs/userguide

**Comment by HuangJunye** [comment]
We are planning to move the how-to guide examples from IBM Cloud Runtime doc to qiskit-ibm-runtime repo as examples: https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-choose-backend

**Comment by HuangJunye** [comment]
https://github.com/Qiskit/qiskit-ibm-runtime/issues/289

**Comment by HuangJunye** [comment]
https://github.com/Qiskit/qiskit-ibm-runtime/issues/289 is merged and the how-to guides went live last week: https://qiskit.org/documentation/partners/qiskit_ibm_runtime/how_to.html
