### ISSUE TITLE
circuit.draw(output='mpl) does not draw qubit labels correctly.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#1449]
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: osx

### What is the current behavior?
Using Latex:
<img width="603" alt="screen shot 2018-12-07 at 11 49 43 am" src="https://user-images.githubusercontent.com/1249193/49661112-39c16400-fa16-11e8-8610-70a1d89474e6.png">
Using MPL:
<img width="496" alt="screen shot 2018-12-07 at 11 50 21 am" src="https://user-images.githubusercontent.com/1249193/49661148-4fcf2480-fa16-11e8-8f52-ad065c35d815.png">

**Comment by mtreinish** [comment]
@nonhermitian give #1450 a try, that should fix it
