### ISSUE TITLE
Change the name Lookaheadmapper and basicmapper

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit#1523]
### What is the expected enhancement?
In the folder, it is not clear what is a mapper and what is not. My view (also @ajavadia) is all steps are a mapper. Mapping is all things combined: swap insertion, fix direction, unroll to native gates, etc.

- [x] Unroller
- [ ] LookaheadSwap
- [ ] StochasticSwap should happend in (#1520)
- [ ] BasicSwap  
- [ ] LayoutSelect should happen in (#1499)
- [x] CXDirection (pr #1521)

**Comment by jaygambetta** [comment]
@ajavadia and @1ucian0 are we going to get these done.

**Comment by ajavadia** [comment]
Yes I'll do it.
