### ISSUE TITLE
CX Cancellation does not cancel the sequence cx1, cx2, cx2, cx1

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#1552]
The following code should result in empty circuit after CX cancellation:
```
qr = QuantumRegister(2)
circuit = QuantumCircuit(qr)
circuit.cx(qr[0], qr[1])
circuit.cx(qr[1], qr[0])
circuit.cx(qr[1], qr[0])
circuit.cx(qr[0], qr[1])
```
The current result is:
```
cx q2[0],q2[1];
cx q2[0],q2[1];
```

**Comment by ajavadia** [comment]
No this is by design. You should run the CXCancellation pass in a loop using `property_set.fixed point['depth']`

**Comment by jaygambetta** [comment]
This is correct. You need to run it twice.
