### ISSUE TITLE
Plot_city_state central plane not drawn behind all positive columns

### ISSUE THREAD

**Issue by dime10** [Qiskit/qiskit#3315]
### Information

- **Qiskit Terra version**: 0.10.0
- **Python version**: 3.7.4
- **Operating system**:  Windows 10

### What is the current behavior?
As seen in this image, the plane at z=0 is drawn in front of some of the positive columns. Surprisingly most, but not all, of the columns are drawn this way.
![66311970-fe324780-e90f-11e9-8c39-cf8aaff16559](https://user-images.githubusercontent.com/29467667/67506636-b80a1180-f68d-11e9-835d-ed593d9b4561.PNG)
Other examples:
![image](https://user-images.githubusercontent.com/29467667/67507038-762d9b00-f68e-11e9-996a-6aa20c0c5536.png)

### Steps to reproduce the problem
Plot a state vector with positive amplitudes.

### What is the expected behavior?
Positive columns (z>0) should be drawn in front of the plane, negative columns behind it (this second part seems to work already).

### Suggested solutions
Don't know what is causing this.

**Comment by mrvee-qC** [comment]
# Update for Santa - QGoGP
:white_check_mark: Issue still reproducible as per original author. Any plot with positive and negative columns should reproduce the issue. Example code to reproduce first image:


```
from qiskit.tools.visualization import plot_state_city
plot_state_city([0.5+0.5j , 0.5 +0.5j ,0.5 +0.5j ,-0.5-0.5j],
     title="Ghosts from qiskit past")
```
![Screenshot_83](https://user-images.githubusercontent.com/61380731/145828983-585b02d7-58b8-45b0-93a3-4d67bbfaae7f.png)

Not sure if the right section but it seems to completely mess up for different states! (State vectors are on top of the ss)

#### Anomaly 1 - Statevector [0.191 + 0.462j , 0.191 + 0.462.j , -0.191 + 0.462j , -0.191 + 0.462j]
![Screenshot_82](https://user-images.githubusercontent.com/61380731/145831787-34e45e06-ed77-4b85-8d09-385f8047e07f.png)

#### Anomaly 2 - Statevector [0.354 + 0.354j , 0.5 + 0.j , 0.354 + 0.354j , 0.5 + 0.j]
![Screenshot_81](https://user-images.githubusercontent.com/61380731/145831900-40f07509-d7a1-4876-9837-ca4a85967be5.png)

Will update comment/add more comments if cause is found/fixed.

> Python version 3.9.7
> qiskit-terra version: 0.19.1

**Comment by AlexanderGroeger** [comment]
I'm already working on the other mentioned [issue](https://github.com/Qiskit/qiskit-terra/issues/8413). I could easily tack this on to my work changes. Would someone please assign this task to me?
