### ISSUE TITLE
qiskit.providers.basicaer needs better module level docs

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#3403]
### What is the expected enhancement?
Module level docs need more examples on actual uasage

**Comment by Nisha-Banerjee** [comment]
# Update for gosts_of_github_past
this issue is still valid as more detailed examples on actual uasage in [`qiskit.providers.basicaer`](https://qiskit.org/documentation/apidoc/providers_basicaer.html) is required. The corresponding file is [`_init_.pyfile`](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/providers/basicaer/__init__.py#L13).

**Comment by javabster** [comment]
Hi @shivalee12 apologies for the slow response, things are hectic at the start of the year! I think this is the page that needs some more documentation: https://qiskit.org/documentation/apidoc/providers_basicaer.html?highlight=basicaer

There is currently just one small explanation about what the `BasicAer` module does, it would be good to flesh this out a bit more. For comparison, other module level docstrings have much more detail, like this: https://qiskit.org/documentation/apidoc/circuit.html

Perhaps @nonhermitian or @jakelishman might have some specific suggestions for what's missing from the `BasicAer` docs?

**Comment by jakelishman** [comment]
The main thing missing is a simple example of how to use the simulator objects offered by `BasicAer`.  It can probably just be as simple as showing how to submit a simple circuit, and retrieve the measurement counts, final statevector and final unitary matrix as appropriate (I'm not actually sure BasicAer can do anything more than that, and even that's a struggle).

It would also be good to loudly trumpet that `BasicAer` is not generally suitable for any serious simulation workload, and to point people towards the full implementation of `Aer` instead.

**Comment by ss3398** [comment]
Please assign this to me. I am new to quantum computing and this would be my first issue. I have recently completed a course on quantum computing and am comfortable with python.

**Comment by HuangJunye** [comment]
@ss3398 Thanks for volunteering to help! If you are not sure about how to get started, don't hesitate to reach out.

**Comment by ss3398** [comment]
Cool. I am just waiting to hear from my employer that they have no objections to my working on an open source project (sorry, I should have checked this before).

**Comment by ss3398** [comment]
My employer has approved. So I will work on this now.

**Comment by ShellyGarion** [comment]
This bug does not apply to currently supported versions of Qiskit. Please submit a new issue if the bug still occurs in Qiskit 1.
See https://docs.quantum.ibm.com/migration-guides/qiskit-1.0-features#providers.basicaer
