### ISSUE TITLE
circuit deepcopy too slow: singleton gates

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit#3800]
It is currently very slow to copy a circuit. Among other things, one reason is that circuits are defined over gate instances. So a circuit with 2000 H gates and 5000 CX gates will go through that many copy operations, clearly a waste. Can we modify the datastructures to optimize this?

Along the same lines, there are currently other kinds of information in a gate instance that should be static and known before instantiation, like the name, number of qubits, or definitions (for non-parameterized gates, but also maybe for parameterized ones). It seems like a refactoring is in order.

**Comment by Avhijit-codeboy** [comment]
This milestone has already been achieved.

**Comment by 1ucian0** [comment]
A series of merged PR probably fixed this issue. Closing it. Feel free to reopen it if more specific optimization can be done.

**Comment by Cryoris** [comment]
I believe this issue is about making gates static and only copying the necessary information instead of the entire gate instances. Currently, we still do store 2000 X-gate instances if we have 2000 X gates in a circuit so I don't think this issue can be closed.

**Comment by 1ucian0** [comment]
Reopening. The expected change is refactoring gates as singletons.
