### ISSUE TITLE
transpiled circuit layout refers to original circuit

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#3855]
A [recent issue](https://github.com/Qiskit/qiskit-terra/issues/3851#issuecomment-587094919) raised the problem of how confusing a transpiled circuit layout is. In other words, the result of transpiling `circuit` gives you a `result_circuit` in which `result_circuit._layout` is in the domain of `circuit`.

Should the transpiled circuit make the change to the flat register `q` or be kept in the original naming (holding the layout)?

**Comment by jakelishman** [comment]
The `Layout` linking the physical qubits of `result_circuit` to the virtual ones of `circuit` was always necessary, though it's unfortunate that `Layout` makes the physical qubits harder to work with in the output.

That said, the spirit of the problem should have been solved by #10835, so the `TranspileLayout` class that's now the public `QuantumCircuit.layout` field includes methods to get things like the initial layout suitable for recompilation.
