### ISSUE TITLE
Consolidate synthesis code in qiskit/synthesis directory

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit#4699]
### What is the expected enhancement?

Move over the algorithms from quantum_info/synthesis to transpiler/synthesis.

**Comment by ShellyGarion** [comment]
Make a separate `qiskit.synthesis` directory that contain everything currently under `qiskit.quantum_info.synthesis` and `qiskit.transpiler.synthesis` and `qiskit.extensions`

**Comment by alexanderivrii** [comment]
Hi, may I please work on this issue together with Shelly (@ShellyGarion)? Thanks.
