### ISSUE TITLE
QuantumCircuit.compose does not raise an error with invalid qubits argument

### ISSUE THREAD

**Issue by georgios-ts** [Qiskit/qiskit#4970]
### Information

- **Qiskit Terra version**: master @ b1c9a23
- **Python version**: 3.7.1
- **Operating system**: osx

### What is the current behavior?
`QuantumCircuit.compose` runs normally if `qubits` argument has duplicate values. If you try to compose two circuits after converting to dag, `DAGCircuit.compose` raises an error. Introduced after #4762 .

### Steps to reproduce the problem
```
n = 3
qc = QuantumCircuit(n)
qc.h(range(n))

m = 2
circ = QuantumCircuit(m)
circ.z(range(m))
circ.cx(0, 1)

new_circuit = qc.compose(circ, qubits=[1, 1])
print(new_circuit)


     ┌───┐          
q_0: ┤ H ├──────────
     ├───┤┌───┐┌───┐
q_1: ┤ H ├┤ Z ├┤ Z ├
     ├───┤└───┘└───┘
q_2: ┤ H ├──────────
     └───┘   
```

But 
```
dag_qc   = circuit_to_dag(qc)
dag_circ = circuit_to_dag(circ)

dag = dag_qc.compose(dag_circ, 
                     qubits=[1, 1], inplace=False)


raises DAGCircuitError
```

### What is the expected behavior?
As duplicate values in `qubits` is not a valid input, `QuantumCircuit.compose` should raise an error.

### Suggested solutions
Similar to `DAGCircuit.compose`
```
        # Check the edge_map for duplicate values
        if len(set(edge_map.values())) != len(edge_map):
              raise CircuitError("duplicates in wire_map")
```

**Comment by Cryoris** [comment]
I'm a little hesitant to adding checks in the `compose` method because it might slow down the usage and this use-case is obviously a wrong input, so that users won't be surprised if it doesn't work. But if the DAGCircuitError is too cryptic, we could improve it there? This would not give us additional overhead when users use `compose` correctly but would still give a proper error message.

**Comment by mrvee-qC** [comment]
# Update for Santa:elf:- QGoGP
✅ Error reproducible! Has the same 'duplicates in wire map' DAGCircuitError raised as mentioned by OP

```
from qiskit.converters import circuit_to_dag
from qiskit import QuantumCircuit

n = 3
qc = QuantumCircuit(n)
qc.h(range(n))

m = 2
circ = QuantumCircuit(m)
circ.z(range(m))
circ.cx(0, 1)

new_circuit = qc.compose(circ, qubits=[1, 1])
print(new_circuit)
dag_qc   = circuit_to_dag(qc)
dag_circ = circuit_to_dag(circ)

dag = dag_qc.compose(dag_circ, 
                     qubits=[1, 1], inplace=False)
```
#### Screenshot 

![Screenshot_90](https://user-images.githubusercontent.com/61380731/145870680-618973e3-15f4-4783-bf43-f19dd8d8ba46.png)


Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1
