### ISSUE TITLE
Missing CX gate time in backend parameters

### ISSUE THREAD

**Issue by nelimee** [Qiskit/qiskit#498]
Missing CX gate time in backend parameters

## Expected Behavior
Provide data about `CX` gate application time in the `backend` instances.

## Current Behavior
It is impossible for user to recover automatically the time needed to apply a `CX` gate on a given backend. The information is still given in the [backend log page](https://github.com/QISKit/qiskit-backend-information/blob/master/backends/tenerife/V1/version_log.md) but can't be accessed via the Python API.
```py
from qiskit import register, get_backend
import Qconfig
register(Qconfig.APItoken, Qconfig.config['url'])
ibmqx4 = get_backend('ibmqx4')
print(ibmqx4.parameters)
```
outputs with `pprint` instead of `print` and with some croped parts:
```py
{'backend': 'ibmqx4',
 'fridge_parameters': {'Temperature': {'date': '-', 'unit': '-', 'value': []},
                       'cooldownDate': '2017-09-07'},
 'last_update_date': '2018-05-23T09:56:48.000Z',
 'qubits': [{'T1': {'date': '2018-05-23T09:56:48Z',
                    'unit': 'µs',
                    'value': 50.4},
             'T2': {'date': '2018-05-23T09:56:48Z',
                    'unit': 'µs',
                    'value': 13.5},
             'buffer': {'date': '2018-05-23T09:56:48Z',
                        'unit': 'ns',
                        'value': 10},
             'frequency': {'date': '2018-05-23T09:56:48Z',
                           'unit': 'GHz',
                           'value': 5.24231},
             'gateTime': {'date': '2018-05-23T09:56:48Z',
                          'unit': 'ns',
                          'value': 60},
             'name': 'Q0'},
            # Q1, Q2, Q3, Q4
            ]}
```

## Possible Solution
Include a new field in the `backend.parameters` dictionnary. 
Possible idea:

```py
{'backend': 'ibmqx4',
 'fridge_parameters': {'Temperature': {'date': '-', 'unit': '-', 'value': []},
                       'cooldownDate': '2017-09-07'},
 'last_update_date': '2018-05-23T09:56:48.000Z',
 'qubits': [
              # Q0, Q1, Q2, Q3, Q4
           ],
 'multi_qubits': { [control_qubit0] : { [target_qubit0] : { [CX_gate_info] }, 
                                        [target_qubit1] : { [CX_gate_info] }, #...
                                      },
                   [control_qubit1] : { [target_qubit0] : { [CX_gate_info] }, 
                                        [target_qubit1] : { [CX_gate_info] }, #...
                                      }, #...
                 },
}
```

## Context
I want to be able to estimate as precisely as possible the time needed to execute a given quantum circuit.

## Your Environment

* Version used: qiskit==0.5.2
* Environment name and version (e.g. Python 3.6.1):  
      Python 3.6.5 (default, Apr  4 2018, 15:09:05) 
      [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux

**Comment by dcmckayibm** [comment]
There is a plan to fix this. The format will be similar to what you suggest.

**Comment by delapuente** [comment]
Pinging @jaygambetta, @dcmckayibm and @ajavadia. Are there plans to include this kind of information?

**Comment by jaygambetta** [comment]
Yes but it goes in the properties that comes from the api. It will not happen until come Maine calibrations and parameters and get a new command in api

**Comment by delapuente** [comment]
Putting "on hold" until the feature in the API is ready.

**Comment by jaygambetta** [comment]
Closing as this is really part of the API and when the API changes this information will update as such.
