### ISSUE TITLE
Inverting a quantum circuit

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit#507]
I can create a circuit for generating arbitrary quantum superposition with `initialize()` function. 
I know there is a call to `inverse()` function within the `initialize()`. So, it should be easy to do that (just do not execute that call to `inverse()`). 

But I cannot find a way to inverse a circuit I obtain from the `initialize()` nor for any quantum circuit that I have. 

## Expected Behavior

Access to `inverse()` function, or, at least an example of using `CompositeGate` that supports operation to invert the gate.

## Current Behavior

There seems to be no test case and examples of using `CompositeGate` from the `initialize()`. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.5.2
* Environment name and version (e.g. Python 3.6.1): Python 3.6.x
* Operating System and version: MacOSX

**Comment by ajavadia** [comment]
`QuantumCircuit`s are not in general reversible (could contain measure or reset). `CompositeGate`s are reversible, and a simple call to `inverse()` on any CompositeGate should do the trick. Initialize is just one example of a CompositeGate.

As for tests, they are added in #573. I agree we should have more examples for the CompositeGate and make it easier to use (see #316), but I think this current issue is resolved. Feel free to reopen if your problem persists.
