### ISSUE TITLE
Bug in circuit addition

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit#511]
**WARNING**: *All the circuits I was testing were generated with `initialize()`* 

The circuit can be constructed by combining two or more circuit. But adding circuits obtained from `initialize()` gives the wrong result. When having `circuitC = circuitA + circuitB` what we get is `circuitC = circuitA.inverse() + circuitB.inverse()`. 

## Expected Behavior

`circuitC = circuitA + circuitB` instead.

## Current Behavior

`circuitC = circuitA + circuitB` results in the application of `circuitA.inverse() + circuitB.inverse()`.

## Possible Solution

No idea 

## Steps to Reproduce (for bugs)

1. Yeast
![yeast](https://user-images.githubusercontent.com/15240898/40554747-b0f2f5cc-6081-11e8-82c2-3f26d6cd7628.png)

2. InverseYeast
![invyeast](https://user-images.githubusercontent.com/15240898/40554779-cc84e160-6081-11e8-9f8b-7e36d355ca80.png)

3. Yeast + InverseYeast
![yeast_invyeast](https://user-images.githubusercontent.com/15240898/40554785-d32fea5a-6081-11e8-9fa8-a7e46b0cae5b.png)

4. The case below seems more complicated... 

Yeast + Protozoan = ??? (unexpected circuit??) 

![image](https://user-images.githubusercontent.com/15240898/40554923-509c56a4-6082-11e8-9ba7-97dda7bea773.png)

## Your Environment

* Version used: 0.5.2
* Environment name and version (e.g. Python 3.6.1): Python 3.6.x
* Operating System and version: MacOSX

**Comment by ajavadia** [comment]
@ismaila-at-za-ibm seems to have worked on a fix.

**Comment by diego-plan9** [comment]
Seems to be closed by #534 - @rraymondhp , could you test and reopen if necessary?
