### ISSUE TITLE
ParameterVector support for Schedules

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit#5233]
### What is the expected enhancement?

Currently, `QuantumCircuit`s support `assign_parameters` with `ParameterVector` input. The task is to add support similarly for `Schedule`s, which now support parameter assignment as well.

**Comment by alejomonbar** [comment]
can I try this one?

**Comment by lcapelluto** [comment]
Yes, please! Let me know if you need help. I would start by looking in `circuit/quantumcircuit.py` and expect to make changes in `pulse/schedule.py`. (Plus a reno note and tests)

**Comment by Husain0007** [comment]
Hello, @lcapelluto I am a first-time Open Source contributor, do you mind if I take a look at the issue?

**Comment by 1ucian0** [comment]
Hi @alejomonbar ! any progress?

**Comment by alejomonbar** [comment]
Hi @1ucian0. Yes, I just got some feedback from @lcapelluto but I have this question https://github.com/Qiskit/qiskit-terra/pull/5240#issuecomment-793194776 for concluding with this issue.

**Comment by rupeshknn** [comment]
This issue can be **closed** as this functionality is available in the current version of qiskit.

```python

from qiskit import pulse
from qiskit.pulse import Schedule
from qiskit.circuit import ParameterVector


schedule = pulse.Schedule()
parameters = ParameterVector("θ", 2)
gate = pulse.Gaussian(640, parameters[0], parameters[1])
schedule += pulse.Play(gate, pulse.DriveChannel(0))
schedule.assign_parameters({parameters:[0.75, 160]})

# Schedule((0, Play(Gaussian(duration=640, sigma=θ[1], amp=θ[0], angle=0), DriveChannel(0))), name="sched2")
```

**Comment by arthurostrauss** [comment]
@rupeshknn This issue should actually remain open, as the output schedule does not carry the assigned parameter values but maintain the ParameterVectorElements themselves.
