### ISSUE TITLE
`StateFn` makes `OperatorStateFn` out of `PauliOp` or `ListOp` containing anything

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit#5732]
`StateFn` is meant to construct something representing a quantum state, pure or mixed.
`OperatorStateFn` is meant to represent a density operator. But, for some objects, such as a `PauliOp` or a `ListOp` containing anything, `StateFn` constructs a `OperatorStateFn`, which does not agree with these semantics.

```python
In [1]: from qiskit.aqua.operators import *                                                                                                        

In [2]: StateFn(ListOp([X, Y]))                                                                                                                    
Out[2]: OperatorStateFn(ListOp([PauliOp(Pauli(z=[False], x=[True]), coeff=1.0), PauliOp(Pauli(z=[True], x=[True]), coeff=1.0)], coeff=1.0, abelian=False), coeff=1.0, is_measurement=False)

In [3]: StateFn(ListOp([1, "zebra"]))                                                                                                              
Out[3]: OperatorStateFn(ListOp([1, 'zebra'], coeff=1.0, abelian=False), coeff=1.0, is_measurement=False)
```

This behavior is more or less relied on in the test suite. For example here https://github.com/Qiskit/qiskit-aqua/blob/63b5029f739e30dfd08bb6321d3567b1f08c40a6/test/aqua/operators/test_aer_pauli_expectation.py#L71-L72

and  here https://github.com/Qiskit/qiskit-aqua/blob/63b5029f739e30dfd08bb6321d3567b1f08c40a6/test/aqua/operators/test_aer_pauli_expectation.py#L98-L99

In the latter example, we have
```python
In [6]: StateFn(X)                                                                                                                                 
Out[6]: OperatorStateFn(PauliOp(Pauli(z=[False], x=[True]), coeff=1.0), coeff=1.0, is_measurement=False)
```
But `X` is not a density operator (not trace 1 or positive).

The results of the tests are apparently correct and meaningful, but the intermediate steps need to be cleaned up conceptually.

Aqua master commit 63b5029f

**Comment by woodsp-ibm** [comment]
Opflow is now deprecated soon to be removed. New features/enhancements are no longer a consideration.
