### ISSUE TITLE
add Spanish, Mexico translation

### ISSUE THREAD

**Issue by joseluisrg** [Qiskit/qiskit#581]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
None. Requesting translation addition for Spanish. 

- What is the current text that needs to be fixed or removed? (You can copy and paste)
No fixes rather requesting translation addition for Spanish. 

- What should the documentation say instead?
Should expand to Spanish. 

- Are there other related issues or pull requests about this bug?
No. 

## Does existing documentation need to be updated with new content?

- Which files need to be updated?
All files for translation as defined by Crowdin.

- What content needs to be updated or replaced? (You can copy and paste)
All files for translation as defined by Crowdin

- What new content needs to be added?
Spanish language content for Spanish speakers. This can be the basis for other Spanish derivatives like Castillian or further language particularizations.

**Comment by derivation** [comment]
Hi @joseluisrg Thanks for your request. We're starting to discuss what it takes to start up a new language. We started with Japanese, where we had a community leader who recruited about 10 or so volunteers who all use Qiskit. Do you know where (online or in-person) most people who would be interested in a Spanish translation of Qiskit congregate / read / publish? Do you think you could gather them to comment on this thread to show their interest in helping?

**Comment by joseluisrg** [comment]
Hello Paul, I touched base with our local IBM Q Ambassador and she has gathered 10 Spanish speakers (including me and her), so yes we can help. We will ask them to join this thread. Thanks.

**Comment by sita158** [comment]
Hi Paul, we are about 14 Qiskit users interested in helping (counting me and Jose Luis). I have asked them to comment in this thread, so that you can identify us... Thank you.

**Comment by terebikun** [comment]
Hello! 
you can count me in on this one.

**Comment by balo215** [comment]
Hi! 
I'm interested too.
Regards.

**Comment by SooluThomas** [comment]
Spanish, Mexico translations have been enabled in CrowdIn. Please follow the [steps for contributing to documentation localization](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation). Thank you.

**Comment by derivation** [comment]
I spoke with @sita158 off-thread. She is going to continue to organize the community around Spanish (Mexico).

**Comment by derivation** [comment]
@SooluThomas I recommend publishing the Spanish, Mexico localization after the community translates

- [ ] https://qiskit.org/documentation/
- [ ] https://qiskit.org/documentation/install.html
- [ ] https://qiskit.org/documentation/getting_started.html

**Comment by SooluThomas** [comment]
@derivation Sounds good!

**Comment by liobas** [comment]
Hi,

I am in! 
regards.

**Comment by marmotae** [comment]
I'm all in for this one
Cheers 
Balta

**Comment by juanmontalvog** [comment]
Count me in! Regards

**Comment by SooluThomas** [comment]
@terebikun @balo215 @liobas @marmotae @juanmontalvog Please follow the [steps for contributing to documentation localization](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation). Here's a sample PR (https://github.com/Qiskit/qiskit/pull/580). Thank you.

**Comment by jkmartin098** [comment]
I'd like to join

**Comment by SooluThomas** [comment]
Since we have added Spanish(Mexico) in Crowdin, I'm closing this issue. Reopen if need be.

**Comment by derivation** [comment]
@SooluThomas keep this open until Spanish can be displayed in the live doc web page.

**Comment by cristeam2** [comment]
Hi

> Count me in! Regards

+1 Me too

**Comment by nonhermitian** [comment]
Can you please move this issue here: https://github.com/Qiskit/qiskit-translations if needed
