### ISSUE TITLE
Transpiler may permute qubit ordering in statevectors, but not density matrices

### ISSUE THREAD

**Issue by Serock3** [Qiskit/qiskit#5839]
### Information

- **Qiskit Terra version**: 0.16.4
- **Python version**: 3.8.5
- **Operating system**: Windows 10 (running through WSL)

### What is the current behavior?
Similar issues have been noted before (https://github.com/Qiskit/qiskit-terra/issues/2980, https://github.com/Qiskit/qiskit-terra/issues/5350, https://github.com/Qiskit/qiskit-terra/issues/4608), but I wanted to add how density matrices behave.

After transpiling the circuit the state vector (may be) permuted, this only affects snapshots of the state vector and not density matrices or measurements. There are two causes of this. First, the layout the transpiler chooses. This can be retrieved from `transpiled_circ._layout`. Second, the SWAPs inserted by the routing method permutes the qubit ordering. This can change throughout the circuit, but I don't know of any way to get this information.

### Steps to reproduce the problem
This circuit creates a circuit for a device with no connectivity between qubit 1 and 3. Which causes the transpiler to both permutate the layout and insert SWAPs. It takes three snapshots throughout the operation and compares the normal circuit to its transpiled version using both state vector and density matrix snapshots. 

```python
from qiskit import QuantumCircuit,QuantumRegister, Aer, execute
from qiskit.compiler import transpile
from qiskit.quantum_info.states.measures import state_fidelity
from IPython.core.display import display

# Create circuit
circ = QuantumCircuit(3)
circ.x(0)
circ.cnot(0,1)
circ.snapshot('snap1', snapshot_type='statevector')
circ.snapshot('snap1', snapshot_type='density_matrix')
circ.cnot(0,2)
circ.snapshot('snap2', snapshot_type='statevector')
circ.snapshot('snap2', snapshot_type='density_matrix')
circ.cnot(1,2)
circ.snapshot('snap3', snapshot_type='statevector')
circ.snapshot('snap3', snapshot_type='density_matrix')
circ.measure_all()

transpiled_circ = transpile(circ, coupling_map=[[0,1],[1,0],[1,2],[2,1]],optimization_level=2)

display(circ.draw())
display(transpiled_circ.draw())

results = execute(circ,Aer.get_backend('qasm_simulator')).result()
statevector1 = results.data()['snapshots']['statevector']['snap1'][0]
statevector2 = results.data()['snapshots']['statevector']['snap2'][0]
statevector3 = results.data()['snapshots']['statevector']['snap2'][0]
density_matrix1 = results.data()['snapshots']['density_matrix']['snap1'][0]['value']
density_matrix2 = results.data()['snapshots']['density_matrix']['snap2'][0]['value']
density_matrix3 = results.data()['snapshots']['density_matrix']['snap3'][0]['value']

results = execute(transpiled_circ,Aer.get_backend('qasm_simulator')).result()
statevector_transpiled1 = results.data()['snapshots']['statevector']['snap1'][0]
statevector_transpiled2 = results.data()['snapshots']['statevector']['snap2'][0]
statevector_transpiled3 = results.data()['snapshots']['statevector']['snap3'][0]
density_matrix_transpiled1 = results.data()['snapshots']['density_matrix']['snap1'][0]['value']
density_matrix_transpiled2 = results.data()['snapshots']['density_matrix']['snap2'][0]['value']
density_matrix_transpiled3 = results.data()['snapshots']['density_matrix']['snap3'][0]['value']

print('Fidelity between transpiled and normal statevector snapshots')
print('snap 1',state_fidelity(statevector_transpiled1,statevector1))
print('snap 2',state_fidelity(statevector_transpiled2,statevector2))
print('snap 3',state_fidelity(statevector_transpiled3,statevector3))
print('\nFidelity between transpiled and normal density matrix snapshots')
print('snap 1',state_fidelity(density_matrix_transpiled1,density_matrix1))
print('snap 2',state_fidelity(density_matrix_transpiled2,density_matrix2))
print('snap 3',state_fidelity(density_matrix_transpiled3,density_matrix3))
print('Counts normal: ',results.get_counts(circ))
print('Counts transpiled: ',results.get_counts(transpiled_circ))
```

Result of running:

Circuit pre transpiling
![image](https://user-images.githubusercontent.com/16863941/107639048-ad073600-6c70-11eb-88d1-b7a247c718a7.png)

Circuit after transpiling
![image](https://user-images.githubusercontent.com/16863941/107640492-a8dc1800-6c72-11eb-97c0-dfc02590746e.png)

```
Fidelity between transpiled and normal statevector snapshots
snap 1 0.0
snap 2 1.0
snap 3 0.0

Fidelity between transpiled and normal density matrix snapshots
snap 1 1.0
snap 2 1.0
snap 3 1.0
Counts normal:  {'011': 1024}
Counts transpiled:  {'011': 1024}
```

Note how the fidelity between the state vectors of the normal and the transpiled circuit goes from 0 to 1 to 0 again, as the permutation changes from the inserted SWAPs. The snapshot of the density matrix is never permuted, neither are the measurements.
### What is the expected behavior?
The snapshots of the state vector should undo the permutation, as it does for density matrix snapshots.

### Suggested solutions

Not sure.

**Comment by ajavadia** [comment]
Interesting, I agree the snapshots should undo permutations as the original intent of the snapshot is to save information about the original circuit (it is easy to keep track of the permutations, starting from layout and going past each swap). 

I doubt this is done currently for density matrices, however, so seems like something is happening by chance to cause the permutation to be correct.

**Comment by chriseclectic** [comment]
Density matrix snapshots behave quite differently to statevector.
* Statevector is always defined on full width of circuit and ignores the ordering of qubits in its qarg. So if you permute qubits instructions the statevector will change.
* Density matrix is defined as the reduced density matrix on the specified qubits in the qargs of the instruction, so changing qubits arg will permute the returned density matrix.

Hence if you permute qubits in your circuit, but also permute qubits in the density matrix snapshot to account for this, the final returned density matrix should be unchanged.

Maybe in the future we could add ability to permute qubits in the save statevector qubits arg (as long as its still defined across all qubits), and then it would behave like the density matrix one does.

**Comment by ajavadia** [comment]
Ok I agree the Statevector snapshot should be constrained to be defined over all qubits, but I don't think it should be constrained to be defined over qubit order 0..N-1. We should allow that to be permuted.

**Comment by chriseclectic** [comment]
Yeah it would be good to have but simulators don't support computing that permutation at the moment. It would have to be an added feature.

**Comment by fs1132429** [comment]
I am new and I would like to work on this issue if its okay.

**Comment by epelaaez** [comment]
Hi @chriseclectic, is the consensus that the feature to compute permutations of the statevector should be added? If so, I'd like to work on it if possible.

**Comment by jakelishman** [comment]
Since the snapshot instructions don't exist in Qiskit 1.0 any more, I'll close this issue as obsolete.  The "save" functionality is now specific to simulators; there's functionality along these lines in Qiskit Aer, which would be the right place to go if there's further issues about this.

**Comment by NathanPaceydev** [comment]
This is still a real issue. Qiskit remaps measurement results after transpilation, but does not remap save_statevector or other snapshot instructions, so the simulator returns states in the physical qubit order created by the transpiler, not the user’s logical order.

This causes major problems in realistic workflows:

QEC / surface codes: Stabilizers, syndrome extraction, and multi-cycle coherence all rely on fixed logical qubit indices. With SWAPs inserted during routing, mid-circuit statevectors become permuted, making it impossible to track the logical state or apply corrections correctly.

Backend-aware transpilation: Sometimes you must transpile (e.g., ECR connectivity, native RZ/CX). But even then, you still need the simulator to reflect the same logical state so you can validate each QEC cycle. Otherwise, how could anyone implement or test surface code logic on hardware if the simulator cannot guarantee consistent logical ordering across cycles?

Custom noise models and mid-circuit debugging: Operators and snapshots target the wrong qubits when ordering changes mid-program.

Measurements already obey logical ordering; statevectors should as well. Simulators need an option that guarantees all saved states follow the user’s logical qubit order, even after transpilation routing.

**Comment by jakelishman** [comment]
As I explained in the previous comment as the reason I closed this issue, this is no longer the domain of Qiskit, since the instructions don't belong to us and we are not a simulator.  All these things would have to be tackled on Aer (which unfortunately has little maintenance and less feature development right now).

The Qiskit transpiler already should track enough information, and it actually _will_ be remapping the qubits in the actual `SaveStatevector` instruction (e.g. look at `qc.data[<whatever>].qubits` before and after transpilation, it's just that Aer presumably doesn't re-permute said statevector (and there's additional complications from layout expansion). The initial layout after transpilation and final layout after routing are available as `QuantumCircuit.layout.initial_index_layout()` and `.final_index_layout()` respectively, so given those, and the `CircuitInstruction.qubits` field I mentioned previously, it should be possible to manually re-permute the statevector you're interested in.

**Comment by NathanPaceydev** [comment]
Thanks for the clarification. It’s worrying to hear that this now falls outside Qiskit’s scope and that Aer isn’t actively maintained. Fault-tolerant design, surface codes, and QEC workflows fundamentally rely on consistent logical qubit ordering across cycles, so it’s difficult to see how one can reliably validate or prototype fault-tolerant circuits if simulators don’t guarantee stable logical statevector ordering.

I understand that the transpiler tracks layouts (initial_index_layout, final_index_layout) and that the CircuitInstruction.qubits fields change accordingly. My problem is ensuring this works reliably across many cycles of a surface code where the transpiler sometimes introduces permutations and sometimes does not. For distance-d surface codes, the layout varies with d, and we need to compare the logical statevector after each cycle to track fidelity. Without a stable, guaranteed mapping, state comparison becomes ambiguous.

What would be the recommended “manual” method to consistently reorder the Aer statevector into logical-qubit order for each cycle

**Comment by NathanPaceydev** [comment]
Thank you Jake! I got the permutations of the statevector using this:

```python
def extract_save_qubit_orders(transpiled):
    """
    Return list of (label, qubit_order_list)
    where qubit_order_list gives the physical qubits used
    by that SaveStatevector instruction at that moment.
    """
    save_info = []

    for inst, qargs, cargs in transpiled.data:
        if inst.name == "save_statevector":
            label = inst.label  # read label string
            qubit_order = [transpiled.find_bit(q).index for q in qargs]
            save_info.append((label, qubit_order))

    return save_info
```

Then doing a bitwise permutation of the state vector:
```python
def permute_sv(sv, qubit_order):
    """
    sv: numpy statevector (complex array)
    qubit_order: list where qubit_order[logical] = physical qubit index
                 in the ordering used by the save instruction

    This restores the statevector into logical [0,1,2,...] order.
    """
    n = len(qubit_order)
    new_sv = np.zeros_like(sv)

    for idx in range(len(sv)):
        # physical bits in the statevector as output by Aer
        phys_bits = [(idx >> i) & 1 for i in range(n)]

        # reorder into logical order
        log_bits = [ phys_bits[qubit_order[logical]] for logical in range(n) ]

        # compute new index in logical basis ordering
        new_idx = sum(log_bits[i] << i for i in range(n))

        new_sv[new_idx] = sv[idx]

    return new_sv
```

Using these, one can use the extracted state vectors from their circuit and permute them using the ordering kept in the data for each state vector.

I could use initial and final ordering too, but this does not work for many cycles which have many permutations, which is the problem for QEC. A note, our code only supports barrier, not statevector readouts, but you can also use the barrier ordering list, just change: `        if inst.name == "barrier":
`

I would think this could be a good addition to AER or any other Qiskit Simulator, but I understand that in real hardware, you, of course, cannot access a state vector.
