### ISSUE TITLE
Evaluating expectations having used QuantumCircuit.isometry gives wrong results with StateFn

### ISSUE THREAD

**Issue by anedumla** [Qiskit/qiskit#6004]
### Information

- **Qiskit Terra version**: 0.17.0
- **Python version**: 3.8.3
- **Operating system**: Windows 10 Enterprise 64-bit

### What is the current behavior?
```python
>>> vector = [1.0, -2.1, 3.2, -4.3]
>>> init_state = vector / np.linalg.norm(vector)
>>> num_qubits = int(np.log2(len(vector)))
>>> qc = QuantumCircuit(num_qubits)
>>> qc.isometry(init_state, list(range(num_qubits)), None)
<qiskit.circuit.instructionset.InstructionSet object at 0x00000254691FCD60>
>>> (~StateFn(I^I) @ StateFn(qc)).eval()
(5.8e-17+1.0000000000000002j)
>>> (~StateFn(qc) @ StateFn(qc)).eval()
(5.8e-17+1.0000000000000002j)
```

### Steps to reproduce the problem

See above.

### What is the expected behavior?

The output should be 1.

**Comment by jlapeyre** [comment]
The problems seems to be that, for the input above, this method returns an incorrect vector
https://github.com/Qiskit/qiskit-terra/blob/90387a20be329f3752c4acfceb2420f89c895178/qiskit/opflow/state_fns/circuit_state_fn.py#L215-L227

In particular, I'm pretty sure the problem is not in opflow, but in BasicAer. Or, perhaps BasicAer does not guarantee preserving the global phase? It may be relevant (or not) that the initial state actually prepared by `qc.isometry` above differs from that of `init_state` by a phase of `exp(i 5pi/4)`

Some solutions are:
* find the bug
* convert the circuit to a matrix with `Operator`. But, this is inefficient in general.
* Use a different simulator. In fact, I recall talk of removing `BasicAer`.

**Comment by Cryoris** [comment]
> Use a different simulator. In fact, I recall talk of removing BasicAer.

I think we should move to using `Statevector` over `BasicAer` anyways. Does that fix this particular problem?

**Comment by Cryoris** [comment]
I tracked the issue down to the following. It seems that `BasicAer` gives different results on the inverse of the isometry than the `Statevector` class (up to a global phase), which is  the root of this error:
```python
import numpy as np
from qiskit import QuantumCircuit, BasicAer, transpile, execute
from qiskit.opflow import StateFn, I
from qiskit.quantum_info import Statevector

def basicaer(qc):
    return execute(qc, BasicAer.get_backend('statevector_simulator'), optimization_level=0).result().get_statevector()

vector = np.array([1, 2, 3, 1])
iso = QuantumCircuit(2)
iso.isometry(vector / np.linalg.norm(vector), [0, 1], None)
iso = iso.inverse()  # comment this and there's no phase difference

basicaer_sv = basicaer(iso)
direct_sv = Statevector(iso)
print('BasicAer', basicaer_sv)
print('Statevector', direct_sv)
print('Equiv?', direct_sv.equiv(basicaer_sv))  # True
print('Phase difference:', direct_sv.data[0] / basicaer_sv[0])  # 0+1j
print()

transpiled = transpile(iso, basis_gates=['rx', 'ry', 'rz', 'u', 'cx'], optimization_level=0)
basicaer_sv = basicaer(transpiled)
direct_sv = Statevector(transpiled)
print('BasicAer', basicaer_sv)
print('Statevector', direct_sv)
print('Equiv?', direct_sv.equiv(basicaer_sv))  # True
print('Phase difference:', direct_sv.data[0] / basicaer_sv[0])  # 1+0j
```
@chriseclectic do you have an idea where this could be coming from?

**Comment by Cryoris** [comment]
#6045 fixes this error in the representation you pointed out above, but not if you change it to 
```
>>> (~StateFn(qc) @ (I^I) @ StateFn(qc)).eval()
```

**Comment by ShellyGarion** [comment]
This bug does not apply to currently supported versions of Qiskit. Please submit a new issue if the bug still occurs in Qiskit 1.*.
See https://docs.quantum.ibm.com/migration-guides/qiskit-opflow-module.
