### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit#610]
I want to request for adding Chinese translation for Qiskit documentations. Meanwhile, I will look for contributors to join the efforts.

**Comment by revilooliver** [comment]
Hi, I am interested in contributing to Chinese translation.

**Comment by HuangJunye** [comment]
@revilooliver That's great! Thank you. I have gathered another 3 people on Slack for the translation.  We will need about 10 people to have enough supports for a new language addition. Meanwhile, can you ask around for more people to join?

**Comment by revilooliver** [comment]
Actually I am Ji Liu from the Slack channel :)  I can find one or two more people to join us.

**Comment by JoeyXLiu** [comment]
Hey, this is Joey Liu from the Slack channel :)

**Comment by itsuka021** [comment]
Hello, I would like to join and my name in slack is BaiSiang

**Comment by tbcdebug** [comment]
Hi, I am interested in contributing to Chinese translation as well.

**Comment by Hans0124SG** [comment]
I want to contribute to Chinese translation team. My name in Slack is Wang Han.

**Comment by HuangJunye** [comment]
Hi all, thanks for your interests! We have 6 people now, will need 4 more to join before we can request for adding Chinese localization. Can you please ask around if your friends are interested in this project?

**Comment by TonySong97** [comment]
Hi, I would like to join this project. Thank you for bringing this up :)

**Comment by XYShe** [comment]
Hey I am also interested! My name is Xinyang she.

**Comment by jnmupkucas** [comment]
Hello, Thank you for bringing this up. I am not very familiar with this field, but I am very interested. I hope to join the project to learn about it and contribute as much as I can.

**Comment by kobe-ding** [comment]
Hi I'm interested in joining this project! My name is Chaoxin Ding.

**Comment by viviwang1008** [comment]
Hi Junye, I am not an expert in this field, but I would like to contribute to the project. Wei WANG.

**Comment by tbcdebug** [comment]
I think we have enough people?

**Comment by HuangJunye** [comment]
@SooluThomas @veenaiyuri Good news! We have gathered more than 10 people for the Chinese localisation. Can we add Chinese to Crowdin? How do we proceed from here?

**Comment by veenaiyuri** [comment]
Junye,
That is really good news indeed!
Currently our management team is trying to support your effort by making sure we have an IBMer who speaks mandarin to be a focal to support you all from within the organization. We will let you know as soon as we figure out who would be appropriate for this role. Thanks! 

Yuri

**Comment by HuangJunye** [comment]
Thanks Yuri!

**Comment by ForeverZyh** [comment]
Hi, I am also interested. My name is Yuhao Zhang.

**Comment by qslumin** [comment]
Hi, I am also glad to join in. Thanks!  :)

**Comment by TerryBreaksButterfly** [comment]
Hi, Junye,

Count me in. I'm Terry Suun.

**Comment by nonhermitian** [comment]
Can you please move this issue here: https://github.com/Qiskit/qiskit-translations if needed
