### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by AlexAlper** [Qiskit/qiskit#616]
https://crowdin.com/project/qiskit-docs
I want to start translating into Russian
Can you add the Russian language?

**Comment by SooluThomas** [comment]
Thanks for your interest in Contributing to Qiskit Localization. Please read the descriptions of the different roles in the [Blog Post](https://medium.com/qiskit/qiskit-in-my-language-is-qiskit-73d4626a99d3) (How to get involved section).

For more info: https://github.com/Qiskit/qiskit/issues/600#issuecomment-540041562

> Hi @raffmiceli, have you read the descriptions of the different roles in the [Blog Post](https://medium.com/qiskit/qiskit-in-my-language-is-qiskit-73d4626a99d3) (How to get involved section)?
> To get a language started, we need to have someone who will commit to being the *translation lead*, then there needs to be at least one *proofreader* to get a language started. 
> Which role are you interested in?

**Comment by AlexAlper** [comment]
> Thanks for your interest in Contributing to Qiskit Localization. Please read the descriptions of the different roles in the [Blog Post](https://medium.com/qiskit/qiskit-in-my-language-is-qiskit-73d4626a99d3) (How to get involved section).
> 
> For more info: [#600 (comment)](https://github.com/Qiskit/qiskit/issues/600#issuecomment-540041562)
> 
> > Hi @raffmiceli, have you read the descriptions of the different roles in the [Blog Post](https://medium.com/qiskit/qiskit-in-my-language-is-qiskit-73d4626a99d3) (How to get involved section)?
> > To get a language started, we need to have someone who will commit to being the _translation lead_, then there needs to be at least one _proofreader_ to get a language started.
> > Which role are you interested in?

 I want to be a translator into Russian

**Comment by lzdanski** [comment]
Hi @AlexAlper, we're still looking for someone who can volunteer to be translation lead and a proofreader. I'm adding the `help wanted` label and exploring some other ways to share this with the community. Thanks for your patience!

**Comment by ndv87** [comment]
> Hi @AlexAlper, we're still looking for someone who can volunteer to be translation lead and a proofreader. I'm adding the `help wanted` label and exploring some other ways to share this with the community. Thanks for your patience!

I can be a proofreader.

**Comment by nonhermitian** [comment]
Can you please move this issue here: https://github.com/Qiskit/qiskit-translations if needed
