### ISSUE TITLE
Inconsistency in `TwoLocal(..., entanglement_blocks=...)`

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#6185]
From  https://quantumcomputing.stackexchange.com/questions/16922/unable-to-use-iswap-in-qiskit-twolocal-entangling-block

### What is the expected enhancement?

Not all the standard library can be specified "by name" in `TwoLocal(..., entanglement_blocks=...)`. This creates confusion. IMO, 'by name' is just a source of problem and the parameter should be set `by instance`.

**Comment by Cryoris** [comment]
I see your point, but it's just so much more convenient to set by name than importing the gates and I think we would really deteriorate the UX if we don't allow it. We can raise a better error or maybe automate improve how gates are selected by name eg by importing all gates and checking their name or so.

**Comment by javabster** [comment]
Proposed solution from discussion with @Cryoris:

It's a lot nicer for the user to be able to set by name so would be best if we could make that work. Also the current TwoLocal class uses a hard coded `valid_layers` dictionary to get the required gates which is not ideal. So we suggest the following:

- Remove `valid_layers` dictionary in `two_local.py` and instead import all the standard gates (so we can iterate over them to get the required gate by name)
- Add  a static method to every standard gate that returns the number of parameters (so for TwoLocal we can instantiate and also get the number of qubits for the required gate)

**Comment by jakelishman** [comment]
We fixed this at some point - probably #12009.
