### ISSUE TITLE
Max Likelihood Amplitude Estimator applies post processing twice to the confidence interval

### ISSUE THREAD

**Issue by Francesco-Benfenati** [Qiskit/qiskit#6243]
### Information

- **Qiskit Terra version**: 0.17.1
- **Python version**: 3.8.3
- **Operating system**: macOS 11.2.3

### What is the current behavior?
The confidence_interval of the Max Likelihood Amplitude Estimator is already rescaled. The confidence_interval_processed is rescaled twice. This does not happen for example with the Iterative Amplitude Estimator

### Steps to reproduce the problem
Run a Max Likelihood Amplitude Estimator with a post processing function

### What is the expected behavior?
Have the confidence_interval not rescaled, and the confidence_interval_processed only rescaled once

### Suggested solutions
I haven't seen where the bug is

**Comment by Francesco-Benfenati** [comment]
The same problem happens with AmplitudeEstimation too

**Comment by ElePT** [comment]
Transferred to new repo: https://github.com/qiskit-community/qiskit-algorithms/issues/49
