### ISSUE TITLE
why is qiskit_backend_overview a magic instead of a function/method?

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#6378]
Having `qiskit_backend_overview` as a `qiskit.tools.jupyter` magic is not ideal. It creates unintuitive situations. For example, `from qiskit.tools.jupyter import qiskit_backend_overview` does not work. And `%qiskit_backend_overview` fails if no `load_account()` was not executed yet.

I suggest to make `qiskit_backend_overview` a method in the provider or just a standalone function.

Or is there any key advantage in having it as a magic?

**Comment by nonhermitian** [comment]
I would just deprecate it and remove. It is legacy code that has been replaced by other tools in the IBM Cloud.

**Comment by jakelishman** [comment]
This was removed in #11513.
