### ISSUE TITLE
Wrong ordering convention in opflow tensor docs?

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit#6398]
### Information

- **Qiskit Terra version**:  0.17.2
- **Python version**: 3.9
- **Operating system**: Mac

### What is the current behavior?

The [docstring for OperatorBase.tensor](https://qiskit.org/documentation/_modules/qiskit/opflow/operator_base.html#OperatorBase.tensor), which is repeated for e.g. PauliOp.tensor, has this explanation of ordering:

>         Return tensor product between self and other, overloaded by ``^``.
>         Note: You must be conscious of Qiskit's big-endian bit printing convention.
>         Meaning, X.tensor(Y) produces an X on qubit 0 and an Y on qubit 1, or X⨂Y,
>         but would produce a QuantumCircuit which looks like
> 
>             -[Y]-
>             -[X]-
> 
>         Because Terra prints circuits and results with qubit 0 at the end of the string
>         or circuit.

But when I try to verify this behavior, the printed circuit is labeled with q_0 at the top, which seems to indicate that actually a Y has been applied to qubit 0, and an X to qubit 1, contradicting the docstring:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/60495383/117877178-13442a80-b259-11eb-9e11-cf62bc928eda.png">

### What is the expected behavior?

I expect the docstring should be changed or clarified to match the actual behavior. It's critical that the ordering convention is clear and consistent for users to be able to use opflow, since the wrong convention can lead to severe but hard-to-find bugs.

**Comment by Cryoris** [comment]
I think for the docstring "qubit 0" means the first qubit in the tensor product. But that's not `q_0`, which is what the docstring is trying to clarify. Probably it would be better to just remove explicit numbers from the phrase, like 
```
    Note: You must be conscious of Qiskit's big-endian bit printing convention.
    Meaning, X.tensor(Y), or X⨂Y, produces a circuit looking like
```

**Comment by jlapeyre** [comment]
I don't think it's worth updating the docs, since this code is obsolete.
