### ISSUE TITLE
CircuitStateFn in opflow could be extended to support quantum circuits with classical registers

### ISSUE THREAD

**Issue by riddhisw** [Qiskit/qiskit#6400]
### What is the expected enhancement?
We wish to be able to use `qiskit.algorithms`  (specifically, `VQE`) on quantum circuits  associated with classical registers. Currently, `qiskit.opflow.state_fns.circuit_state_fn`   raises a TypeError rejecting any  circuit with classical bits:
```
if len(primitive.clbits) != 0:
            raise TypeError('CircuitOp does not support QuantumCircuits with ClassicalRegisters.')
```
For instance, this TypeError is raised when `vqe.construct_expectation() ` method wants  to run the line `ansatz_circuit_op = CircuitStateFn(wave_function) ` but in general, I think the use of `CircuitStateFn` could affect other classes beyond `VQE` (e.g. qiskit gradient framework).  

In particular for the `VQE` class,  from my understanding, it is not possible to avoid calling `CircuitStateFn` using options for passing your own expectation value calculation.  Another suggestion is to locally comment out the code raising TypeError to see if the logic is supported but so far this approach stalls at other errors.

**Comment by ShellyGarion** [comment]
This bug does not apply to currently supported versions of Qiskit. Please submit a new issue if the bug still occurs in Qiskit 1.*.
See https://docs.quantum.ibm.com/migration-guides/qiskit-opflow-module
https://docs.quantum.ibm.com/migration-guides/qiskit-algorithms-module
