### ISSUE TITLE
Add Brazilian portuguese language

### ISSUE THREAD

**Issue by gilbion** [Qiskit/qiskit#651]
Hello,

I would like to have the Qiskit documentation translated from English to Brazilian Portuguese. 

I can participate in the translation project as either the Translation Leader or the Proofreader.

I also have a couple other people that would like to participate in the translation effort.

Thank you!

**Comment by SooluThomas** [comment]
Hi @gilbion, Thank you for your interest in contributing to Qiskit Localization. 

Please ask the other people who'd like to join as well to comment here in this issue and also [make a PR for adding your name to the LOCALIZATION_CONTRIBUTORS file](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation). Each contributor should add only their own name to the list.

**Comment by SooluThomas** [comment]
> Hi @SooluThomas, I am also interest in translating to Brazilian Portuguese and I am Brazilian native. Thanks

Thank you @imvieira for volunteering for localization. I see that you've already added your name to LOCALIZATION_CONTRIBUTORS list in PR - https://github.com/Qiskit/qiskit/pull/624. You need not make a PR again 😊

**Comment by diegodsd** [comment]
I have already started studying such and can contribute to translate it under portuguese language.

**Comment by SooluThomas** [comment]
Hi all! Please go ahead and make PRs as mentioned in [Step 2](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) of Contributing to Localization Docs.

**Comment by lzdanski** [comment]
Hi @diegodsd, @gilbion, @imvieira the Qiskit Translation project for Brazilian Portuguese is now open on Crowdin! 

To join the project, follow [steps 4 and 5](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) of the contributor guide. 

*Please be sure to include the [PR you made](https://github.com/Qiskit/qiskit/pulls) adding your name to the Localization Contributors file in the message body when you request to join*

**Comment by nonhermitian** [comment]
Can you please move this issue here: https://github.com/Qiskit/qiskit-translations if needed
