### ISSUE TITLE
Get gate from name.

### ISSUE THREAD

**Issue by idnm** [Qiskit/qiskit#6531]
### What is the expected behavior?

There are standard labels for gates like `cx`, `ry`, 'u3' etc. For example,  `qiskit.compiler.transpile` accepts a list of basis gates in this form. Currently the only way I know how to find out which label stays for which gate is to examine [circuit library](https://qiskit.org/documentation/apidoc/circuit_library.html) (and even there seems to be no clear mapping between labels and gates). It would be very convenient to be able to construct a gate from the corresponding label, such that for example `qiskit.circuit.Gate.from_label('h')` would give `qiskit.circuit.library.HGate`.

**Comment by singhmeet11** [comment]
Hi, this looks like an interesting idea but in issue #5098 they wanna remove the `label` parameter from all the gates, so then this modification will be rendered useless, I think.

**Comment by Cryoris** [comment]
In this PR we rather mean `name`, not `label`. The name of a gate is unique so you can construct it via name, however the label is essentially just for plotting. The label is being removed via #5098, but not the name. I'll rename this PR title to make this clearer.

**Comment by eptru** [comment]
seems like an interesting and useful feature! I am interested in this if no one else has started working on it.

**Comment by Cryoris** [comment]
Sure, go ahead @eptru!

**Comment by enavarro51** [comment]
Is this being worked on? If not, I can pick it up.

**Comment by eptru** [comment]
Yeah sorry it took a bit longer. I will try to comp it this week.
________________________________

**Comment by Quant02** [comment]
I'm new to contributing. @eptru are you still working on this? If not, I want to take it up.

**Comment by eptru** [comment]
Oops sorry I forget about this again.. I will try to get this done in the next two days.

**Comment by s1k0ra** [comment]
Is there solution yet ? @eptru

**Comment by jakelishman** [comment]
There is now a standard function `qiskit.circuit.library.standard_gates.get_standard_gate_name_mapping` that returns a `dict[str, Gate]`, so you can do:

```python
from qiskit.circuit.library.standard_gates import get_standard_gate_name_mapping

name_map = get_standard_gate_name_mapping()

hgate = name_map["h"]
```

I'll close this issue, but if there's more to discuss please feel free to reopen.

**Comment by s1k0ra** [comment]
No, sounds good. Thanks for the quick response 👍
