### ISSUE TITLE
Generalize `CXCancellation` optimization pass to generic gate-inverse pairs

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit#6576]
### What is the expected enhancement?

The `CXCancellation` pass currently only looks for adjacent CX-CX gates (on the same qubits) as opportunities for optimization, but it should support a broader set of both self-inverse gates and generic gate-inverse pairs.

One option (similar to what was done for `CXDirection` in #5609 ) would be to include in `CXCancellation` additional gate-inverse rules for which it can search the circuit to find applications.  It would be better though to add an optional attribute to `Instruction` instances to denote which `Instruction` (if any) is know ahead of time to be an instruction's inverse.

**Comment by lcapelluto** [comment]
This PR #6855 can be used to complete this feature request -- all that would be required would be to search for the correct inputs for the new pass prior to running. I unlinked the PR to leave this issue open after it's merged.
