### ISSUE TITLE
Add final layout from property set to output circuit metadata

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#6661]
### What is the expected enhancement?

Right now the routing passes all set the `final_layout` property in the property_set of the PassManager it's running in. This would be useful to expose to users that call `transpile()` so they know the layout the transpiler has set. We already preserve the circuit metadata for each transpiler pass explicitly for cases like this where we want to add attributes from the transpiler on the output circuit. We should start doing this for the `final_layout` property.

This might also be a good time to move the existing initial layout property we set as a private attribute on the output circuit to the circuit metadata as well.

**Comment by jakelishman** [comment]
This got done in #8802 and #8597.
