### ISSUE TITLE
Gate with parameterized gate *and* phase is bound incorrectly

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit#6674]
### Information

- **Qiskit Terra version**: main @ a2cc56f82ebbfd83fb9dc87e9f5dd59eacba9709
- **Python version**: 3.7.9
- **Operating system**: macOS

### What is the current behavior?

A circuit that contains a gate with the same parameter both in a gate and the global phase does bind the parameters, but it still shows up as free in the bound circuit.

### Steps to reproduce the problem

```python
from qiskit.circuit import *

x = Parameter('x')
inner = QuantumCircuit(1)
inner.global_phase = x
inner.rx(x, 0)

bound = inner.assign_parameters([0])
print("Inner", bound.parameters, "and decomposed", bound.decompose().parameters)

outer = QuantumCircuit(inner.num_qubits)
outer.append(inner.to_gate(), outer.qubits)

bound = outer.assign_parameters([0])
print("Outer", bound.parameters, "and decomposed", bound.decompose().parameters)
```
Results in
```
Inner ParameterView([]) and decomposed ParameterView([])
Outer ParameterView([]) and decomposed ParameterView([Parameter(x)])
```

### What is the expected behavior?

The decomposed `outer` circuit should not have free parameters.

**Comment by jakelishman** [comment]
This is no longer reproducible as of Qiskit 1.0.1 and appears to do the right thing now, so I'll close this issue as complete.
