### ISSUE TITLE
Add back held release notes from 0.18.0

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#6715]
### What is the expected enhancement?

As part of the 0.18.0 release prep in #6652 a couple release notes were held back (and removed from the repo to avoid reno thinking they should be applied to the 0.18.0 release) as they weren't fully implemented yet. The 2 release notes in question are

- `lo-freqs-circuit-c2ec161873eb4a68.yaml` which was added in #6167 and removed in https://github.com/Qiskit/qiskit-terra/pull/6652/commits/3b4600a8a1f0e9d86afa8c9cd40a287fe6c91566 (after being rewritten)
- Single bit classical conditions which was added in #6018

This issue is just for tracking to make sure we add the appropriate release notes back when we're ready to advertise the new functionality

**Comment by Eric-Arellano** [comment]
This seems irrelevant now. Feel free to reopen if you disagree.
