### ISSUE TITLE
PauliTrotterEvolution does not recognize SummedOp of PauliSumOp as Paulis

### ISSUE THREAD

**Issue by nbronn** [Qiskit/qiskit#6721]
### Information

- **Qiskit Terra version**: 0.18.0.dev0+732e887
- **Python version**: 3.9.4 
- **Operating system**: Darwin

### What is the current behavior?

When converting an `EvolvedOp` operator from a Pauli Hamiltonian via `PauliTrotterEvolution`, the evolved Hamiltonian is not recognized as consisting only of Paulis in certain cases.

### Steps to reproduce the problem

```
from qiskit.circuit import Parameter
from qiskit.opflow import I, X, Y, Z, PauliTrotterEvolution, Suzuki

mu = Parameter('$\\mu$')
nu = Parameter('$\\nu$')

my_ham1 = mu*((I^I) - (Z^I)) + nu*((I^I) - (I^Z))

tt = Parameter('$t$')
U_ham1 = (tt*my_ham1).exp_i()
```

```
U_ham1
```
prints

```
EvolvedOp(SummedOp([PauliSumOp(SparsePauliOp([[False, False, False, False],
               [False, False, False,  True]],
              coeffs=[ 1.+0.j, -1.+0.j]), coeff=1.0*$\mu$), PauliSumOp(SparsePauliOp([[False, False, False, False],
               [False, False,  True, False]],
              coeffs=[ 1.+0.j, -1.+0.j]), coeff=1.0*$\nu$)], coeff=1.0*$t$, abelian=False), coeff=1.0)
```

```
trot_op1 = PauliTrotterEvolution(trotter_mode=Suzuki(order=2, reps=1)).convert(U_ham1)
```
prints
```
Evolved Hamiltonian is not composed of only Paulis, converting to Pauli representation, which can be expensive.
```

### What is the expected behavior?

`PauliTrotterEvolution` should simplify the expression as in the following equivalent operator:

```
my_ham2 = (mu+nu)*(I^I) - mu*(Z^I) - nu*(I^Z)
U_ham2 = (tt*my_ham2).exp_i()
trot_op2 = PauliTrotterEvolution(trotter_mode=Suzuki(order=2, reps=1)).convert(U_ham2)
```
does not print a warning message.

```
U_ham2
```
prints
```
EvolvedOp(SummedOp([PauliOp(Pauli('II'), coeff=1.0*$\mu$ + 1.0*$\nu$), PauliOp(Pauli('ZI'), coeff=-1.0*$\mu$), PauliOp(Pauli('IZ'), coeff=-1.0*$\nu$)], coeff=1.0*$t$, abelian=False), coeff=1.0)
```

### Suggested solutions

Perhaps parsing the summed operators to ensure Paulis are recognized so that more efficient `opflow` methods can be used.

**Comment by ShellyGarion** [comment]
This bug does not apply to currently supported versions of Qiskit. Please submit a new issue if the bug still occurs in Qiskit 1.*.
See https://docs.quantum.ibm.com/migration-guides/qiskit-opflow-module.
