### ISSUE TITLE
Use Isometry to implement Initialize instruction

### ISSUE THREAD

**Issue by EgrettaThula** [Qiskit/qiskit#6760]
### What is the expected enhancement?
As per documentation, `Isometry` instruction can be used for **state preparation**.
On the other hand, `Initialize` instruction does its work by first resetting the qubits to `|0⟩` followed by an **state preparing** unitary.
That means `circ.initialize` is equivalent to `circ.reset` + `circ.iso`.

However, I noticed that using `Isometry` almost always results in a circuit with much less number of CNOTs.
```python
n = 4
psi = random_statevector(2 ** n)

# Using initialize
qr1 = QuantumRegister(n)
qc1 = QuantumCircuit(qr1)
qc1.initialize(psi, qr1)
tr_qc1 = transpile(qc1, basis_gates = ['u', 'cx'], optimization_level = 3)
print('Initialize:', tr_qc1.count_ops())

# Using reset + iso
qr2 = QuantumRegister(n)
qc2 = QuantumCircuit(qr2)
qc2.reset(qr2)
qc2.iso(psi, qr2, [])
tr_qc2 = transpile(qc2, basis_gates = ['u', 'cx'], optimization_level = 3)
print('Isometry:', tr_qc2.count_ops())
```

The result is something like that:
```
Initialize: OrderedDict([('u', 26), ('cx', 22)])
Isometry: OrderedDict([('u', 15), ('cx', 11)])
```

So, I suggest to use `Isometry` to implement `Initialize` instruction. This should lead to a better end result with less code to maintain.

**Comment by Cryoris** [comment]
`Isometry` and `Initialize` use two different algorithms to construct the circuits. Rather than replace one with the other I think it would be better to keep synthesis part of `Initialize` (i.e. without the initial resets) in some class in Qiskit but have ``QuantumCircuit.initialize`` use the more efficient isometry instead.

**Comment by ShellyGarion** [comment]
close in favor of #12081.
the separation of initialize to reset + state preparation was done in #7666
