### ISSUE TITLE
Deprecate qiskit.extensions

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit#6861]
### What is the expected enhancement?

Following #4699 and #4311 and others, the `qiskit.extensions` folder should be empty and can be deprecated and removed.

**Comment by mtreinish** [comment]
I opened up #10646 just now and missed that this already existed. I had these details in there about how we can go about making this change:

The `qiskit.extensions` module is a historical artifact that predates the existence of the circuit library. As we're stabilizing and unifying interface we should remove this standalone module and migrate or remove the classes defined in it. Right now there are the following things in the module:

* `UnitaryGate`
* `Initialize`
* `Snapshot`
* `HamiltonianGate`
* `SingleQubitUnitary`
* `UCPauliRotGate`
* `UCRXGate`
* `UCRYGate`
* `UCRYGate`
* `Isometry`
* `DiagonalGate`
* `MCGupDiag`
* `UCGate`

As a first step we should migrate these class definitions to live in the circuit library and add a redirect shim that will emit a deprecation warning for anything using `qiskit.extensions`. In parallel we should take inventory of these classes and individually deprecate any class which doesn't provide value anymore and stage those for removal.

**Comment by ewinston** [comment]
What are the thoughts about which of these should be deprecated?

**Comment by Cryoris** [comment]
@ewinston Only `Snapshot` and `SingleQubitUnitary` for now, I added some explanations in #10725.
