### ISSUE TITLE
double swap is not being optimized out when followed by a gate

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#7296]
### What is the expected enhancement?

Consider the following situation:
```python
from qiskit import QuantumCircuit
circuit = QuantumCircuit(2)
circuit.swap(0,1)
circuit.swap(0,1)
circuit.draw('mpl')
```
![image](https://user-images.githubusercontent.com/766693/142732387-d67e4793-1ecb-4d9e-8fad-4a1e333b010b.png)

When transpiled at level 3, the swap gates are optimized out
```python
transpile(circuit, optimization_level=3).draw('mpl')
```

![image](https://user-images.githubusercontent.com/766693/142732379-d41e15b7-cec7-486b-8d4a-0c23ddc140b8.png)

Let's add a gate at the end:
```python
circuit.h(0)
circuit.draw('mpl')
```
![image](https://user-images.githubusercontent.com/766693/142732347-f75962e7-6bd3-4c61-8f59-b8dc5d1d0bc9.png)

When transpiled at level 3, the swap gates are not being optimized out:
```python
transpile(circuit, optimization_level=3).draw('mpl')
```
![image](https://user-images.githubusercontent.com/766693/142732347-f75962e7-6bd3-4c61-8f59-b8dc5d1d0bc9.png)

**Comment by georgios-ts** [comment]
In the first example, the swap gates are actually optimized by [`OptimizeSwapBeforeMeasure`](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/transpiler/passes/optimization/optimize_swap_before_measure.py) (hint: try with just one swap, it'll still be removed) while in the second example, placing an `HGate` at the end, prevents the transpiler from applying this optimization.

Notice though that if you specify a basis gate set, the transpiler will collect and resynthesize the swap gates + hadamard and the output circuit will not have any 2q gate.  Nevertheless, it might be beneficial to add [`InverseCancellation`](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/transpiler/passes/optimization/inverse_cancellation.py) pass in the preset passmanagers.

**Comment by 1ucian0** [comment]
I think swap should be like cnot and h.

**Comment by 1ucian0** [comment]
I agree that this issue might get fixed if `InverseCancellation` gets into the preset passmanagers (did not test it tho).

**Comment by ajavadia** [comment]
if you do `transpile(circuit, basis_gates=['h', 'cx'])` then the circuit gets simplified. 

most of the passes are based on synthesis and synthesis over swap is not supported (since it's not entangling). But if you give any other basis it will work. (cx or cz or whatever)

**Comment by jakelishman** [comment]
We've updated the default pipelines since this issue was opened, and the double swap gets optimised out at all non-zero optimisation levels.
