### ISSUE TITLE
Add Spanish, Spain Language

### ISSUE THREAD

**Issue by Arturacu** [Qiskit/qiskit#738]
This week I joined the translation group of the Spanish Mexico language. I found out that though both Spaniards and Mexicans speak Spanish, we speak it differently. To get a more precise documentation I want to create a new group for the Spanish, Spain language.

I have talked with some other people. They are willing to join me to create a new translation group.

I could be the Translation Lead of the Spanish, Spain group. Some translators and proofreaders will be: @fcnatra, @gabrielgt, @ibonreinoso and @aitmoreno

Also, help from any other people willing to join us will be welcomed.

**Comment by VicPinaCanelles** [comment]
Hi! I’ve been translating some easier parts into Spanish, Mexico but I can join for the Spanish, Spain translation too.

**Comment by MIBbrandon** [comment]
Hello there! I'd love to join the Spanish, Spain translation team too

**Comment by iyanmv** [comment]
I could also help with that!

**Comment by iyanmv** [comment]
I will wait till Spanish (ES-es) group is added to `docs/LOCALIZATION_CONTRIBUTORS` and a new group is created in Crowdin to add my PR.

**Comment by lzdanski** [comment]
@Arturacu I sent you a message on Crowdin about Translation Lead questions! Please be sure to check your messages there.

**Comment by lzdanski** [comment]
Hi @iyanmv @MIBbrandon @VicPinaCanelles @fcnatra, @gabrielgt, @ibonreinoso and @aitmoreno the Qiskit Translation project for [Spanish](https://crowdin.com/project/qiskit-docs/es-ES#) is now open on Crowdin! 

*Please be sure to include the [PR you made](https://github.com/Qiskit/qiskit/pulls) adding your name to the Localization Contributors file in the message body when you request to join*

To join the project, follow [steps 4 and 5](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) of the contributor guide. 

Let me know if you have any questions!

**Comment by iyanmv** [comment]
There are many open PR. I will wait at least till https://github.com/Qiskit/qiskit/pull/752 is merged to add my name.

**Comment by iyanmv** [comment]
PR made: https://github.com/Qiskit/qiskit/pull/770

**Comment by fcnatra** [comment]
...waiting for approval on Crowdin (fcnatra) - Translating Qiskit-Docs to Spanish language

| 
| 
|  | 
Translating Qiskit-Docs to Spanish language

Qiskit-Docs Spanish translation
 |

 |

 |






[http://fcnatra.com] [twitter] [skype] [linkedin] 

    En miércoles, 8 de enero de 2020 19:20:18 CET, Laura Zdanski <notifications@github.com> escribió:  
 
 
Hi @iyanmv @MIBbrandon @VicPinaCanelles @fcnatra, @gabrielgt, @ibonreinoso and @aitmoreno the Qiskit Translation project for Spanish is now open on Crowdin!

Please be sure to include the PR you made adding your name to the Localization Contributors file in the message body when you request to join

To join the project, follow steps 4 and 5 of the contributor guide.

Let me know if you have any questions!

**Comment by nonhermitian** [comment]
Can you please move this issue here: https://github.com/Qiskit/qiskit-translations
