### ISSUE TITLE
Enable ignored test in test_fake_backends

### ISSUE THREAD

**Issue by iuliazidaru** [Qiskit/qiskit#7438]
### What is the expected enhancement?

While working on #3905 I saw a test which is skipped until https://github.com/Qiskit/qiskit-aer/issues/741 is fixed. Maybe is should be checked again.
https://github.com/Qiskit/qiskit-terra/blob/main/test/python/mock/test_fake_backends.py
```
    @unittest.skip("Skipped until qiskit-aer#741 is fixed and released")
    @unittest.skipUnless(HAS_AER, "qiskit-aer is required to run this test")
    def test_transpile_schedule_and_assemble(self):
        """Test transpile, schedule and assemble on generated backend."""
        qc = get_test_circuit()
```

**Comment by jakelishman** [comment]
Since `ConfigurableFakeBackend` was removed in #11568, I think this issue is obsolete now.  Please feel free to re-open if there's more to discuss.
