### ISSUE TITLE
Matplotlib plots of Grover broken locally and on IBM Q Experience

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/qiskit#7503]
### Environment

_On local machine__
- **Qiskit Terra version**:  {'qiskit-terra': '0.19.1', 'qiskit-aer': '0.9.1', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.18.2', 'qiskit-aqua': '0.9.5', 'qiskit': '0.33.1', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}
- **Python version**:  3.9.7 
- **Operating system**:  NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"

### What is happening?

Matplotlib drawing of Grover oracle in Qiskit example draws incorrectly.

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit
from qiskit.algorithms import AmplificationProblem

# the state we desire to find is '11'
good_state = ['11']

# specify the oracle that marks the state '11' as a good solution
oracle = QuantumCircuit(2)
oracle.cz(0, 1)

# define Grover's algorithm
problem = AmplificationProblem(oracle, is_good_state=good_state)

# now we can have a look at the Grover operator that is used in running the algorithm
problem.grover_operator.draw(output='mpl')
```

### What should happen?

Drawing of entire oracle circuit.
What you get instead is just a drawing of the first two qubit states

### Any suggestions?

Reported on Qiskit Slack https://qiskit.slack.com/archives/C88B13092/p1641501466002000

**Comment by enavarro51** [comment]
I believe this is the result of #6634. You can get the detail back by doing
```
problem.grover_operator.decompose().draw(output='mpl')
```

**Comment by jwoehr** [comment]
Thanks @enavarro51 ... I think IBM Q Experience does not have a public repo? So I wonder how to file an issue or PR to fix the slightly misleading tutorial.

**Comment by jwoehr** [comment]
@enavarro51 found the tutorials.
Sumbitted [this PR](https://github.com/Qiskit/qiskit-tutorials/pull/1259), thanks for your help.

**Comment by hu-milize** [comment]
thank you both very much!

**Comment by ShellyGarion** [comment]
This bug does not apply to currently supported versions of Qiskit. Please submit a new issue if the bug still occurs in Qiskit 1.*.
https://docs.quantum.ibm.com/migration-guides/qiskit-algorithms-module
