### ISSUE TITLE
CircuitSampler works incorrectly in batched mode

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit#7608]
### Environment

- **Qiskit Terra version**: Latest sources
- **Python version**: 3.7, but it does not depend on the python version
- **Operating system**: All

### What is happening?

When `CircuitSampler` is used sample circuits (gradient circuits in my case) and circuit parameters are lists, e.g. a single parameter has a list of values the output has unexpected shape. This problem initially arose in machine learning where batch gradient computations are required.

@Cryoris This is for your attention, please :)

### How can we reproduce the issue?

I have a simple circuit with two parameters `p` and `w` as a toy example. Just to be in the context of the problem, in my case `p` is a feature and `w` is a weight in QNNs. In real life these are vectors, but here scalar parameters are good enough.
Then, I have a list of values for `p` and I want to compute gradient wrt to `p` for all values of `p`. This list is a list of samples in a dataset. In real setup, for each value of `p` I have the same value for `w`, but in the example I have different values for `w`, just to have different outputs.

Here is a setup:
```python
from qiskit import QuantumCircuit, Aer
from qiskit.circuit import Parameter
from qiskit.opflow import Gradient, StateFn, CircuitSampler
from qiskit.utils import QuantumInstance, algorithm_globals

​
def row_gradients(qc, grad_param, param_values: dict, quantum_instance) -> None:
    gradient = Gradient()
    gradient_circuit = gradient.convert(StateFn(qc), [grad_param])
​
    sampler = CircuitSampler(quantum_instance)
​
    num_samples = len(next(iter(param_values.values())))
    # iterate over all parameters, create a parameter object with a single set of parameters
    # and compute gradients per row
    for i in range(num_samples):
        sample_params = {key: param_values[key][i] for key in param_values.keys()}
        g = sampler.convert(gradient_circuit, sample_params).assign_parameters(sample_params).eval()
        print(g)
​
​
def batch_gradients(qc, grad_param, grad_param_values, other_values, quantum_instance):
    gradient = Gradient()
    # gradient wrt grad_param
    gradient_circuit = gradient.convert(StateFn(qc), [grad_param])
​
    sampler = CircuitSampler(quantum_instance)
​
    # combine all parameters, I guess, here is a problem
    all_params = {}
    all_params.update(grad_param_values)
    all_params.update(other_values)
​
    g1 = sampler.convert(gradient_circuit, all_params)
​
    # in g1 we still have other parameters! is it a bug or a feature?
    # we have to assign other parameters again
    g = g1.assign_parameters(other_values).eval()
    print(g)


if __name__ == '__main__':
    qi = QuantumInstance(
        Aer.get_backend("aer_simulator_statevector"),
        seed_simulator=algorithm_globals.random_seed,
        seed_transpiler=algorithm_globals.random_seed,
    )
​
    num_qubits = 1
​
    qc = QuantumCircuit(num_qubits)
    # this is our feature
    p = Parameter("p")
    # weights
    w = Parameter("w")
    qc.rx((3 - p) * (3 - w), 0)
​
    p_values = {p: [1, 1.23]}
    w_values = {w: [4, 4.56]}
​
    all_values = dict(p_values)
    all_values.update(w_values)
​
    batch_gradients(qc, grad_param=p, grad_param_values=p_values, other_values=w_values, quantum_instance=qi)
​
    row_gradients(qc, grad_param=p, param_values=all_values, quantum_instance=qi)
```

I have two versions: a batched version and a row by row one. 

In the batched version  `grad_param` is a circuit parameter to compute gradient wrt. `grad_param_values` is a dict of values for `grad_param`. `other_values` contains values for other parameters in the circuit. For the example above I want a gradient wrt `p` for a pair of values of `{p: 1, w: 4}` and `{p: 4, w: 4.56}` only as I have only 2 samples in my toy dataset.

In the row by row version I compute gradient for one set of parameters in one go. This leads to a large number of jobs, that's why this is inefficient. `grad_param` is the same, a circuit parameter to compute gradient wrt. `param_values` contains `p + w` parameter values as a dict.

The output of the batched version:
```
[[[[(0.45464871341284085+0j), (-0.45464871341284085+0j)], [(0.7092519929240315+0j), (-0.7092519929240315+0j)]]], [[[(0.18564254215640696+0j), (-0.18564254215640696+0j)], [(0.2896023657639948+0j), (-0.2896023657639948+0j)]]]]
```
There are more number than I expect to see. Looks like `CircuitSampler` samples circuits for a cross product of the parameters and this is unexpected. I suspect it is a bug.

The output of the row by row version:
```
[[(0.45464871341284085+0j), (-0.45464871341284085+0j)]]
[[(0.2896023657639948+0j), (-0.2896023657639948+0j)]]
```
This is correct.

### What should happen?

The batched version as outlined above should produce the same results as the row by row version.

**Comment by ShellyGarion** [comment]
This bug does not apply to currently supported versions of Qiskit. Please submit a new issue if the bug still occurs in Qiskit 1.*.
See https://docs.quantum.ibm.com/migration-guides/qiskit-opflow-module.
