### ISSUE TITLE
Provide equivalence checkers

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit#761]
According to @liupibm:

### The goal of the quivalence checker
Given two circuits, check whether their final amplitude vectors V1 and V2 are equivalent: they differ only in the global phase, i.e., the equation V1*E^(I*x)=V2 has a solution.

This is useful for debugging transpiler passes also.

**Comment by jaygambetta** [comment]
As in the last one this goes on hold until we are ready to scientifically discuss this. Can you put this back on hold or make it in a roadmap for qiskit 0.8. We will have an equivalence checker but after the transpiler is complete.

**Comment by ajavadia** [comment]
This is being done in Aer now.

**Comment by ajavadia** [comment]
reopening as the API to interact with the equivalence checker may end up in Terra

**Comment by kevinsung** [comment]
We have
```python
Operator(circuit).equiv(Operator(other_circuit))
```
and
```python
Statevector(circuit).equiv(Statevector(other_circuit))
```
Am I misunderstanding, or is this issue asking for something else?

**Comment by burgholzer** [comment]
> We have
> 
> ```python
> 
> Operator(circuit).equiv(Operator(other_circuit))
> 
> ```
> 
> and
> 
> ```python
> 
> Statevector(circuit).equiv(Statevector(other_circuit))
> 
> ```
> 
> Am I misunderstanding, or is this issue asking for something else?

Both of these scale exponentially with the number of qubits in the system.
If someone is interested in a more scalable equivalence checker that works out of the box with Qiskit, have a look at MQT QCEC (https://github.com/cda-tum/mqt-qcec, `pip install mqt.qcec`).

Verifying the equivalence of two Qiskit circuits is as easy as
```python
from mqt.qcec import verify 

res = verify(qc1, qc2)
```

Note that the tool uses dedicated data structures (decision diagrams and ZX calculus) plus dedicated verification schemes to make the verification way more scalable than the simple construction and comparison of the circuits' unitaries. More information can be found in the documentation at https://mqt.rtfd.io/projects/qcec

**Comment by eliarbel** [comment]
Thanks @burgholzer for sharing! 

@1ucian0, @ajavadia  this is quite an old issue. Apparently, there are both built-in as well as 3rd party solutions. So, do we still want to keep this open?

**Comment by 1ucian0** [comment]
great work @burgholzer and team! Consider [submitting the project to the Qiskit Ecosystem](https://github.com/Qiskit/ecosystem/issues/new?assignees=octocat&labels=submission&projects=&template=submission.yml&title=%5BSubmission%5D%3A+) :)

Indeed, probably this issue can be closed.
