### ISSUE TITLE
Cannot get expectation value of list ops or composed ops

### ISSUE THREAD

**Issue by mikevitz** [Qiskit/qiskit#7743]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

'qiskit-terra': '0.19.1', 
'qiskit-aer': '0.10.2', 
'qiskit': '0.34.1', 
Python 3.8.12

OS=Amazon Linux, version 2
ID_LIKE="centos rhel fedora"

### What is happening?

I am having trouble evaluating operators built from composed ops and list ops.  I keep getting the error:
`ValueError: Cannot compute overlap with StateFn or Operator if not Measurement. Try taking sf.adjoint() first to convert to measurement.`

### How can we reproduce the issue?
Copy/paste and run the code block below:
```
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from qiskit import Aer, QuantumCircuit
from qiskit.circuit import Parameter
from qiskit.opflow import StateFn, PauliSumOp, AerPauliExpectation, ListOp, Gradient
from qiskit.utils import QuantumInstance, algorithm_globals
from qiskit.opflow import (StateFn, Zero, One, Plus, Minus, H,
                           DictStateFn, VectorStateFn, CircuitStateFn, OperatorStateFn)

######### construct the parametrized circuit
qc = QuantumCircuit(2)

qc.h(0)
qc.h(1)
qc.cx(0,1)

param1 = Parameter('θ1')
param2 = Parameter('θ2')
qc.rx(param1, 0)
qc.rx(param2, 1)

qc_sfn = StateFn(qc)

######### construct hamiltonians
H_11 = StateFn(PauliSumOp.from_list([("ZI", 1.0)]))
H_12 = StateFn(PauliSumOp.from_list([("IZ", 1.0)]))

######### combine hamiltonian and circuit 
op_11 = ~H_11 @ qc_sfn
op_12 = ~H_12 @ qc_sfn
ops1 = ListOp([op_11, op_12])

print(op_11.to_circuit_op())
print(ops1.to_circuit_op())

op_11.bind_parameters({param1: 0.832619845547938,
                       param2: 0.07103605819788694})

ops1.bind_parameters({param1: 0.832619845547938,
                    param2: 0.07103605819788694})

######## DOESN'T WORK
op_11.eval(One^2)

######## ALSO DOESN'T WORK
ops1.eval(One^2)
```

### What should happen?

Should be able to get the expectation value of the operator.

**Comment by Cryoris** [comment]
I think you're not using the opflow instructions correctly here:
* `bind_parameters` is not an in-place operations, but returns the bounds object
* your `op_11` and `ops1` objects are already fully contracted, you can just call `eval()` on them without any argument

If you change the code as follows it seems to work:
```python
# ... as you had it
bound_11 = op_11.bind_parameters({param1: 0.832619845547938,
                                  param2: 0.07103605819788694})

bounds1 = ops1.bind_parameters({param1: 0.832619845547938,
                               param2: 0.07103605819788694})

print(bound_11.eval())
print(bound1.eval())

**Comment by mikevitz** [comment]
Thank you for the observation!  I see now how to do this. 

But I keep getting unexpected results!  For example
`bound = ops1.bind_parameters({param1: 10.832619845547938,
                    param2: 1.07103605819788694})

print(bound.eval())`

No matter what parameters I use, it always gives results:
`[0j, 0j]`

My understanding is that the code creates a circuit, puts the qubits in superposition via Hadamard, entangles them via CNOT and rotates around x axis in Bloch sphere.

Shouldn't I get non-zero results here?

Thanks again!

**Comment by jakelishman** [comment]
Since `opflow` was removed in #11111 and no longer supported, I think this issue is now obsolete.  Thanks for the discussion, and feel free to re-open if I've missed anything.
