### ISSUE TITLE
Quantum geometric tensor features

### ISSUE THREAD

**Issue by Zoufalc** [Qiskit/qiskit#7817]
### What is the expected enhancement?

The quantum geometric tensor reads `〈∂kψ|∂lψ〉−〈∂kψ|ψ〉〈ψ|∂lψ〉` and the quantum Fisher information reads `4 * Re[〈∂kψ|∂lψ〉−〈∂kψ|ψ〉〈ψ|∂lψ〉]`. 
Using the features implemented for the `LinCombFull` Circuit QFI methods implemented by [PR 7632](https://github.com/Qiskit/qiskit-terra/pull/7632), we can easily compute the quantum geometric tensor using linear combination of unitaries methods.

To streamline the possibilities and clarify the methods for the user, we suggest adding a class of quantum geometric tensor methods to the gradient framework such that several QFI methods may be derived from them.  

@Cryoris

**Comment by woodsp-ibm** [comment]
Opflow is now deprecated soon to be removed. New features/enhancements are no longer a consideration.
