### ISSUE TITLE
Rename old fake BackendV2 classes

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit#7838]
### What is the expected enhancement?

https://github.com/Qiskit/qiskit-terra/pull/7643 implemented mocked IBM Quantum Systems backends using the new BackendV2 interface. 

There were older fake BackendV2 classes that were created before for testing. We need to rename, reorganize or remove those classes

https://github.com/Qiskit/qiskit-terra/blob/8105a80c84ce2447a1e224b85f4f56e98f074763/qiskit/test/mock/fake_mumbai_v2.py
- [x] FakeMumbaiV2. Fixed by https://github.com/Qiskit/qiskit-terra/pull/7839

https://github.com/Qiskit/qiskit-terra/blob/8105a80c84ce2447a1e224b85f4f56e98f074763/qiskit/test/mock/fake_backend_v2.py
- [ ] FakeBackendV2
- [ ] FakeBackend5QV2
- [ ] FakeBackendSimple

**Comment by HuangJunye** [comment]
Reopening as #7839 only partially fixed this issue.

**Comment by HuangJunye** [comment]
@mtreinish What would you suggest to replace the old `FakeBackendV2` class? Should I choose one of the fake IBM Quantum systems to replace it, e.g. `FakeMumbaiV2`? And use a `FakeBelemV2` to replace the usage of `FakeBackend5QV2`?

**Comment by HuangJunye** [comment]
I decided to use `FakeManilaV2` which has 5Q qubits to replace `FakeBackendV2`, `FakeBackend5QV2` and `FakeBackendSimple`. One thing I am not sure is how to deal with `FakeBackendV2LegacyQubitProps`.

https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/test/mock/fake_backend_v2.py#L103-L109

**Comment by HuangJunye** [comment]
@mtreinish Having a deeper look at the different classes of these fake backends.

`FakeBackendSimple` is only used in https://github.com/Qiskit/qiskit-terra/blob/main/test/python/algorithms/test_backendv2.py and https://github.com/Qiskit/qiskit-terra/blob/6aacabd99122be2c2d59ef29655217db6ab33f0f/test/python/providers/test_backend_v2.py#L68-L71 so I can probably replace it with a fake V2 IBM Quantum backend with more than 18 qubits (required for the shor factoring test) or (probably better approach) a fake V2 QasmSimulator.

The rest of them are written in a very specific way and the tests specifically test the details of these backends. I am not sure how to generalize them to base on the new `FakeBackendV2` or a specific instance of a fake V2 IBM Quantum backend.

Or maybe I should just rename them and improve docstrings to describe what they are used for?

**Comment by 1ucian0** [comment]
I think this is can be closed, via #10918
