### ISSUE TITLE
job_monitor fails for qiskit runtime jobs

### ISSUE THREAD

**Issue by mbhealy** [Qiskit/qiskit#7865]
### Informations

- **Qiskit version**: 0.35.0
- **Python version**: 3.8
- **Operating system**: Ubuntu

### What is the current behavior?
When attempting to monitor jobs that use the qiskit runtime the following error occurrs:
```
Job Status: job is queued
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_9699/736061496.py in <module>
     19 )
     20 
---> 21 job_monitor(reset_job)

~/.local/lib/python3.8/site-packages/qiskit/tools/monitor/job_monitor.py in job_monitor(job, interval, quiet, output, line_discipline)
     87         _interval_set = True
     88 
---> 89     _text_checker(
     90         job, interval, _interval_set, quiet=quiet, output=output, line_discipline=line_discipline
     91     )

~/.local/lib/python3.8/site-packages/qiskit/tools/monitor/job_monitor.py in _text_checker(job, interval, _interval_set, quiet, output, line_discipline)
     47 
     48         if status.name == "QUEUED":
---> 49             msg += " (%s)" % job.queue_position()
     50             if job.queue_position() is None:
     51                 interval = 2

AttributeError: 'RuntimeJob' object has no attribute 'queue_position'
```

### Steps to reproduce the problem
Submit a qiskit runtime job to a full queue, then monitor the job with `job_monitor(job)`

### What is the expected behavior?
The job_monitor should not exit with an exception

### Suggested solutions
Remove the assumption that the job object has a `queue_position` method, as that is not part of the base class.

**Comment by saktar-unr** [comment]
Hi, Can I work on this issue?

**Comment by jakelishman** [comment]
@saktar-unr: sure, if you'd like, I'll assign you.  The issue is that the `job` here could (in theory) be any `JobV1` object, and so we can only require methods from that class.  It looks like this function was written at a time when `qiskit-ibmq-provider` and `qiskit-terra` were tightly coupled, so it assumes a type of `Job` that is no longer a part of Terra, and it hasn't been touched much since.

We'll need to update the function so that it only uses functionality from Terra's `JobV1`.  I think we can safely remove all IBMQ-specific functionality from this, because `qiskit-ibmq-provider` provides a very similar function that handles their specific case (Michael: as a more complete solution, you may want to use `qiskit.providers.ibmq.job.job_monitor` instead, since that's got IBMQ-specific extensions like queue position.)

**Comment by saktar-unr** [comment]
@jakelishman, Thank you! I have a question on this. As JobV1 (https://qiskit.org/documentation/stubs/qiskit.providers.JobV1.html) does not have the queue_position method anymore. Can I just remove the part where it computed the job position in queue? I mean should I just show status.value for all JobStatus (https://qiskit.org/documentation/stubs/qiskit.providers.JobStatus.html). I pushed a commit with those updates. Please let me know if I need to do more changes.

**Comment by seenivasanh** [comment]
Hello @saktar-unr,

Thanks for your effort in looking into this. Do we have a solution? 
It is frustrating to see the total number of jobs in a given backend and not knowing the job position. 

Thanks in advance.
Seenivasan

**Comment by jakelishman** [comment]
In general, it is up to individual providers to supply Python-space methods to query properties of their queueing system, not core Qiskit.  As mentioned in an above comment, `qiskit-ibm-provider` supplies [its own method](https://docs.quantum.ibm.com/api/qiskit-ibm-provider/qiskit_ibm_provider.job.job_monitor), and if that's functionality that `qiskit-ibm-runtime` doesn't have, then that would be an issue to file [at their repository](https://github.com/Qiskit/qiskit-ibm-runtime).  That said, their PR Qiskit/qiskit-ibm-runtime#1210 appears to have just recently added similar functionality.

I suspect that `job_monitor` is likely to be removed from core Qiskit, and left entirely to providers - its existence in the core library is more of a historical artefact.

**Comment by seenivasanh** [comment]
Thanks @jakelishman for your explanation and the pointer to the runtime functionality. 
Will look into it.

**Comment by eliarbel** [comment]
@mbhealy although #11414 gracefully handles the missing `queue_position` attribute, this functionally in any case is tied to the already-deprecated `qiskit-ibm-provider` so nothing more we can do here.
