### ISSUE TITLE
Do not wait 5 seconds in QuantumInstance by default

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#7909]
### What is the expected enhancement?

VQE and the like are basically unusable with FakeBackends because the `QuantumInstance` is waiting 5 sec to get results.  It would be nice to have `wait=0` by default.

For example, a 2Q problem takes 21min by default, verse 39sec on the same machine using a custom SPSA solver following this tutorial: https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.html

**Comment by woodsp-ibm** [comment]
Opflow is now deprecated soon to be removed. New features/enhancements are no longer a consideration.
