### ISSUE TITLE
Wrong time value in Trotterized unitary

### ISSUE THREAD

**Issue by ajrazander** [Qiskit/qiskit#8126]
### Environment

- **Qiskit Terra version**: 0.36.0
- **Python version**: 3.8.8
- **Operating system**: Mac 11.6.5

### What is happening?

Computing a suzuki decomposition of a Hamiltonian for a given time t. If t is a float, everything works fine. If t is a Parameter object the value gets squared when it is bound.

### How can we reproduce the issue?

```
from qiskit.opflow import X, Z, Suzuki
from qiskit.circuit import Parameter

time = 11.0
H = (X^X^X) + (Z^Z^Z)
U1 = Suzuki(1, order=1).convert(time * H)
print(U1)

t = Parameter('t')
U2 = Suzuki(1, order=1).convert(t * H)
U2_t = U2.bind_parameters({t:time})
print(U2_t)
```

which outputs on my device
```
ComposedOp([
  e^(-i*11.0 * XXX),
  e^(-i*11.0 * ZZZ)
])
ComposedOp([
  e^(-i*121.0 * (
    1.0 * XXX
  )),
  e^(-i*121.0 * (
    1.0 * ZZZ
  ))
])
```

### What should happen?

What should happen is when the time value is bound to the Parameter object, it should show 11.0 inside the exponential, not 121.0.

**Comment by ikkoham** [comment]
I think we need to add 
```
operator.coeff = 1
```
after getting coeff.
https://github.com/Qiskit/qiskit-terra/blob/2eee56616d50a9e26756f855ef4aa0135920ad78/qiskit/opflow/evolutions/trotterizations/suzuki.py#L62

**Comment by Cryoris** [comment]
Thanks for reporting this @ajrazander! 

You can also use the `PauliEvolutionGate` instead, which we will shift to in the future 🙂 

```python
from qiskit.circuit import Parameter
from qiskit.circuit.library import PauliEvolutionGate
from qiskit.synthesis import SuzukiTrotter
from qiskit.opflow import X, Z

suzuki = SuzukiTrotter(order=2, reps=1)  # for order=1 you should use LieTrotter

time = 11.0
H = (X^X^X) + (Z^Z^Z)
U1 = PauliEvolutionGate(H, time=time, synthesis=suzuki).definition
print(U1)

t = Parameter('t')
U2 = PauliEvolutionGate(H, time=t, synthesis=suzuki).definition
U2_t = U2.bind_parameters({t:time})
print(U2_t)
```

**Comment by BramDo** [comment]
> I think we need to add
> 
> ```
> operator.coeff = 1
> ```
> 
> after getting coeff.
> 
> https://github.com/Qiskit/qiskit-terra/blob/2eee56616d50a9e26756f855ef4aa0135920ad78/qiskit/opflow/evolutions/trotterizations/suzuki.py#L62

I tried coeff = 1 instead of operator.coeff = 1. This solution works in my local qiskit terra. I will try to make with this solution my first attribution.

**Comment by ajrazander** [comment]
Excellent. Thank you everyone! Glad to see the fix as well as an example of what functions to use in the future :) I'll let someone else close the issue

**Comment by javabster** [comment]
@BramDo are you still working on this or can I unassign you and let someone else pick it up? 😄

**Comment by BramDo** [comment]
I was busy with other projects but now I have some more time and I could start working on this again. A far as I can remember the fix was already working, but there were some tests needed. So I can pick it up myself if that is OK. It could be that I have to merge latest files because the fix was already done many months ago. I will look into this and report the status.

**Comment by ShellyGarion** [comment]
This bug does not apply to currently supported versions of Qiskit. Please submit a new issue if the bug still occurs in Qiskit 1.*.
See https://docs.quantum.ibm.com/migration-guides/qiskit-opflow-module.
