### ISSUE TITLE
Add instructions for building documentation locally for documentation related contributions

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit#8274]
### What should we add?

I can't find instructions for building documentation locally for qiskit-terra in https://qiskit.org/documentation/contributing_to_qiskit.html#contributing-to-documentation nor https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md I think it would to add something similar to https://github.com/Qiskit/qiskit-machine-learning/issues/413 for qiskit-terra so that community contributors can follow to make documentation related contributions

**Comment by jakelishman** [comment]
It's here, right now: https://qiskit.org/documentation/contributing_to_qiskit.html#documenting-your-code.  It could be made more prominent, such as in Terra's `contributing.md`, though.

**Comment by prakharb10** [comment]
Adding to this, `tox` is used for running tests, building docs, etc. However, `tox` itself is not listed in `requirements-dev.txt`. I feel that after installing the packages listed in `requirements-dev.txt`, my environment should be ready to work on development.
Should we consider adding it to the list?

**Comment by mtreinish** [comment]
`tox` is independent of the `requirements-dev.txt` as it's a tool for manage your development virtual environments, package installation, and execution of test commands. Tox builds a virtualenv with a development install of the package and any additional testing tools. If you insist developers need to install requirements-dev first to install tox you end up duplicating the install of everything in the requirements list because first you install it in your working python env and then tox will install everything again in it's isolated testing venvs (you'd also needlessly install tox in the tox venv, but that's not as big a deal).

**Comment by prakharb10** [comment]
I think I understand your point, @mtreinish. However, this does make me wonder whether my current setup is "optimal". Should we use the venv that tox creates for development? (as the python interpreter for the project)

**Comment by HuangJunye** [comment]
The "Contributing to Documentation" section was removed in https://qiskit.org/documentation/contributing_to_qiskit.html#contributing-to-documentation I would like to suggest to add it back and improve it with clearer instructions on installing the dependencies.

**Comment by Pablohn26** [comment]
To create a local environment for the documentation of this repository, the instructions are the following:

```
apt update && apt install git make python3-sphinx python3-pip
git clone https://github.com/Qiskit/qiskit-terra.git
cd qiskit-terra/docs/
pip install -r ../requeriments-dev.txt
make html
```

I want to create the content of the broken link https://qiskit.org/documentation/contributing_to_qiskit.html#contributing-to-documentation , but I am hitting the following error ([like this one](https://github.com/xingyizhou/CenterTrack/issues/98)): 

```bash
root@b0e1fe2f62ee:/qiskit/docs# make html
Running Sphinx v4.5.0
loading translations [en]... done
making output directory... done

Extension error (versionutils):
Handler <function _extend_html_context at 0x7fe6482d4280> for event 'config-inited' threw an exception (exception: Command '['git', 'describe', '--abbrev=0']' returned non-zero exit status 128.)
```
@HuangJunye could you help me with this issue? I can generate locally documentation of qiskit-terra but not the [qiskit](https://github.com/Qiskit/qiskit) documentation.

**Comment by HuangJunye** [comment]
@Pablohn26 I am not sure about this error. 

Can you try this?

```
pip install -r requirements-dev.txt
pip install 'tox<4'
tox -e docs
```

**Comment by ayukumar11** [comment]
Hello, I would also love to contribute to this if it's still open.

**Comment by Raghav-Bell** [comment]
Hello!  i would like to contribute to this issue,

**Comment by AngeloDanducci** [comment]
@uchoi91 @ayukumar11 @Raghav-Bell You've all expressed interest previously but this issue fell through the cracks.  If any of you are still looking to contribute to this issue reply here and I'll assign to the first responder.

**Comment by uchoi91** [comment]
@AngeloDanducci I am looking and can contribute to this. 
when you assign me to it, I'll get rolling!

Thannks!

**Comment by AngeloDanducci** [comment]
@uchoi91 assigned, thanks!

**Comment by uchoi91** [comment]
hey all. 
I have created a section in contribution.md that discuss making documentation locally using tox, sphinx-build and make with recommending users to use tox cmd. 

Thanks!
