### ISSUE TITLE
Move the EvolvedOperatorAnsatz to N_local circuits directory

### ISSUE THREAD

**Issue by ShellyGarion** [Qiskit/qiskit#8326]
### Environment

- **Qiskit Terra version**: 0.21.0
- **Python version**: all
- **Operating system**: all

### What is happening?

This issue is regarding the organization of the circuit library, and in particular of the N-local circuits:
https://qiskit.org/documentation/apidoc/circuit_library.html#n-local-circuits

[EvolvedOperatorAnsatz](https://qiskit.org/documentation/stubs/qiskit.circuit.library.EvolvedOperatorAnsatz.html#qiskit.circuit.library.EvolvedOperatorAnsatz) gate is not under N-local circuits, although its basis is [NLocal](https://qiskit.org/documentation/stubs/qiskit.circuit.library.NLocal.html#qiskit.circuit.library.NLocal),
While [QAOAAnsatz](https://qiskit.org/documentation/stubs/qiskit.circuit.library.QAOAAnsatz.html#qiskit.circuit.library.QAOAAnsatz) gate whose basis is [EvolvedOperatorAnsatz](https://qiskit.org/documentation/stubs/qiskit.circuit.library.EvolvedOperatorAnsatz.html#qiskit.circuit.library.EvolvedOperatorAnsatz) is under N-local circuits.

### How can we reproduce the issue?

See the circuit library documentation: https://qiskit.org/documentation/apidoc/circuit_library.html

### What should happen?

[EvolvedOperatorAnsatz](https://qiskit.org/documentation/stubs/qiskit.circuit.library.EvolvedOperatorAnsatz.html#qiskit.circuit.library.EvolvedOperatorAnsatz) gate should be also in the N-local circuits directory https://qiskit.org/documentation/apidoc/circuit_library.html#n-local-circuits

### Any suggestions?

Move [EvolvedOperatorAnsatz](https://qiskit.org/documentation/stubs/qiskit.circuit.library.EvolvedOperatorAnsatz.html#qiskit.circuit.library.EvolvedOperatorAnsatz) gate to the N-local circuits directory https://qiskit.org/documentation/apidoc/circuit_library.html#n-local-circuits

**Comment by ShellyGarion** [comment]
Note that this should be handled in two steps.
First, one should add the gate in the correct place.
Then, in the following release, one can start the [deprecation process](https://qiskit.org/documentation/deprecation_policy.html).

**Comment by Ca1eb3** [comment]
I would like to do this.

**Comment by ShellyGarion** [comment]
thanks @Ca1eb3 - I assigned you to this issue!
