### ISSUE TITLE
Extend `qiskit.algorithms.eval_observables` to allow returning a callable

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit#8347]
### What should we add?

If we want to evaluate a set of expectation values for the same observables and circuits, but with different circuit parameters, we can cache the whole transpilation and basis transformation processes. Qiskit's opflow easily allows this and to leverage this it would be nice if we extended the `eval_observables` to allow returning a callable that takes as input circuit parameters and returns the (efficiently) evaluated expectation values.

Something like this is already used in #8304 and can be extracted and merged with the existing `eval_observables` in a follow-up.

**Comment by woodsp-ibm** [comment]
With the move to primitives, since estimators handle that aspect, can this be closed as no longer relevant. eval_observables will be removed when the now pending deprecated algorithms that use it are removed in the future.

**Comment by Cryoris** [comment]
This pretty much transfers to `estimate_observables` in the same way -- but if we decide to drop that and include dict support in the estimators we can close this issue here, yes 🙂

**Comment by ElePT** [comment]
Transferred to new repo: https://github.com/qiskit-community/qiskit-algorithms/issues/52

**Comment by ElePT** [comment]
Transferred to new repo: https://github.com/qiskit-community/qiskit-algorithms/issues/52
