### ISSUE TITLE
PauliTrotterEvolution doesn't work with 'qdrift'

### ISSUE THREAD

**Issue by BurgerAndreas** [Qiskit/qiskit#8356]
### Informations

- **Qiskit version**: 0.37.0
- **Python version**: 3.10
- **Operating system**: Mac OS Big Sur 11.6.7

### What is the current behavior?

PauliTrotterEvolution doesn't work with 'qdrift', only with 'trotter' and 'suzuki'

Error message:

```
  line x, in my_file
    trotterized_op = PauliTrotterEvolution(trotter_mode='qdrift', reps=1).convert(evolution_op)
  File "/Users/andreasburger/opt/anaconda3/envs/qiskit-sf/lib/python3.10/site-packages/qiskit/opflow/evolutions/pauli_trotter_evolution.py", line 106, in convert
    return self._recursive_convert(operator)
  File "/Users/andreasburger/opt/anaconda3/envs/qiskit-sf/lib/python3.10/site-packages/qiskit/opflow/evolutions/pauli_trotter_evolution.py", line 120, in _recursive_convert
    pauli, time=time, synthesis=self._get_evolution_synthesis()
  File "/Users/andreasburger/opt/anaconda3/envs/qiskit-sf/lib/python3.10/site-packages/qiskit/opflow/evolutions/pauli_trotter_evolution.py", line 110, in _get_evolution_synthesis
    if self.trotter.order == 1:
AttributeError: 'QDrift' object has no attribute 'order'
```

### Steps to reproduce the problem

```
from qiskit.opflow import I, X, Y, Z, PauliTrotterEvolution
from qiskit.circuit import Parameter

hamiltonian = 1.0*(I^Z^Z) # <class 'qiskit.opflow.primitive_ops.pauli_op.PauliOp'>
evo_time = Parameter('t')
evolution_op = (evo_time * hamiltonian).exp_i()
trotterized_op = PauliTrotterEvolution(trotter_mode='qdrift', reps=1).convert(evolution_op)  # error
```

### What is the expected behavior?

PauliTrotterEvolution should work with qdrift, as stated by the documentation:
https://qiskit.org/documentation/stubs/qiskit.opflow.evolutions.PauliTrotterEvolution.html
It works with 'trotter' and 'suzuki'

### Suggested solutions

Unsure. I've tried using

```
from qiskit.opflow import QDrift
trotterized_op = PauliTrotterEvolution(trotter_mode=QDrift()).convert(evolution_op)  # error
```

instead, but that gives the same error message.

**Comment by ShellyGarion** [comment]
I will close this PR since `qiskit.opflow` has been deprecated, and since the current [`PauliEvolutionGate`](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.PauliEvolutionGate) does have a [`qdrift`](https://docs.quantum.ibm.com/api/qiskit/synthesis#evolution-synthesis) method.
Please check the current API and re-open this issue if needed.
