### ISSUE TITLE
plot_state_city axis labels outside figure boundaries

### ISSUE THREAD

**Issue by jmcelroy01** [Qiskit/qiskit#8413]
### Environment

- **Qiskit Terra version**: 0.21.0

Qiskit Software | Version
-- | --
qiskit-terra | 0.21.0
qiskit-aer | 0.10.4
qiskit-ibmq-provider | 0.19.2
qiskit | 0.37.0
qiskit-nature | 0.4.1
qiskit-finance | 0.3.3
qiskit-optimization | 0.4.0
qiskit-machine-learning | 0.4.0

- **Python version**: 

Python version | 3.10.5
Python compiler | GCC

- **Operating system**: 

Linux, OpenSUSE Tumbleweed

### What is happening?

I have a Jupyter notebook dark theme set up. The white space generated by calling plot_state_city is not enough for the figure axis labels to be inside it. 

![2022-07-28_07-56-51](https://user-images.githubusercontent.com/59029169/181499290-c5f94cfb-3837-4e13-a739-93d253968ed6.png)

Setting a higher value for figsize=() seems to correct it, but the labels also get smaller. 

![2022-07-28_07-56-35](https://user-images.githubusercontent.com/59029169/181499654-84621d31-8da1-4e6d-8a90-2eab51cb99a6.png)

It could be because I have a higher DPI monitor. Not sure whether #3315 could be related or not. 

### How can we reproduce the issue?

Use non-default Jupyter notebook theme, then: 

```
bell = QuantumCircuit(2)
bell.h(0)
bell.cx(0, 1)
sv = Statevector.from_label('00')
sv.evolve(bell)
plot_state_city(sv)
```

### What should happen?

The white space generated by calling plot_state_city should include enough space for axis labels, and the labels should maybe scale at least to some extent when figsize is increased.

**Comment by AlexanderGroeger** [comment]
I'll take a look at this issue. Since it's a bit old, it is okay to test and fix it in the latest version?

**Comment by mtreinish** [comment]
Sounds good, I've assigned the issue to you. If you find it's still valid feel free to open a PR to fix it.

**Comment by AlexanderGroeger** [comment]
Thank you @mtreinish! Can confirm this is still an issue in qiskit-terra v0.25.0. Will look into a solution.
![image](https://github.com/Qiskit/qiskit-terra/assets/46076580/a7c6018f-5b4b-4932-83b5-61ed1b03e06c)
