### ISSUE TITLE
Use `dataclass` for `AlgorithmResult`

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit#8437]
### What should we add?

Now that the Python 3.6 support is dropped we can use `dataclasses` in Qiskit. Since our `AlgorithmResult` was essentially a dictionary replacement we implemented ourselves, should we switch to simply using `dataclass` as an algorithm result? 

That would have advantages like
* _much_ less overhead in writing algorithm results since no getters/setters are required (the docs can go into the class docstring)
* access to dataclass features such as easy conversion to dicts or easily creating immutable results

**Comment by Cryoris** [comment]
Seeing 5 thumbs up I take that the outcome of the discussion is -- yes, do it. So I'll remove the label 🙂

**Comment by ElePT** [comment]
Transferred to new repo: https://github.com/qiskit-community/qiskit-algorithms/issues/53
