### ISSUE TITLE
QuasiDistribution/ProbDistribution key change methods behave differently to Counts

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit#8607]
### Environment

- **Qiskit Terra version**: 0.22 
- **Python version**: 3.9
- **Operating system**: MacOS

### What is happening?

The `binary_probabilities` `hex_probabilities` methods of `QuasiDistribution` and `ProbDistribution` return a regular dictionary instance rather than the same original such as is done with `Counts` when converting key types.

### How can we reproduce the issue?

Call `quasi_distribution.hex_probabilities()` will return a regular `dict` for example, while calling `counts.hex_outcomes()` returns a `Counts` object.

### What should happen?

These classes should behave like `Counts` in that changing the type of the keys should not change the type of object so that key types (int, bin, hex) can be switched back and forth as needed.

### Any suggestions?

I think it would make a lot of sense to have a base dict subclass that is just a keyed default dict that can handle the conversion of keys between integer, bitstring and hextring (like counts currently does) for any value types, and then `Counts`, `ProbDistribution`, `QuasiDistribution` could all inherit from this.

**Comment by t-imamichi** [comment]
I tried comparison and saw `Counts.hex_outcomes()` returns a regular `dict` too.

```python
from qiskit.result import Counts, QuasiDistribution

c = Counts({'00': 0.5, '11':0.5})
q = QuasiDistribution({'00': 0.5, '11':0.5})

ch = c.hex_outcomes()
qh = q.hex_probabilities()

print(type(c), type(ch), ch)
print(type(q), type(qh), qh)
```
output
```
<class 'qiskit.result.counts.Counts'> <class 'dict'> {'0x0': 0.5, '0x3': 0.5}
<class 'qiskit.result.distributions.quasi.QuasiDistribution'> <class 'dict'> {'0x0': 0.5, '0x3': 0.5}
```

I'm likely to miss your point. Could you give me an example code?

**Comment by chriseclectic** [comment]
This isn't really relevant anymore with SamplerV2
