### ISSUE TITLE
Rename `parameter_values` to `parameter_vectors` in primitives

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit#8813]
### What should we add?

I have been bothered lately by the fact the we call `parameter_values` to a `Sequence[Sequence[float]]` in the primitives, and I think it is leading to confusion.

I keep coming across with loops like:
```python
for parameter_value in parameter_values:
    ...
```
which seems intuitive but it is semantically wrong, because the type of `parameter_value` here is `Sequence[float]`.

I wanted to propose renaming ~`paramenter_values`~ to `parameter_bindings`. This will make everything more clear imho:
```python
for binding in parameter_bindings:
    for value in binding:
        ...
```

**Comment by Cryoris** [comment]
Since we now also support just passing the `parameter_values` (i.e. `Sequence[float]` instead of a doubly-wrapped) with #8704, is this still an issue? 🙂 Personally, `bindings`to me sounds like it would be a mapping/dict of parameter: value pairs, and `values` sounds more like a list 🤔

**Comment by ikkoham** [comment]
> it would be a mapping/dict of parameter

I feel like same.

**Comment by pedrorrivero** [comment]
I see your point, but I would not feel very comfortable using the supported exception (single entry) to name the general case (multiple entries), unless we did the same for the other args as well (i.e. `circuit` and `observable`  instead of ~`circuits`~ and ~`observables`~). As a matter of fact I would be perfectly fine with this approach as well.

Consistency is key for clarity.

**Comment by ikkoham** [comment]
I thought that $\theta$ itself is a parameter value even if it's a vector, so the list $\[\theta_{0}, \theta_{1}...\]$ is parameter values.

hmm... difficult. how about `parameter_vectors`?

**Comment by pedrorrivero** [comment]
Interesting @ikkoham! I kind of like it tbh, although I probably need to get used to it. It is a good middle ground 🙂

**Comment by Cryoris** [comment]
It's a good point with `observable(s)` and `circuit(s)`! Reading that actually it to me it would be clearest to use
```
circuit observable parameter_values
```
but I'm not sure it's an option to rename the all arguments based on this 😅

**Comment by ikkoham** [comment]
`transpile`'s argument is `circuits`. We used it for consistency.

**Comment by pedrorrivero** [comment]
The more I think about it, the more I like @ikkoham 's idea of calling it `parameter_vectors`!

**Comment by pedrorrivero** [comment]
I have discovered a `ParameterVector` class under `qiskir.circuit` which may be interesting to analyze in this context. I would probably refrain form using it.

**Comment by Cryoris** [comment]
The `ParameterVector` is just a indexed vector of parameters used e.g. in variational ansatz circuits (or even mostly there?). By "refrain from using it", do you mean refrain from using `parameter_vectors` as replacement of `parameter_values`? Or refrain from using a `ParameterVector`? 🤔

**Comment by pedrorrivero** [comment]
I meant refrain from using the `ParameterVector` class. But no strong opinions if you think otherwise, especially after your nice explanation! 😊

**Comment by Cryoris** [comment]
The `ParameterVector` nicely solves some problems we had with parameterized ansätze, like sorting by index if the name is the same (to sort `a b[0] b[1] b[2] ... z` instead of `a b[0] b[1] b[10] .... z`) and adjusting the number of parameters if the ansatz is resized (which e.g. `TwoLocal` circuits allow) 😄 I see how `parameter_vectors` is confusing as name, maybe we need to choose something else in that case 🤔

**Comment by pedrorrivero** [comment]
I honestly like `parameter_vectors`, I just don't want it to be confused with the class 😊 and I agree that `parameter_bindings` may be more confusing

There are only so many synonyms haha but happy to consider alternatives, we have time until the next release

**Comment by t-imamichi** [comment]
I close this because the discussion is obsolete
