### ISSUE TITLE
Chernoff confidence intervals in IAE when summing samples up 

### ISSUE THREAD

**Issue by alexandra-frca** [Qiskit/qiskit#8821]
In the [IAE algorithm](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/algorithms/amplitude_estimators/iae.py), on line 478, shouldn't the probability `prob` be replaced by `round_one_counts/round_shots`? 

In the case where the data from different iterations with the same Grover power are joined together, only the Clopper Pearson confidence intervals seem to consider the joint information, whereas the Chernoff method considers the total shots but the probability of the latest iteration alone.

**Comment by ElePT** [comment]
Transferred to new repo: https://github.com/qiskit-community/qiskit-algorithms/issues/55
