### ISSUE TITLE
Primitives 0.23

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit#8890]
_This issue serves as an index for all major updates to the primitives module towards Qiskit Terra 0.23._

Please visit the relevant issues and/or PRs for specific discussion on each topic, discussion here is reserved for general matters or themes affecting several features.

If a new issue/PR is open and needs indexing here for tracking, please mention this issue so that we can keep track of everything and we will try to update the index accordingly.

### Issues:
- [ ] Debate making all primitives [protocols](https://peps.python.org/pep-0544/)
- [ ] Update signatures
  - [ ] Choose `Sequence`, `Collection`, or `Iterable` for all compound data types
  - [x] #8813 
  - [ ] Disallow positional arguments beyond `circuits`, `observables`, and `parameter_*`
  - [ ] Upgrade `Options` to custom class (keep `**kwargs` in `run` and add them `__init__`)
  - [ ] Implement `Options.to_dict()` (and possibly `Options.from_dict()`) to avoid direct `__dict__` access
- [x] Normalize all observables to `SparsePauliOp` in `run`
- [ ] Normalize input circuits to no measurements in `BaseEstimator`, and all measured if none provided in `BaseSampler`
- [ ] Allow multi-circuit and single observable input, or vice-versa
- [ ] Standardize (optional) transpilaiton stage definition in specification
- [ ] Revisit caching for performance improvements
- [x] #8100
  - [ ] Enforce `tuple` as the type for all data fields
  - [ ] Update statistical information (e.g. `variance`, `std_deviation`, `std_error`)
  - [ ] Enforce statistical information (e.g. `variance = 0` if exact)
  - [ ] Add `compose()` constructor to `BasePrimitiveResult`
  - [ ] Add new `Metadata` type based on `dict`
  - [ ] Add utils to standardize result serialization (e.g. JSON)
  - [ ] Add Result `to_dict()` and `from_dict()`
  - [ ] Use `defaultdict` to report quasi-probabilities
- [ ] Remove deprecated
- [ ] Add `_circuit_key` util
- [ ] Base `_circuit_key` in QASM representation
- [ ] Refactor

### PRs:
- [ ] #8105 
- [ ] #8367
- [x] #9065 
- [ ] #9074

---
_Please, look out for previous work before picking anything up. Some PRs may address several issues._

**Comment by woodsp-ibm** [comment]
I will note we have the `mod_primitives` label which we try to lable issues/PRs with to help manage/find the relevant ones etc.

**Comment by t-imamichi** [comment]
I close this because the discussion is obsolete
