### ISSUE TITLE
Sampler returns incorrect duplicate results

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit#9093]
### Environment

- **Qiskit Terra version**: 3ce1737b2cb1b417c5bf9c41073d3ab4a664a732
- **Python version**: 3.10.7
- **Operating system**: Fedora 36

### What is happening?

I pass 8 different circuits to Sampler. Using the old deprecated syntax, the sampler correctly returns 8 unique distributions. Using the new syntax, only 2 unique distributions are returned, which is obviously wrong.

### How can we reproduce the issue?

[circuits.zip](https://github.com/Qiskit/qiskit-terra/files/9955897/circuits.zip)
```python
from qiskit import qpy
from qiskit.primitives import Sampler


def unique(items):
    unique_items = []
    for item in items:
        if not any(item == x for x in unique_items):
            unique_items.append(item)
    return unique_items


with open("circuits.qpy", "rb") as f:
    circuits = qpy.load(f)

# deprecated syntax
with Sampler(circuits=circuits) as sampler:
    sampler_result = sampler(circuits=range(len(circuits)))
    quasi_dists_1 = sampler_result.quasi_dists

# updated syntax
sampler = Sampler()
sampler_result = sampler.run(circuits).result()
quasi_dists_2 = sampler_result.quasi_dists

# results differ
print(len(unique(quasi_dists_1)))  # prints 8
print(len(unique(quasi_dists_2)))  # prints 2
```

### What should happen?

The sampler should return the correct results.

**Comment by t-imamichi** [comment]
I close this because Primitives V1 is deprecated #12575
