### ISSUE TITLE
Q composer in Jupyter notebook

### ISSUE THREAD

**Issue by Andreas162534** [Qiskit/qiskit#9122]
### What should we add?

A single method, that shows the circuit, q-sphere and the bins with probabilities (like in the Q Composer)  for the current state. 
You could get the Q Composer easys vizualisation together with the code you write in Python, not OpenQASM 2.0.

Thanks for consideration!

**Comment by 1ucian0** [comment]
Thanks for your suggestion. It sounds like a really nice project for the Qiskit eocsystem (similar to https://nonhermitian.org/kaleido/ ).

**Comment by skp-github** [comment]
@1ucian0 If you are not working on it already, please assign it to me I would like work on it. If i understand correctly, the idea is to visualise circuit, q-sphere and probability distributions by just calling one function ?. If you can provide me some of your inputs(how, what features, etc) I can work on it create something similar to https://nonhermitian.org/kaleido/ with a lot of customisations . Let me know your thoughts, thanks :)

**Comment by Andreas162534** [comment]
Thanks!

**Comment by 1ucian0** [comment]
I'm closing this issue as out of the scope for Qiskit. Feel free to open a thread in https://github.com/Qiskit/feedback/discussions/categories/ideas if interested in following up with the idea.

Thanks both!
