### ISSUE TITLE
Deprecate visualize_transition() visualization function

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#9355]
### What should we add?

The visualize_transition() has a number of limitations with it and is really outside the scope of visualizations we want to be supporting in qiskit. We should plan to deprecate and subsequently remove this function from qiskit, it can live as an external library or module for those who would like to retain this functionality moving forward.

**Comment by kdk** [comment]
Can we include in this setting up an external repository with the existing code and moving it to https://qiskit.org/ecosystem/ ?

**Comment by 1ucian0** [comment]
I made a feature request for it in kaleidoscope https://github.com/QuSTaR/kaleidoscope/issues/67 

Finding a place for the function does not have to be a blocker for this issue.

**Comment by YingHongTham** [comment]
@mtreinish has this issue been assigned to someone? I would like to work on it
