### ISSUE TITLE
Equality checks fail for `EstimatorResult` objects

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit#9464]
### Environment

- **Qiskit Terra version**: 0.22.2
- **Python version**: 3.11
- **Operating system**: MacOS

### What is happening?

Equality checks fail in `EstimatorResult` objects because `values` attr is `np.array` and `==` is not well behaved for those.

### How can we reproduce the issue?

```python
from numpy import array
from qiskit.primitives import EstimatorResult

values = list(range(9))
metadata = [{} for _ in values]

result_1 = EstimatorResult(values=array(values), metadata=metadata)
result_2 = EstimatorResult(values=array(values), metadata=metadata)

assert result_1 == result_2
```
Outputs:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [8], line 10
      7 result_1 = EstimatorResult(values=array(values), metadata=metadata)
      8 result_2 = EstimatorResult(values=array(values), metadata=metadata)
---> 10 assert result_1 == result_2
     11 result_1

File <string>:4, in __eq__(self, other)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### What should happen?

Equality should return `True` or `False` appropriately.

### Any suggestions?

We should move to using tuple (i.e. immutable, core python types) instead or `np.array`.

**Comment by t-imamichi** [comment]
It's not a good idea to check equality of floating-point values with `==`. 
There is a simple example in the official documentation https://docs.python.org/3.11/tutorial/floatingpoint.html.
```python
print(0.1 + 0.1 + 0.1 == 0.3)
# False
```

I suggest np.allclose for that purpose.
https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

**Comment by pedrorrivero** [comment]
That is a good point @t-imamichi. 

It might be even better to provide a custom `__eq__` method in the class, overriding the default one for `dataclass`.

Nonetheless, I have to insist in moving away from numpy types though. The `values` field is not even a vector per-se, but a collection of floats, and issues like this will keep coming up.

**Comment by t-imamichi** [comment]
I prefer introducing a utility function of the equality check based on `np.allclose`.
`assert result_1 == result_2` easily fails due to the floating-point numbers even if `values` is tuple.

I don't have a strong opinion of the type of `values` itself. I'm fine to change it from ndarray to tuple.

**Comment by t-imamichi** [comment]
I close this because the Primitives V1 is deprecated #12575
