### ISSUE TITLE
SamplingMinimumEigensolverResult and subclasses thereof when printing

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit#9755]
### What should we add?

Printing a SamplingVQE result shows a limited number of fields -it should show the full result as we do for other algorithms.

AlgorithmResult, which SamplingMinimumEigensolverResult inherits, defines a str which prints all the fields in a manner similar to a dict print with field name and value.

SamplingMinimumEigensolverResult however overrides this https://github.com/Qiskit/qiskit-terra/blob/9d336182f41533888a728609ce9e7102bb143180/qiskit/algorithms/minimum_eigensolvers/sampling_mes.py#L128-L138 and prints a limited amount of information. A user then using SamplingVQE or QAOA and printing the result, unlike other algorithm results that print based off AlgorithmResult, sees just this limited data - no info about optimizer, optimal point etc.

I could see this being removed from SamplingMinimumEigensolverResult - but maybe this was done for a nicer format of the fields it does print. The other thought is to have AlgorithmResult prepended to this; or even rework the code to be more like AlgorithResult except these chosen fields to do an improved format. Bottom line is that I think the SamplingVQE result, or other result subclasses should print all their info.

**Comment by ElePT** [comment]
Transferred to new repo: https://github.com/qiskit-community/qiskit-algorithms/issues/58
