### ISSUE TITLE
Improve main API ref index page

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit#9852]
Often I want to provide a link to an API ref in a question. Even if I know what module its in the seeming lack of any apparent organization on the main page here https://qiskit.org/documentation/apidoc/terra.html means I end up scanning the list up and down trying to find it. At least I know by now the opflow and algorithms are at the end! - earlier I was trying to locate primitives... Even sort alphabetically would help if I know the module, for new users maybe a better organization could be things sorted categorically and perhaps alphabetically under that?

**Comment by jakelishman** [comment]
I think this was largely obsoleted by the move of the documentation to Qiskit/documentation, and some of the additional work that went on there - there are some section headings now.  I'll close this - I think it's more completely managed at Qiskit/documentation now if there's more to do.

**Comment by Eric-Arellano** [comment]
Yes, this was done. Thanks!
